### ISSUE TITLE
Enhancement: tag management, having tags for tags or having a default 'home' tag

### ISSUE THREAD

**Issue by ycardon** [linuxserver/Heimdall#107]
I <3 tags: tags are far more powerful than folders, in real life things belong to multiple categories.

My problem with current tag management in Heimdall is that whenever an item get tagged, it disappears from the home screen. I'd like to have my items accessible under their category section, but I'd also like to have some of them accessible on the home screen because I use them a lot.

I could have created a 'home' tag, associate my most used items to it and point my bookmark to ../tag/home, but then I cannot see other categories since tags has no tags (ie. I cannot set a 'home' tag for my categories).

Or there could be a default 'home' tag that will pin items to the home screen, whether they have been tagged or not.

Both implementations would be fine, the first one is more powerful (and less user friendly)

**Comment by skluthe** [comment]
Would also love to have tags inside of other tags. That would be awesome!

**Comment by anoma** [comment]
+1 for home screen tag

**Comment by KodeStar** [comment]
Hmm, I'll have to have a think on this one, you are absolutely right, I'm just not sure how best to implement it.

**Comment by tbrasser** [comment]
I was about to make duplicates for achieving this. And adding seperate "APPS" that just point me back to the homepage. 

A default home tag would be the most elegant solution I think.

**Comment by RichardUUU** [comment]
+1 for home screen tag. Also, I can currently only apply one tag at a time, so fixing that needs to be part of the solution.

**Comment by halorrr** [comment]
+1 on home screen tag

**Comment by KodeStar** [comment]
Added in 2.2.1
