### ISSUE TITLE
Foundation App Request: OpenMediaVault

### ISSUE THREAD

**Issue by skluthe** [linuxserver/Heimdall#108]
Would love to have OpenMediaVault as an option.

Btw I love that proxmox is already supported! You've been busy!

**Comment by Attoy** [comment]
**Name**: OpenMediaVault
**URL**: https://www.openmediavault.org/
**License**: [GNU General Public License v3 ](https://www.gnu.org/licenses/gpl-3.0.html)
**Summary**: openmediavault is the next generation network attached storage (NAS) solution based on Debian Linux. It contains services like SSH, (S)FTP, SMB/CIFS, DAAP media server, RSync, BitTorrent client and many more. Thanks to the modular design of the framework it can be enhanced via plugins.
**Icon Source**: https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/var/www/openmediavault/images/header_logo.png *

The icon is not 250x250 , I'll try to find a better one.

**Comment by halorrr** [comment]
This can be closed now.
