### ISSUE TITLE
Reverse proxy compatibility 

### ISSUE THREAD

**Issue by anoma** [linuxserver/Heimdall#119]
Heimdall 1.4.3-1.4.6 fix most of the reverse proxy compatibility issues but a few remain.

For example if you edit a tag and save, Hemdall issues a `302` redirect to `http://heimdall` which obviously fails.

This is also true when adding a new application via the dialogue. Also of interest is if you add a new application but omit the URL the warning that a URL is required is returned but the image icon URL then breaks.

Suspect all of these issues stem from a common redirection bug.

**Comment by KodeStar** [comment]
Is this still an issue @anoma ?

**Comment by anoma** [comment]
It was still failing in 1.4.6 last week but since then I have moved away to a non RP setup. If nothing has changed in the last few days it will still be broken, if it has let me know and I will setup something to test it with again

**Comment by norweeg** [comment]
this sounds like a problem with redirects in your reverse proxy, not heimdall.  I've been using the most current Heimdall this entire time and have never had this issue.  What do you use as a reverse proxy and how do you have it configured?

**Comment by aptalca** [comment]
It may depend on the reverse proxy method.

I didn't have success with a subfolder proxy, but it works great when proxied from the root location or form a subdomain.

**Comment by norweeg** [comment]
the container is configured to be at root, so your reverse proxy should strip the path prefix you put ahead of that before forwarding the request

**Comment by Unthred** [comment]
Just started using heimdall and it looks great! But I am having this exact issue, I am running on an unraid server with letsencrypt doing my reverse proxy, everything works fine its just whenever I save anything it takes me to the internal ip address...... but it has actually saved.

Any help would be anazing

Here is my nginx setup for it

`server {
        listen 443 ssl;
        server_name apps.somedomain.com;

        location / {
            auth_basic "Restricted";
            auth_basic_user_file /config/nginx/.htpasswd;
            include /config/nginx/proxy.conf;
            proxy_pass       http://192.168.13.1:8888;
        }
}
`

**Comment by norweeg** [comment]
@Unthred try

`    location / {
        auth_basic "Restricted";
        auth_basic_user_file /config/nginx/.htpasswd;
        include /config/nginx/proxy.conf;
        proxy_pass       http://192.168.13.1:8888;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
    }`

**Comment by aptalca** [comment]
@Unthred 
try proxying the https port of the heimdall container ie. (proxy_pass https://192.168.13.1:port;)

**Comment by Unthred** [comment]
@aptalca that worked! thanks verrrrrry muchly

**Comment by huuub** [comment]
Hmmm sorry to ask but could you explain a little bit more : 
try proxying the https port of the heimdall container ie. (proxy_pass https://192.168.13.1:port;)
What do I need to do exactly.
I have traefik reverse proxy working on docker and want to use the internal IP address on the home network and the https://radarr.myhostname.com elsewhere.

**Comment by mabushey** [comment]
@huuub I'm also using traefik. I don't believe Heimdall supports SSL termination.
