### ISSUE TITLE
Password Protect Settings

### ISSUE THREAD

**Issue by jacobgad** [linuxserver/Heimdall#121]
It would be great if there was an option to password protect settings, that way the dashboard can be publicly facing but no one can randomly change the settings

**Comment by KodeStar** [comment]
Interesting question, but what is the use case?  Like, why would you have the dashboard publicly facing?

**Comment by jonocairns** [comment]
I'm guessing you could have any reversed proxy applications linking from a root domain name. Plex / Ombi come to mind

**Comment by jacobgad** [comment]
Exactly right jono,
I have my apps running through a reverse proxy and password protected. There is no need to password protect the dashboard, just the settings. just want to use it as a homepage to access my publicly facing apps.

thanks for all your hard work!!!

**Comment by jonocairns** [comment]
Are there any security concerns to having Hiemdall internet facing? The only thing that comes to mind is the API key apps... Is there any way someone could do malicious stuff via the backend setup (around php specially)? @KodeStar

**Comment by aptalca** [comment]
You can add password protection through htpasswd. It works with both apache and nginx. Most of my internet facing guis are using it

**Comment by jonocairns** [comment]
I think the use case here is that you want your friends to be able to access the site without a password (pure links don't really require security, they can link to things with security), you just don't want them to change the icons / links etc. @aptalca

**Comment by jacobgad** [comment]
Exactly right Jono

**Comment by anoma** [comment]
This is a dupe request for multiuser support https://github.com/linuxserver/Heimdall/issues/48 as what is needed here is just an anonymous user account with the typical app control limits you would apply to such.

**Comment by NowayIndustries** [comment]
My usecase for something like this would primarily be like a centralized bookmark page. I currently use an Organizr page for this (which has user support so guests can only see certain things), however it was not ment to be used like this (instead much like muximux it will normally show the page in an iframe).

Really all I'd need was some guidance on how to block access to /items/ for example (and any other endpoints that would need blocking) via htaccess or something similair.

**Comment by Ryonez** [comment]
@anoma I wouldn't say that this is a dupe issue, the desired outcomes are quite different, even if the other issue could account for this use case.

I'd like to see support for the configuration parts to be restricted, so it could be used in public instances with less concern.

For now I've set .htpasswd for `/items`, `/tags` and `/settings`. I'm not sure if this will be good enough.

**Comment by thestraycat** [comment]
I agree. It works well as a public facing web portal for ombi and a few others. Simple protection of the settings would be enough for me.

**Comment by KodeStar** [comment]
Implemented in v2.0.0
