### ISSUE TITLE
Allow separate URL for API access

### ISSUE THREAD

**Issue by spacecakes** [linuxserver/Heimdall#122]
It would be great if Heimdall would allow configuration of separate URLs for API access and app access. This is useful when running Heimdall and other web apps in Docker containers on a bridged network. 

For example

- The SABnzbd container might be accessed at its hostname and the port number, in my case ’nas.int:8085’ (changed from default `8080`). However, due to the bridged network this won't work for API access for whatever reasons 
- API access works by connecting Heimdall to the container's internal Docker IP, e.g. `172.168.1.23:8080` or it's Docker hostname, `sab:8080`. But then Heimdall will send me to that adress when trying to launch the web app, which of course wont work since it's internal to Docker

Specifying separate URLs would be great in this case.

**Comment by KodeStar** [comment]
Agreed, will update current enhanced apps so the api url is separate, but prefilled with main url

**Comment by cybercorey** [comment]
I was thinking the same thing the other day! I have all my outward facing proxyed though nginx with basic auth and all local traffic firewalled to the box itself, this would solve my problems aswell :)
