### ISSUE TITLE
Support for local cert authorities

### ISSUE THREAD

**Issue by grOGH** [linuxserver/Heimdall#129]
It would be nice if users could upload or add a self-owned certificate authority (in .pem format) that is then used for validating certificates of all local apps.

For example, I have Pihole use a certificate (for pihole.home.lan) signed with my local CA, which is trusted by my systems and browsers to get secure HTTPS with the web console.

However, guzzlehttp needs an explicit parameter to use the CA, otherwise a 500 error is thrown on API calls:

`$client = new Client(['http_errors' => false, 'verify' => '/etc/ssl/certs/home.lan.pem']);`

So what could be done:

- add a designated location in /config (or a file upload in the settings) to upload the CA file
- have all enhanced plugins use the "verify" parameter with the guzzlehttp client if one is present

so Heimdall can support local HTTPS apps with custom CAs.

**Comment by KodeStar** [comment]
Definitely a good idea I'll have to have a think on how best to implement it as not everybody is using docker, and those that are wouldn't want it to disappear on an update.

**Comment by grOGH** [comment]
I found a different solution - apparently guzzlehttp looks for a php.ini setting to get a bundle of CA certs in one .pem-file, so you can just create one by concatenating all certs (your local CA, letsencrypt..), place it in /config, and set the path in /config/php/php-local.ini:

`config`

**Comment by KodeStar** [comment]
Awesome! How would you feel about creating a pull request on the readme with this information? Maybe adter the reverse proxy section, have something like **Self signed certificates** If you use our docker you can do this...
If not I will add it myself when I get a chance :)
