### ISSUE TITLE
Enhanced App - NZB Get - Download statistics not displaying

### ISSUE THREAD

**Issue by jemcgrath1** [linuxserver/Heimdall#130]
Download statistics not displaying within icon, as per video demo.
NZBGET configured correctly, link working correctly however no stats are displayed.

Selecting the "test" button appears to do nothing.

**Comment by jonocairns** [comment]
are you getting 500 console errors? I was getting something similar for plexpy.

**Comment by jemcgrath1** [comment]
No, no errors, nothing in the logs just "test' function for plexpy API key and NZBGet does nothing.
Additional "status" that should be showing in Heimdall dashboard icons does not appear to work

**Comment by KodeStar** [comment]
@jonocairns - For whatever reason guzzle can't reach the url you are using, see if you can hit it via a browser.  If you are using it in a docker try using the internal docker ip instead, v1.4.7 added the ability to use a different url for the API

@jemcgrath1 - If test doesn't work then it wont work on the dash either, if you come on the discord I should be able to troubleshoot it.

**Comment by jonocairns** [comment]
@KodeStar yea that's the strange part... I can copy paste the url and it returns some valid JSON in the browser. I am already using the internal docker IP to reference plexpy :(

Other things about the setup:
- Hiemdall is on another IP inside a docker container
- plexpy is under a subdirectory `/stats`

**Comment by jemcgrath1** [comment]
@KodeStar Thanks for the offer of assistance at addressing the enhanced apps not functioning at all. Where do you want to start?

**Comment by jemcgrath1** [comment]
Hi All,
@Kodestar - Thanks for the assistance but identified issue after digging around as per discord notes.

Issue was to do with Nginx being used in the container.

For the links to work correctly, primary url had to be set as:
http://<Exposed IP:Port>  of NZBget/Plexpy Containers

Optional URL for enhanced app features required docker internal containername
http://<internal container name:port>

It has been suggested that this should be documented clearly to prevent confusion, or to consider removing the requirement for nginx, the heimdall container should be able to communicate with exposed services on other containers for enhanced applications.

**Comment by jemcgrath1** [comment]
thanks again for the assistance
