### ISSUE TITLE
Document image limitations

### ISSUE THREAD

**Issue by RichardUUU** [linuxserver/Heimdall#131]
There seem to be size limitations for both Icon images and the screen Background Image. It would be nice to know what those are e.g. (max size: xxx by yyy)

Add Application page
Background Image page

**Comment by KodeStar** [comment]
It will depend on how you are running it, the limitation will probably be in your php.ini, I don't think there is any limit imposed by the code.

**Comment by RichardUUU** [comment]
I'm running through the unRAID docker. Thanks.

**Comment by KodeStar** [comment]
From other posts I see you are running the unraid docker @RichardUUU in that case, I just had a quick look, it's currently set at 2MB, it could be set higher, but 2MB should be big enough for most images with a bit of compression.  The problem with increasing it is it will take longer for the page to display initially.  I guess for background images it's probably not a major issue, as it will be cached in the browser.

**Comment by RichardUUU** [comment]
Crossed replies. Thanks so much for checking. And I'd like to say I really appreciate your work on this app.

**Comment by KodeStar** [comment]
@RichardUUU the php.ini is the alpine default but, there is a file in /config/php/php-local.ini where you can put in any setting and it will append php.ini settings, so if you make it bigger in there you should be good to go.

```
post_max_size = 32M
upload_max_filesize = 32M
```

**Comment by RichardUUU** [comment]
You're awesome.

Cheers, Richard
