### ISSUE TITLE
Change Window Title and FavIcon

### ISSUE THREAD

**Issue by RichardUUU** [linuxserver/Heimdall#132]
It would be nice to be able to change the Window Title (Tab), and the FavIcon. 

I'm sure Heimdall means something lovely in some language. In English, it brings to mind a procedure to rescue a choking sheep.

**Comment by KodeStar** [comment]
I'm English... I guess history isn't your strong point - https://norse-mythology.org/gods-and-creatures/the-aesir-gods-and-goddesses/heimdall/ Nor marvel for that matter - http://marvelcinematicuniverse.wikia.com/wiki/Heimdall

**Comment by RichardUUU** [comment]
No offense intended. Mostly just looking to unify the Tab title with related apps.

**Comment by KodeStar** [comment]
You *could* replace the favicon by just changing it, but of course that wouldn't survive an update, I'm trying to work out the use case for changing the title?  What would you change it to, maybe that will give me some context.

**Comment by RichardUUU** [comment]
Actually, thinking about it, the simplest and most universal solution might be the name of the Tag page currently being viewed or (Home).

**Comment by KodeStar** [comment]
Ok, so something like Home - Heimdall, Webapps - Heimdall, Categgory2 - Heimdall maybe?

**Comment by RichardUUU** [comment]
Yes. Although my absolute preference would be: 
MyServerName/Home
MyServerName/WebApps
MyServerName/OtherApps, etc.

I know what Heimdall is, but the people who use my pages won't.

**Comment by gannon145** [comment]
I would also like to be able to modify the title and favicon. For using an outward facing page I would rather have it branded on the tab with my domain information.

If you want to keep some kind of Heimdall branding, I would rather have a small watermark at the bottom of the dashboard page itself.

**Comment by mrAshpool** [comment]
I'd like to add my support for these features.  The end goal being to be able to pin the site as an icon on a mobile device home screen.  On my own little html landing page this required creating multiple images using apples standard (I'm an android user) of apple-touch-icon-114x114-precomposed.png, ..72x72.., ..57x57.. as well as the favicon.ico

As @gannon145 suggested a watermark would be a good substitute for Heimdall's own branding

**Comment by KodeStar** [comment]
You can change the title by changing the APP_NAME in the .env

**Comment by shadowking001** [comment]
Thanks for this long awaited feature, I can't use my NAS without Heimdall anymore !

**Comment by halsafar** [comment]
There is no option for changing the FavIcon.  This would be useful.

**Comment by halsafar** [comment]
If you are running Heimdall via Docker then just mount the icons yourself using mount mappings like:
```
/host/icon-16x16.png:/var/www/localhost/heimdall/public/favicon-16x16.png
/host/icon-32x32.png:/var/www/localhost/heimdall/public/favicon-32x32.png
/host/icon-96x96.png:/var/www/localhost/heimdall/public/favicon-96x96.png
/host/icon.ico:/var/www/localhost/heimdall/public/favicon.ico
```

If you are running outside Docker then every update just replace those files.

**Comment by Amatsuntsun** [comment]
> I'm English... I guess history/mythology isn't your strong point - Nor marvel for that matter 

wow. 

Good job coming off as arrogant and condescending after someone provides some useful feedback.

**Comment by ochompsky** [comment]
> I'm English... I guess history/mythology isn't your strong point - https://norse-mythology.org/gods-and-creatures/the-aesir-gods-and-goddesses/heimdall/ Nor marvel for that matter - http://marvelcinematicuniverse.wikia.com/wiki/Heimdall

not everyone is a neckbeard like you

**Comment by pilotso11** [comment]
In case someone comes across this again, I've solved this on the latest install as follows:
Create a custom folder with icons in it (you need a fairly large list, see below).
Mount it as `/custom/icons`.
Modify `/custom/nginx/site-confs/default.conf` to add a location, putting this just after the default one, i.e. `location / {}`. I did this by mounting another folder under custom.
```
    location ~* /(apple-icon.*\.png|android-icon.*\.png|favicon.*\.png|favicon\.ico|ms-icon.*\.png|heimdall-logo-small\.svg)$ {
        alias /config/icons/$1;
    }

```
Then, in my docker compose:
```
   heimdall:
      volumes:
      - /my/data/heimdall:/config
      - /my/custom/icons:/config/icons:ro
      - /my/cusom/site-confs:/config/nginx/site-confs:ro
```

The full list of images you need is as follows (taken from inspection of the home page and the manifest):
* favicon-16x16.png
* favicon-32x32.png
* favicon-96x96.png
* favicon.ico
* android-icon-36x36.png   
* android-icon-48x48.png 
* android-icon-72x72.png  
* android-icon-96x96.png  
* android-icon-144x144.png  
* android-icon-192x192.png
* apple-icon-57x57.png     
* apple-icon-60x60.png 
* apple-icon-72x72.png     
* apple-icon-76x76.png     
* apple-icon-114x114.png
* apple-icon-120x120.png
* apple-icon-144x144.png   
* apple-icon-152x152.png   
* apple-icon-180x180.png   
* img/heimdall-logo-small.svg
