### ISSUE TITLE
SupportedApp - Tautulli

### ISSUE THREAD

**Issue by halorrr** [linuxserver/Heimdall#136]
Now that PlexPy has switched to Tautulli, either a separate entry should be added from PlexPy or PlexPy should be replaced. The new logo is here:
https://avatars3.githubusercontent.com/u/34385001?s=400&v=4

(Of course this can be done manually from user end in the meantime)

**Comment by halorrr** [comment]
Made a pull request for this #141

**Comment by halorrr** [comment]
Hey just noticed this got added to the Supported Apps column and though I would mention this one should be in the Enhanced app column :)

**Comment by KodeStar** [comment]
fixed
