### ISSUE TITLE
Enhancement: Pinned Tab Icon for Safari

### ISSUE THREAD

**Issue by ycardon** [linuxserver/Heimdall#139]
Hi,

It would be nice to have a pinned tab icon for Safari (it is a special svg favicon, usually just the shape of the favicon, witch is used when the tab is pinned under Safari). 

Right now, Heimdall appears as a blank space when pinned in Safari (between "Google inbox" and "Feedly" in the following example)

<img width="259" alt="capture d ecran 2018-03-13 a 08 23 20" src="https://user-images.githubusercontent.com/1177253/37327759-e01540c2-2697-11e8-8591-635735639e1b.png">

- [specs from Apple](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html)
- [useful webapp for creating favicon resources (Apple, Android, Windows)](https://realfavicongenerator.net) including also special favicons for smartphone homescreen

**Comment by KodeStar** [comment]
Will look into it, thanks

**Comment by KodeStar** [comment]
Seems to work, reopen if still not fixed in v2.0.0
