### ISSUE TITLE
FoundationApp - Watcher

### ISSUE THREAD

**Issue by mikepruett3** [linuxserver/Heimdall#143]
Would be great to at least have FondationApp support for Watcher3 app. (https://github.com/nosmokingbandit/Watcher3) There is an API for this application as well, but I am not much of a Python programmer to even attempt it. :)

**Comment by Attoy** [comment]
**Name**: Watcher3
**URL**: https://github.com/nosmokingbandit/Watcher3
**License**: [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0.html)
**Summary**: Watcher is an automated movie NZB & Torrent searcher and snatcher. You can add a list of wanted movies and Watcher will automatically send the NZB or Torrent to your download client. Watcher also has basic post-processing capabilities such as renaming and moving.
**Icon Source**: I didn't find an icon (yet)

**Comment by halorrr** [comment]
I can create a pull request for this, is it more accurate to put the name in as Watcher or Watcher3 ?

**Comment by mikepruett3** [comment]
Probably Watcher3.
