### ISSUE TITLE
Heimdall through Traefik

### ISSUE THREAD

**Issue by threeefive** [linuxserver/Heimdall#148]
I'm trying to reverse proxy Heimdall through Traefik. Both are running in docker.
However I keep getting a 502 error.

**_Heimdall Container Config:_**
![image](https://user-images.githubusercontent.com/37472484/37554679-190d85ea-2a41-11e8-94c3-7fc394b4353e.png)

**_Traefik Dash:_**
![image](https://user-images.githubusercontent.com/37472484/37554698-4fd97d22-2a41-11e8-99c0-2572446442c7.png)

Any ideas?

**Comment by zul-jin** [comment]
This happens when you try to run the container as root. If you pick a non-privileged user for it, the error won't pop up.

**Comment by KodeStar** [comment]
Will close this, thanks @zul-jin. If this doesn't fix your issue @threeefive feel free to re-open

**Comment by threeefive** [comment]
Thanks @zul-jin that worked perfectly.
