### ISSUE TITLE
Enhancement: Pyload Foundationapp Integration

### ISSUE THREAD

**Issue by inject00r** [linuxserver/Heimdall#152]
Hi all,

it would be nice if Pyload could be added as an application. Additionally the api could be used to show down/up rates in the tile.

Cheers

**Comment by halorrr** [comment]
Please read the guide on how to properly request a foundation app https://github.com/linuxserver/Heimdall/wiki/Requesting-a-Foundation-app

**Comment by halorrr** [comment]
@Attoy Perfect, I've submitted a pull request on it. Thanks for standardizing that formatting for requests by the way. It makes it so quick for me to put together a pull request for foundation apps when I have all that information ready to go.

**Comment by Attoy** [comment]
@halorrr glad to be useful! I'll learn how to do a PR for foundation apps, sooner or later! On a completely unrelated note, are you italian? 🤔

**Comment by halorrr** [comment]
@Attoy Once you get into the rhythm of it, it becomes pretty easy, I also have photoshop so converting the format and sizes of the logos is fast for me. I am trying to learn for to work with the APIs and start making some enhanced apps. Currently I'm playing with Ombi, we'll see if I ever get it done though haha. I'm Canadian actually. Italian and Portuguese background though from my parents.

**Comment by Attoy** [comment]
@halorrr Yeah, I must convince myself to try as I can't break anything, it's just a PR! 😄 Oh, cool. I see your picture with an Italian baseball cap!

**Comment by halorrr** [comment]
@Attoy Just look at my pull requests to see what I'm changing. It is usually only 4 commits unless I forgot something and need to make an extra change. Update the readme, upload the logo, add the app name to item list, and create the php file (copy and paste from an existing foundation app and change the app name, logo name, and default colour). I probably spend the longest time picking the default colour xD
