### ISSUE TITLE
App Request: Syncthing

### ISSUE THREAD

**Issue by armouredking** [linuxserver/Heimdall#163]
Could we get support for this in Heimdall? It'd especially be nice as an interactive app.

**Comment by Attoy** [comment]
**Name**: Syncthing
**URL**: https://github.com/syncthing/syncthing
**License**: [Mozilla Public License 2.0](https://www.mozilla.org/en-US/MPL/2.0/)
**Summary**: Open Source Continuous File Synchronization
**Icon Source**: https://raw.githubusercontent.com/syncthing/syncthing/master/assets/logo-text-128.png

Filed a proper request.

**Comment by halorrr** [comment]
Submitted a pull request for creating as a supported app.
