### ISSUE TITLE
Appropriate Supported Apps

### ISSUE THREAD

**Issue by halorrr** [linuxserver/Heimdall#167]
@KodeStar With the large list of apps Heimdall now supports built in, it has become suitable for me as a browser startpage. I was wondering how you would feel about me submitting pull requests for regular websites such as Reddit or Gmail. Or is you would prefer things stay focused on server applications.

**Comment by KodeStar** [comment]
It's a good question, I don't really have a preferrence, let me see what the rest of the ls.io guys think and I'll get back to you.

**Comment by CHBMB** [comment]
I think it's not a bad idea tbh @KodeStar but this is your baby, I just break it once in a while for you.

**Comment by KodeStar** [comment]
Yeah, I'm not fussed, if pull requests were added I'd probably approve them.

**Comment by zag2me** [comment]
I'd love to see this!

**Comment by CHBMB** [comment]
@zag2me Nothing stopping you submitting a PR ;)

**Comment by halorrr** [comment]
Ok I could definitely create some pull requests for these. So something that needs to be discussed I guess before I go crazy and submit all the things is how do we want the supported services listed. Because if I starting putting them all in the foundations app list, that list is going to get crazy long, crazy fast.

Also I think issue #126 being solved would become very important as we expand the list, because the lighter colour backgrounds are basically unusable right now for readability sake. A full colour picker for text would be awesome, but I'd settle for a white-black shade picker, or even just a choice or either black or white text. 

I'll see if I can make sense of a way to do this, but not sure I have the relevant skills to add it in.
