### ISSUE TITLE
Gap between search button and bar

### ISSUE THREAD

**Issue by aptalca** [linuxserver/Heimdall#17]
v1.1.3
On chrome, there is a gap between the search button and the search bar
On Win edge, there is no gap

<img width="417" alt="capture60" src="https://user-images.githubusercontent.com/541623/35939487-46697c1e-0c1a-11e8-9849-10902a36a930.PNG">

**Comment by sparklyballs** [comment]
don't use chrome

fuck google 

lol

**Comment by aptalca** [comment]
chrome is life

**Comment by sparklyballs** [comment]
it has so much reporting back to google in it that little snitch nearly caught fire

it has totally shitty handling of unsigned certs

**Comment by KodeStar** [comment]
Fixed
