### ISSUE TITLE
Internet explorer rendering issues

### ISSUE THREAD

**Issue by davidtessier** [linuxserver/Heimdall#178]
When I open my new Heimdall instance on internet explorer I get a rendering issue (see screenshot).

![2018-05-07 13_25_50-](https://user-images.githubusercontent.com/1824441/39715154-4807e878-51fa-11e8-8794-e7c522df982e.png)

The output below is all that shows up in the console in IE. The same messages do NOT show up when launched from Chrome.: 

> DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
> File: mydomainname.ca
> HTML1300: Navigation occurred.
> File: mydomainname.ca
> SCRIPT1003: Expected ':'
> File: app.js, Line: 147, Column: 20
> 

I have reset IE to factory settings and I still get the error. Looking for some guidance. I typically use Chrome but now and then I use IE at work. It would be nice for this to launch. What other things can I do to troubleshoot the problem? 

Thanks

**Comment by KodeStar** [comment]
Does it work in Edge?

**Comment by davidtessier** [comment]
I am running IE11 on Windows 7 and can’t say for sure. Though, when I open inspector within IE, it does say I can emulate Edge. No matter which one I chose (8-Edge) it renders the same.

Dave


On May 7, 2018, at 3:28 PM, KodeStar <notifications@github.com<mailto:notifications@github.com>> wrote:


Does it work in Edge?

**Comment by KodeStar** [comment]
Well I'm not running IE at all on my Mac, so I can't say at all ;)  From what I remember though, MS seems to be leaving IE behind in standards in the hope people switch to Edge.  I will try to find a windows PC, but it will be windows 10.  Also the Edge in IE11 is not the same as the browser Edge, it just means it's the latest version.  I'm reluctant to support an out of date OS, especially as MS themselves stopped mainstream support for it 3 years ago, but if there is an easy way to fix it for IE I'll look into it.  Basically it all comes down to the layout using flexbox and IE not having great support for it, but there are some workarounds I can look into.

**Comment by cybercorey** [comment]
Can confirm,
Latest Edge **IS** IE17, IE 11 is hella old now when it comes to new html technologies
*Version number used for Edge is based on the number of EdgeHTML rather than Edge itself. This is because EdgeHTML is the engine for Edge that is related to feature support change.

https://caniuse.com/#feat=flexbox IE11 only has partial support for flexbox layout, you'd have to include some ployfill to get this working... e.g. https://github.com/philipwalton/flexbugs

**Comment by davidtessier** [comment]
Thanks for letting me know. I’ll leave the decision on in your hands on how to proceed. I understand if you don’t want to proceed with a fix.

Dave

On May 7, 2018, at 3:57 PM, Corey Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


Can confirm,
Latest Edge IS IE17, IE 11 is hella old now when it comes to new html technologies
*Version number used for Edge is based on the number of EdgeHTML rather than Edge itself. This is because EdgeHTML is the engine for Edge that is related to feature support change.

https://caniuse.com/#feat=flexbox<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcaniuse.com%2F%23feat%3Dflexbox&data=02%7C01%7C%7C087761be405d404cadc508d5b454bf16%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636613198427471917&sdata=UYYDmIsXuGjhLP28YJonFYCwerdWUf1pTnTfb6YtdPo%3D&reserved=0> IE11 only has partial support for flexbox layout, you'd have to include some ployfill to get this working... e.g. https://github.com/philipwalton/flexbugs<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fphilipwalton%2Fflexbugs&data=02%7C01%7C%7C087761be405d404cadc508d5b454bf16%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636613198427628165&sdata=yXYxUmI1U5romFzRtWeT8qT%2BYy8NTWZMV3kt7qRq8Y0%3D&reserved=0>

**Comment by CHBMB** [comment]
I'm amazed anyone uses either IE or Edge...... not a criticism, whatever works for you.

**Comment by zag2me** [comment]
IE is still the 2nd biggest browser share on the market. Above Firefox Edge and Safari combined ;)

https://netmarketshare.com/

**Comment by KodeStar** [comment]
Not according to the very link you provided.

Those 3 combined come to 19.55% vs IE's 12.28%, combining all 4 of those only comes to just over half of Chromes 60.64% though.

**Comment by CHBMB** [comment]
Put another way, the most popular search query on Bing is `Google Chrome Download`

**Comment by davidtessier** [comment]
I'm going to unsubscribe from the issue since it seems to have derailed a bit. I'm happy to bring it up and it's now in your hands on whether you want to accommodate IE or not. I am not impacted by the decision since I run Chrome, I just wanted to mention it to the developers. have a great day, and keep up the good work. I really like what you've created here.
