### ISSUE TITLE
UnRaid Enhanced Apps Not Working 

### ISSUE THREAD

**Issue by bassrock** [linuxserver/Heimdall#180]
Hi,

I am using heimdall in unraid with a bridged ip address. I am unable to get any of the enhanced apps to work. I have logged into the heimdall docker and i am able to curl the respective urls using the the ip address of the docker and the external forwarded ports.

I saw the note about using the internal docker name and still can't get it to work with that. Any ideas?

**Comment by KodeStar** [comment]
Unfortunately that is due to limitations with unraids docker setup when running in br0 I believe.  I'm not sure if there is a workaround.
