### ISSUE TITLE
Apps keep dissapearing from the dashboard.

### ISSUE THREAD

**Issue by winterscar** [linuxserver/Heimdall#182]
Title says it all. I'm running on docker with the config mounted outside the container, and every so often, I load up Heimdall and my pinned apps have changed. It's never all of them that disappear, just a few.

**Comment by KodeStar** [comment]
Not a lot to go on there and it's the first I've heard of it happening.  Maybe backup the sqlite database and if they change compare the files?  Replace the database with the backed up one (by renaming).  The database should be in /database/app.sqlite in the docker it's outside the container and symlinked, so have a look wherever your config folder is

**Comment by winterscar** [comment]
Sorry for the limited info, I didn't really know what would be helpful. I've made a backup of `www/app.SQLite` (I couldn't find `database/app.sqlite`), and when it changes I will compare them.

**Comment by KodeStar** [comment]
no worries, if it happens again it would probably be worthwhile looking in /storage/logs/laravel.log as well

**Comment by winterscar** [comment]
Ok, so it just happened again. The backup and the file in use are different (different sha-256).
I cant find any file called Laravel.log 
![image](https://user-images.githubusercontent.com/11340175/40312309-6ba33812-5d0a-11e8-8777-f96355b8cbbb.png)

**Comment by CHBMB** [comment]
@winterscar Is the `/config` mount point a local folder, if so what file system.

**Comment by CHBMB** [comment]
And this might be a stupid question, but there's definitely only one instance of Heimdall running....  As in you're not running multiple containers with the same mount point.

Just a thought

**Comment by winterscar** [comment]
`/config` is mounted on a mergerfs disk under `/srv/docker/Heimdall`.

I just checked docker ps and there's only one instance of Heimdall running unfortunately :/

One thing I'm thinking is: I have no password, so is it possible that automated services are crawling links and causing apps to become unpinned? Is that a possibility?

**Comment by j0nnymoe** [comment]
Or you could configure nginx not to ask you for a password on your local lan atleast - this is how I have it setup so I only have to enter my password externally.

**Comment by winterscar** [comment]
Ok, I think I've figured it out. Pins aren't changing now that the site is password protected. Looking at how the dashboard customization works, any old link crawler would toggle a bunch of pins, as they just need to navigate to https://heimdallserver/items/pintoggle/10 and that pinned item is gone. 

So I suspect that google or some such may in fact be to blame here. 

I've solved this for now by adding the following location to nginx: 

```
    location /items {
    }
```

This makes it impossible to edit the pinned items, and has the fortunate side effect of also hiding API keys as well.

**Comment by boehser-enkel** [comment]
I'd like to see an option to toggle that setting or better: set a password für toggling

**Comment by samsong** [comment]
very interesting. I have this issue in 2025 of apps disappearing from pinned on dashboard.
I tested 

/items/pintoggle/appnumberhere

you're right that does toggle the app. I wonder if some internet search engine crawler found it & is toggling them.

i will add a user account login and see if it helps

> Ok, I think I've figured it out. Pins aren't changing now that the site is password protected. Looking at how the dashboard customization works, any old link crawler would toggle a bunch of pins, as they just need to navigate to https://heimdallserver/items/pintoggle/10 and that pinned item is gone.
> 
> So I suspect that google or some such may in fact be to blame here.
> 
> I've solved this for now by adding the following location to nginx:
> 
> ```
>     location /items {
>     }
> ```
> 
> This makes it impossible to edit the pinned items, and has the fortunate side effect of also hiding API keys as well.

**Comment by caco3** [comment]
> they just need to navigate to https://heimdallserver/items/pintoggle/10 and that pinned item is gone.

Wow, this is a bad design. GET requests never should change things, see https://www.w3schools.com/tags/ref_httpmethods.asp: 
- "GET is used to **request** data from a specified resource."
- "POST is used to send data to a server to create/**update** a resource."

**Comment by imeuro** [comment]
i am facing the same problem (heimdall is exposed to internet and randomly my pins appear/disappear/scramble ecc ecc) and setting up a password for the /items directory, i found out this option in the user page - which should be: [https://heimdallserver/users/1/edit](https://heimdallserver/users/1/edit) - to set a password for the account, and more importantly this checkbox (bottom-right) "Allow public access to front - Only enforced if a password is set."

<img width="1082" height="682" alt="Image" src="https://github.com/user-attachments/assets/e8a0ea1d-2d60-436b-b9d8-ad581fa21df1" />

So, when i try to access any "administrative" page, i see this:

<img width="733" height="667" alt="Image" src="https://github.com/user-attachments/assets/02c8449c-d48a-459a-adeb-9b0c0625ecb2" />

let's see if it solves the issue
