### ISSUE TITLE
Foundation App Request: Rancher

### ISSUE THREAD

**Issue by ullbergm** [linuxserver/Heimdall#183]
Name: Rancher
URL: https://www.rancher.com
License: Apache License 2.0
Summary: Rancher is enterprise management for Kubernetes.
Icon Source: [Here](https://github.com/rancher/ui/tree/master/public/assets/images/logos)

**Comment by CHBMB** [comment]
https://github.com/linuxserver/Heimdall/wiki/Foundation-apps

Could always submit a PR, tends to get apps included quicker.

**Comment by ullbergm** [comment]
Good point, I just saw other issues listed as requests and my brain turned off. 

I'll do a PR for it in a bit.

**Comment by ullbergm** [comment]
Do you prefer single PRs per app or one with multiple in it?

**Comment by CHBMB** [comment]
Single

**Comment by ullbergm** [comment]
https://github.com/linuxserver/Heimdall/pull/189

**Comment by ullbergm** [comment]
thanks
