### ISSUE TITLE
Images load as non-https when behind a proxy, can't connect via internal network

### ISSUE THREAD

**Issue by MindTooth** [linuxserver/Heimdall#187]
Hi,

Been tinkering the last day with several docker apps, including Heimdall.

## Issue 1 - Loading images results in warning behind proxy/TLS
Got over this warning when I configured it behind a Traefik proxy w/ TLS.  Also tried looking through the code, but could not understand what I were looking for :P
```log
Loading mixed (insecure) display content “http://battlestation.lan/storage/supportedapps/sabnzbd.png” on a secure page
```

Nothing major, thought I would at least report it.

## Issue 2 - ~Unable to access SABnzbd via internal network.~
~Off-topic:  How do I connect to a container inside a docker network?  Can't seem to make it work with SABnzbd and API support.  Inside the network the container it's called `sabnzbd`, but when using that name, I get the following error.  (I suspect this is because it's behind a proxy, this was not the error message I intended.)~

~Also, I've tried accessing Heimdall via a port wo/ TLS, but got the same error.~
### Solution
Needed to add `:8080` behind `sabnzbd`, making it `sabnzbd:8080`.
### Error still present
NB!  I still have some issue when pressing `test`.  The ones listed below.  Occurs with & without proxy.

### Error Outputs

From Firefox.
```javascript
TypeError: 'stepUp' called on an object that does not implement interface HTMLInputElement.[Learn More] jquery.min.js:2:71314
	i https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:71314
	jt https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:71206
	jt https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:71229
	jt https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:71229
	jt https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:71229
	w.param https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:71505
	ajax https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:75801
	w[t] https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:78092
	<anonymous> https://battlestation.lan/js/app.js:145:9
	dispatch https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:41720
	add/y.handle https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:39774

```

From Safari
```javascript
[Error] RangeError: Maximum call stack size exceeded.
	(anonymous function) (jquery.min.js:2:71125)
	each (jquery.min.js:2:2578)
	jt (jquery.min.js:2:71085)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
	jt (jquery.min.js:2:71232)
```

**Comment by aptalca** [comment]
Use https for the reverse proxy address

**Comment by MindTooth** [comment]
I'm accessing Heimdall using `https://battlestation.lan/`.

You mean this, accessing the background site using https?  Or where specifically did you mean?
```yaml
  heimdall:
    container_name: heimdall
    environment:
      - TZ=`ls -la /etc/localtime | cut -d/ -f8-9`
    image: linuxserver/heimdall
    labels:
      - "traefik.backend=heimdall"
      - "traefik.docker.network=battle_net"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DOMAINNAME}"
      - "traefik.port=80"
      # - "traefik.port=443"
      # - "traefik.protocol=https"
    networks:
      - battle_net
    restart: always
    volumes:
      - ./config/heimdall:/config
```
If enabling the https version, I get an `Internal Server Error`.

**Comment by aptalca** [comment]
I'm not familiar with traefik but you need to make it connect to heimdall through https://heimdall:443

**Comment by MindTooth** [comment]
Just to be on the same page, what particular issue are you referring to?

* Issue 1 loads images from an explicit `http://logo.png` instead of lets say `//logo.png`.
* Issue 2 is somewhat resolved, and it works okay with the current setup.



AFAIK, Heimdall serves its own certificate when accessing the HTTPS variant, and I not sure how that works behind a proxy.  And it is what I suspect is the issue when trying to access it using HTTPS via the backend.  I might be completely off also.

**Comment by aptalca** [comment]
Issue 1

If heimdall thinks the request is coming through http, it will link to http for assets. If it thinks the request is coming through https,it will link to https.

Documented here: https://github.com/linuxserver/Heimdall/blob/master/readme.md#reverse-proxy

**Comment by MindTooth** [comment]
Thanks, @aptalca 😄
I'll do some more testing in issue 1.

What's your thought on issue 2, is that related?

**Comment by aptalca** [comment]
I don't know why you're trying to use direct connection to the container. When you click on the link in a browser, it won't work. You should use the reverse proxy address for sab

**Comment by MindTooth** [comment]
My bad, the SABnzbd issue is solved, I ment the console error 🤣 I guess that might be because I atm. can't proxy the HTTPS version of Heimdall.  Still tinkering.

<img width="357" alt="screen shot 2018-06-04 at 14 20 04" src="https://user-images.githubusercontent.com/33870508/40917121-685ca816-6802-11e8-9a95-336841f27e68.png">

Seems the test feature is broken in Safari, the browser just stalls for a minute. and no message ( neither no message in Firefox).  Am I to expect a message when testing success for the various integrations?

**Comment by MindTooth** [comment]
I'm such a derp!!! 🤦‍♂️

Needed to turn off verification of the self-signed certificated in the backend.

Solution is to set `insecureSkipVerify = true` in the `traefik.toml` config file.

Resources:
* https://docs.traefik.io/configuration/commons/
* https://stackoverflow.com/questions/49412376/internal-server-error-with-traefik-https-backend-on-port-443

**Comment by MindTooth** [comment]
Ended up hardcoding the path to TransmissionBT :satisfied:  Solved the issue.
```php
    private function getApiUrl()
    {
        $url = $this->config->url;
        $url = rtrim($url, '/');
        /* $apiUrl = $url.'/transmission/rpc'; */
        $apiUrl = 'transmission:9091/transmission/rpc';
        return $apiUrl;
    }
```
<img width="308" alt="screen shot 2018-06-05 at 20 34 30" src="https://user-images.githubusercontent.com/33870508/40995631-e6324fae-68ff-11e8-990b-5fb3d2eae71f.png">
