### ISSUE TITLE
Issues with user and pass in url

### ISSUE THREAD

**Issue by wphillips82** [linuxserver/Heimdall#196]
When attempting to add a url using http://user:pass@ip:port format it won’t accept a password with symbols in it. I tried with passwords with ! and * and it gives the error that the url format is invalid.

**Comment by KodeStar** [comment]
It uses a built in laravel function to validate the url, if you want to disable that change all instances (2 of them) of `'url' => 'required|url',` to `'url' => 'required',` in https://github.com/linuxserver/Heimdall/blob/master/app/Http/Controllers/ItemController.php which will be in `/app/Http/Controllers/ItemController.php` locally
