### ISSUE TITLE
redirect after saving item

### ISSUE THREAD

**Issue by Engwer** [linuxserver/Heimdall#211]
I am running running Heimdall in a docker container behind a reverse proxy listening to port 5001 on localhost. Nginx is proxy passing requests from `mydomain.net` to `localhost:5001`. 
Everything is working fine, and I can access my dashboard both from `mydomain.net` and `localhost:5001` and use Heimdall without any problems. However, when I create a new item and hit save, I'm always redirected to `localhost:5001` even when accessing via `mydomain.net` which yields an error.
I nevery faced this problem when installing other web-applications on my server. Can anyone give some advice?

**Comment by KodeStar** [comment]
@Engwer have you tried changing APP_URL in the .env file, not 100% sure it will make any difference but worth a go.
