### ISSUE TITLE
Actual release zip w/ Heimdall to running from a separate folder

### ISSUE THREAD

**Issue by kaysond** [linuxserver/Heimdall#212]
The installation instructions say to clone the whole repository, or download the zip (which is still the whole repository), and point the document root to Heimdall's public folder. (Or get the docker container). I'd prefer to be able to download a an archive containing a single folder (e.g. "Heimdall") with only the necessary files, and not the whole repo. Then I can easily either run Heimdall directly through its own path - e.g. domain.com/heimdall - or via reverse proxy - e.g. heimdall.domain.com proxied to another http host or vhost.

Right now my solution is to download the repo, delete all of the unnecessary development files, and do an `include("heimdall/public/index.php");` in my own index.php which is super clunky...

**Comment by kaysond** [comment]
I take it back. That doesn't really work at all since all the relative links in the page are then broken... The goal is to have my domain root (i.e. /index.php) to be Heimdall without forcing me to set the document root to /Heimdall/public, causing all the other pages to be inaccessible...

**Comment by KodeStar** [comment]
What development files are in the zip?  Pointing the document root to heimdall/public is just the way Laravel works I'm afraid.  Plenty of people have got it working with reverse proxy though.

**Comment by KodeStar** [comment]
Well I just downloaded the zip to see, so I'll try to break it down.

> The zip is the whole repo right? So it has all the unit testing stuff, git files, etc. I realize it takes an inconsequential amount of storage, but it would be nice to have a zip with just the necessary files.
Nope, the .git is not included, there is a .gitattributes and a .gitignore but that's not even remotely close to having the git folder, also there is no node_modules folder which is what would have all the development stuff in... so yeah, it's pretty much only what you need.

> Maybe it's a Laravel thing (don't think it is..), but most php based projects I've used would have all of the includes as sub directories to the main files, rather than having them all at the same level of hierarchy (i.e. public/app/).
Having the app outside the document root is a best practice security thing, which is how Laravel works be default and I'm unlikely to try changing that.  That said it shouldn't really affect you if you are setting your nginx/apache2 config correctly.

> There's also the issue of the document path of the http side. If I want to do an include("Heimdall/index.php")
I can't think of any reason why that would be something you should do...

**Comment by MindTooth** [comment]
The repo in its current form is the application.  There is nothing that is not needed — except the readme and the Git files.  The ZIP don't include `.git`.

When deploying, one would clone the repo, run `composer install` (however, Heimdall does include the `vendor` folder already), `npm install` & `npm run prod`.  That compiles/minifying the necessary files that goes into `/public`.  Afterwards you remove `node_modules` to save space. Even the `resources` folder can be removed, but only saves 654 kb.

**NB!** Take note that the current project include everything that you need to run the application.  We make sure to compile the source files if they change — meaning the `/public` folder inside the repo is ready to run.

PHP's [`include`](https://secure.php.net/manual/en/function.include.php) is just to include single files, simple logics.  The example provided by the manual shows, they use `include` just to add a simple `vars.php` file.    However, with a complete application like Heimdall, it requires that you provide it with its own Apache/NGINX/Traefik service.  As with many frameworks, they serve the page from a folder inside the application folder.  And it requires all the files in root to function.

Maybe the Laravel documentation on [deployment](https://laravel.com/docs/5.5/deployment) might help you out.  And we will happily help out with problems you might have running Heimdall.

**Comment by kaysond** [comment]
So I looked into laravel a bit more, and I think what I'm looking for would be a user-customizable route prefix. Though maybe that wouldn't quite achieve what I need.

> Having the app outside the document root is a best practice security thing, which is how Laravel works be default and I'm unlikely to try changing that. That said it shouldn't really affect you if you are setting your nginx/apache2 config correctly.

Yea that did occur to me, but it does indeed cause a problem in this odd usage scenario that I'm trying to work out.

> The repo in its current form is the application. There is nothing that is not needed — except the readme and the Git files. The ZIP don't include .git.
Oops! You're right. I think I was looking in my git folder and not the spot I unzipped the release. However, it does seem that you can remove the whole `tests` directory...

So, my usage scenario is admittedly a little odd, and probably not worth your time in supporting, but let me try to clarify what it is I'm trying to do - 

I have an existing domain, with its main vhost pointing to /var/www -  accessed via `domain.com` and `www.domain.com`. What I'd like to do is have `domain.com/index.php` bring up Heimdall. However, I want to keep access to all of the other files and subdirectories in my current document root, which are accessed by things like `domain.com/file.php` `domain.com/file2.php` `domain.com/directory/file.php`, etc.

Correct my if I'm wrong, but my only current option would be to merge my existing documentroot with that of `Heimdall/public`, as in, I'd unzip the repo into `/var/`, and copy `Heimdall/public` to `/var/www/`. This would be super messy and hard to manage.

I realize that Laravel apps are really meant to be put in their own vhost. But I can't think of any way to make this work with apache2 config, or rewrites, or anything.

**Comment by MindTooth** [comment]
Thank you for taking the time to explain the desired outcome a bit more.

I would stay away from merging said files.  If they are individual files, you might be able to serve these.  But I think that the standalone files/folder should be under its own subdomain. or its own directory.  As long as that directory don't occupy the same space as a Heimdall address.

My general tip would be to stay away from the thought of merging two projects.  It might cause more headaches than desired.  And that would be something above what Heimdall provides.
