### ISSUE TITLE
Reverse proxy Webicons don't show

### ISSUE THREAD

**Issue by thestraycat** [linuxserver/Heimdall#219]
Hi guys,

I understand that maybe this is reverse proxy specific... But I'm using the following block in my nginx proxy, that were mentioned in a previous issue on github.. however for some reason i just cant get the webicons to show! Everything else works perfectly, I've tried it on http and https...

# HEIMDALL
     location / {
      #  auth_basic "Restricted";
      #  auth_basic_user_file /config/nginx/.htpasswd;
        include /config/nginx/proxy.conf;
        proxy_pass       http://192.168.1.125:86;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
    }

and 

# HEIMDALL
     location / {
      #  auth_basic "Restricted";
      #  auth_basic_user_file /config/nginx/.htpasswd;
        include /config/nginx/proxy.conf;
        proxy_pass       https://192.168.1.125:446;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
    }

Any ideas why only the webicons are effected? (Picture attached)

![webicons](https://user-images.githubusercontent.com/9296295/41657141-4b104166-748a-11e8-9627-b6fe5d044017.JPG)

**Comment by MindTooth** [comment]
If you open the web tools of your browser, and give it a refresh, we can see of some resources is not loaded correctly.  Be sure to navigate to the console view.

E.g.:

![console-drawer](https://user-images.githubusercontent.com/33870508/41676978-5fbfe1f6-74c7-11e8-8d6f-d8edda09b24e.png)

**Comment by KodeStar** [comment]
No response so closing
