### ISSUE TITLE
Deluge "test" button doesn't work

### ISSUE THREAD

**Issue by kaysond** [linuxserver/Heimdall#229]
I've added Deluge as an "enhanced" app, but when I put the password in and click test, nothing happens. The browser console shows `TypeError: override_url is undefined`

**Comment by Mikrz** [comment]
I found what the issue itself is, and it is due to an attempt at setting an `override_url` variable to a nonexistent text field:
```javascript
//app.js
var override_url = $('#create input[name="config[override_url]"]').val();
if(override_url.length && override_url != '') {
/*line 133:*/    apiurl = override_url;
/*line 134:*/    }
```
This seems to set

**Comment by Mikrz** [comment]
I found what the issue itself is, and it is due to an attempt at setting an `override_url` variable to a nonexistent text field:
```javascript
//app.js line 131-134
var override_url = $('#create input[name="config[override_url]"]').val();
if(override_url.length && override_url != '') {
    apiurl = override_url;
}
```
Because the function doesn't check for type == undefined, it just fails at hitting the length check.

**Comment by kaysond** [comment]
Thanks for getting to the bottom of it!

**Comment by Mikrz** [comment]
Unfortunately, just looking at the repo has me scratching my head about how to actually patch this as I'm completely unfamiliar with the frameworks being used. I can't get the actual activity monitor to work, as the edits I could make to app.js just fix it in the config popup, but not in the main display.

It probably just needs the API text field re-added, but I have no idea where that would be done so someone else will have to figure that out.

**Comment by KodeStar** [comment]
https://github.com/linuxserver/Heimdall/blob/master/resources/views/supportedapps/deluge.blade.php

Just needs the following adding after the hidden field(line 3):
```
    <div class="input">
        <label>{{ strtoupper(__('app.url')) }}</label>
        {!! Form::text('config[override_url]', null, array('placeholder' => __('app.apps.override'), 'id' => 'override_url', 'class' => 'form-control')) !!}
    </div>
```

**Comment by KodeStar** [comment]
Looks like that needs adding to Couchpotato and Deluge as well, the rest have it.

**Comment by marcinozga** [comment]
Deluge config is really broken, but it's identical to Transmission, so simple file replacement fixes it. This is how my deluge file looks like:
```<h2>{{ __('app.apps.config') }} ({{ __('app.optional') }})</h2>
<div class="items">
    <input type="hidden" name="config[enabled]" value="1" />
    <input type="hidden" data-config="type" class="config-item" name="config[type]" value="\App\SupportedApps\Deluge" />
    <div class="input">
        <label>{{ strtoupper(__('app.url')) }}</label>
        {!! Form::text('config[override_url]', null, array('placeholder' => __('app.apps.override'), 'id' => 'override_url', 'class' => 'form-control')) !!}
    </div>
    <div class="input">
        <label>{{ __('app.apps.username') }}</label>
        {!! Form::text('config[username]', null, array('placeholder' => __('app.apps.username'), 'data-config' => 'username', 'class' => 'form-control config-item')) !!}
    </div>
    <div class="input">
        <label>{{ __('app.apps.password') }}</label>
        {!! Form::text('config[password]', null, array('placeholder' => __('app.apps.password'), 'data-config' => 'password', 'class' => 'form-control config-item')) !!}
    </div>
    <div class="input">
        <button style="margin-top: 32px;" class="btn test" id="test_config">Test</button>
    </div>
</div>
```

**Comment by KodeStar** [comment]
@marcinozga thanks for that, I've updated the master version
