### ISSUE TITLE
Open new tab is always overwriting the same tab

### ISSUE THREAD

**Issue by IceBoosteR** [linuxserver/Heimdall#237]
Hi all,

when I click on a button on the Heimdall GUI, the website behind that button is opened, for example Plex. When I now return to Heimdall, and want to open another application like Jenkins, the same tab used for Plex is used for Jenkins now. So it is only possible to opne one application with Heimdall at the same time.

I would like that Heimdall is always openiong a new tab, and is not reusing the same, so I can open multiple applications.

I am using latest Firefox (61.0.1 currently).

-IceBoosteR

**Comment by KodeStar** [comment]
So go to settings and change it?

**Comment by IceBoosteR** [comment]
You are absolutely correct. Haven't seen that.
Thanks.
-Closed
