### ISSUE TITLE
Increase maximum background image upload size

### ISSUE THREAD

**Issue by git-zombie** [linuxserver/Heimdall#239]
As a Heimdall user, I want to upload a high-res background image so that Heimdall looks pretty on my ultra-wide. 

*Background:* 
- I was trying to upload a 3.87MB image and Heimdall was reporting a successful change but would not actually change the image. 

*Specific Fix:* 
Adding the line `upload_max_filesize =  10M` to my php-local.ini file increased the limit for upload and allowed me to upload the 3.87MB image I had been working with.

*Possible solutions:* 
- Document the specific fix above in the readme for the user to implement
- Include the increased upload size fix (shown above) as a default
- Notify the user in the dialogue of the max file size 

Relates to: #4

**Comment by KodeStar** [comment]
For anyone with the same issue, this is specific to the docker rather than heimdall itself, no restrictions are placed within Heimdall itself, I asked the OP to add this issue so I could look at adding better error trapping for when it fails to upload

**Comment by JTT-JustTheTip** [comment]
I am unable to find the readme you're refering to in my docker config directory, what should I be doing to edit the file size limit?

**Comment by j0nnymoe** [comment]
https://github.com/linuxserver/Heimdall#new-background-image-not-being-set

**Comment by JTT-JustTheTip** [comment]
Just worked it out as i posted this, thanks for the speedy response though!

**Comment by doodlebro** [comment]
This issue should be re-opened. There is a secondary limit (around 8MB) regardless of what is set in php-local.ini. I am not sure what is setting this alternate limit. I tried setting upload_max_filesize = 30M and 10M and checked the error logs when I kept getting 413 responses back:

> POST Content-Length of 8553000 bytes exceeds the limit of 8388608 bytes

After this, I tried a half size file of the same image, which worked.

**Comment by HannesJo0139** [comment]
> This issue should be re-opened. There is a secondary limit (around 8MB) regardless of what is set in php-local.ini. I am not sure what is setting this alternate limit. I tried setting upload_max_filesize = 30M and 10M and checked the error logs when I kept getting 413 responses back:
> 
> > POST Content-Length of 8553000 bytes exceeds the limit of 8388608 bytes
> 
> After this, I tried a half size file of the same image, which worked.

I'm a bit confused too, since increasing max filesize worked for me some months ago. However, adjusting max post size solves the issue.

```
upload_max_filesize = 20M
post_max_size = 20M
```
