### ISSUE TITLE
Foundation App Request: Bitwarden

### ISSUE THREAD

**Issue by Haxy89** [linuxserver/Heimdall#241]
**Name: Bitwarden**

**URL: https://bitwarden.com**

**License: GNU GPLv3**

**Summary: Open source password manager**

**Icon Source: https://github.com/bitwarden/web/blob/master/src/images/icons/mstile-150x150.png**

Please use live data displaying like current pass count etc.

**Comment by ABOTlegacy** [comment]
No live data, but look at pull request #258

**Comment by Haxy89** [comment]
Better than nothing, Thanks :)
