### ISSUE TITLE
v1.4.14 - Bad Request when saving Tab options

### ISSUE THREAD

**Issue by jennec** [linuxserver/Heimdall#247]
After upgrading to v1.4.14 I get the following error when saving Tab options:

400 Bad Request
The plain HTTP request was sent to HTTPS port

I took a look at the HTML presented to the browser and it seems that there is a specific http://**** url specified instead of a relative URL which is breaking the submit button for me when offloading SSL on an NGINX reverse proxy.  

Could you please take a look at amending this in your next release?

Thank you.

**Comment by aptalca** [comment]
Is your proxy pass directive pointing to an http or https address?

**Comment by aptalca** [comment]
Change that to https and use the https port. It's in the readme.

**Comment by jennec** [comment]
Whilst this did fix the issue, it was not the only issue that was contributing to this behavior.  It seems that, somehow, during the creation of new containers within Docker MAC addresses on the Bridge network were duplicated.  This was causing my slow down issues as well as issues I had with other containers.  Once i gave them unique MAC addresses everything started to work nicely.  

Thanks for your help.
