### ISSUE TITLE
Traefik and heimdall

### ISSUE THREAD

**Issue by piersonjarvis** [linuxserver/Heimdall#251]
I'm having an issue with heimdall behind a traefik reverse proxy. I can run heimdall all by itself without a problem, but as soon as I put it behind an https traefik reverse proxy I can't save new apps, I get a security warning, then after I hit save the add app window closes and no new app is added.

I can add both docker-compose files for each of these, along with the traefik.toml file if it would help. 

I heard that several people got this working, I just can't figure it out myself.

**Comment by yoyos** [comment]
+1, just had the problem too today

my docker compose:

`version: '3'
services:
  web:
    image: linuxserver/heimdall
    restart: always
    volumes:
      - /data/docker/heimdall/config:/config
    environment:
      TERM: xterm
      PGID: 33
      PUID: 33
      TZ: Europe/Brussels
    labels:
      - traefik.backend=heimdall
      - traefik.frontend.rule=Host:home.ambidev.com
      - traefik.protocol=http
      - traefik.port=80
      - traefik.frontend.entryPoints=http,https
    container_name: heimdall
    networks:
      - web
networks:
  web:
    external: true`

**Comment by yoyos** [comment]
duplicate https://github.com/linuxserver/Heimdall/issues/245
