### ISSUE TITLE
HTML parasites

### ISSUE THREAD

**Issue by yoyos** [linuxserver/Heimdall#252]
Hello, since docker hub build 75 I have this top of my heimdall:

![image](https://user-images.githubusercontent.com/1993859/46257672-e97dd100-c4bd-11e8-8b26-4e28b4f96a17.png)

With docker hub build 76 I have this top of my heimdall:

![image](https://user-images.githubusercontent.com/1993859/46257689-45e0f080-c4be-11e8-8e36-6d6dc847807f.png)

I don't have this under build 74 :)

**Comment by KodeStar** [comment]
Should be fixed now

**Comment by gkoerk** [comment]
I get that error every time I try to add or remove an item on the list (NULL).

**Comment by KodeStar** [comment]
@gkoerk Not an error, it was a debug message to make sure https forcing was working, I just forgot to comment it back out.  Should have had zero effect on the actual working of the app though.  If you can''t add items that's more likely a different issue, maybe wrong permissions on the database.
