### ISSUE TITLE
Uploading background gives error 500 if done by http

### ISSUE THREAD

**Issue by TrashCanMan** [linuxserver/Heimdall#255]
As the title say, im using the [aarch64 docker version](https://hub.docker.com/r/lsioarmhf/heimdall-aarch64/) and everything works fine, i created the docker with all default options exept the ports (i used "-p 28080:80 -p 2443:443") and i created several icons, i activated the search bar, i even use it as start page now, but when i went to upload a background image i was getting a 500 error after selecting the file and pressing save but only when using http (port 28080 in my case), when i tried the https access (in port 2443 in my case) uploading worked fine, after that i returned to use the http port and i have the new image working correctly. As said i solved the problem myself by accessing temporarily by https but imo its a problem that needs to be at least watch unto.

I was getting this on error.log at about the time of the error:
2018/10/03 17:21:47 [crit] 287#287: *971 open() "/var/tmp/nginx/client_body/0000000011" failed (13: Permission denied), client: 192.168.1.214, server: _, request: "POST /settings/edit/2 HTTP/1.1", host: "omv:28080", referrer: "http://omv:28080/settings/edit/2"

I think that this is not a permissions problem since im totally able to upload icons correctly on http, the problem is only with backgrounds.

I dont think it is important but the image in question is [this](https://i.imgur.com/KwyKFHo.jpg) image, downloaded first to my desktop and uploaded with chrome to heimdall.

**Comment by KodeStar** [comment]
I just tried it with http and didn't have any issues, so I'm not really sure how to debug this one.
The error seems to indicate a permissions issue, but I have no idea why it would only affect http and not https... have you tried http again afterwards to see if it was still an issue?

**Comment by KodeStar** [comment]
No response on this, closing for now feel free to re-open if someone has any further information
