### ISSUE TITLE
Heimdall2 just shows blank page

### ISSUE THREAD

**Issue by tailwheeldriver** [linuxserver/Heimdall#267]
I just upgraded to Heimdall2 in the same way I installed the first Heimdall, but now I'm only getting a blank white page. I"m not sure if this is Heimdall or something I didn't do with apache. 

I"m still a bit of a linux newbie, don't hesitate to tell me I missed something obvious.

Server is Ubuntu 16.04 with LAMP stack. 

I cloned the repo and copied everything in the folder to /var/www/html/Heimdall/, then
`sudo chmod 777 /var/www/html/Heimdall && sudo chown -R www-data /var/www/html/Heimdall`
my heimdall.conf page looks just like it did for the last install:

> <VirtualHost *:80>
	ServerName start.myserver.com
	ServerAlias www.start.myserver.com
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html/Heimdall/public/
        <Directory /var/www/html/Heimdall/public>
		Options -Indexes +FollowSymLinks +MultiViews
		AllowOverride All
		Require all granted
	</Directory>
</VirtualHost>

For testing purposes, start.myserver.com is pointed to by my routers DNS resolver, nothing changed there since the previous Heimdall version. 

Also ran 'service apache2 restart' for good measure, still just a white page.

**Comment by KodeStar** [comment]
What version of PHP are you using?

**Comment by tailwheeldriver** [comment]
That was it! Ubuntu 16 repos only have PHP 7.0. I installed php7.3 from the ppa described in this guide: https://tecadmin.net/install-php-7-on-ubuntu/
Switched apache from using 7.0 to 7.3 and 2.0.2 works great now.
I like the new users feature, thanks for the great work.
