### ISSUE TITLE
Disable enforcement of HTTP/HTTPS

### ISSUE THREAD

**Issue by greenaar** [linuxserver/Heimdall#268]
I'm trying to run this in a kubernetes cluster.

For a number of reasons, I don't want to rely on the built-in nginx to handle the ssl certificate.  As such I have port 80 exposed to my service mapper, which then serves that to my ingress controller, which handles all of the SSL/TLS stuff.

Fine.. except heimdall seems to map absolute urls (including http/https prefix).

Is there a way to disable that behavior?

**Comment by aptalca** [comment]
If I understand correctly, you're reverse proxying heimdall through ingress. When you do, why don't you use the https address/port for heimdall in the proxy conf?

So your user connects to https://your.domain:443, and your reverse proxy connects to and serves https://heimdall:443

See here: https://github.com/linuxserver/Heimdall/blob/master/readme.md#reverse-proxy

**Comment by KodeStar** [comment]
Either point to https://heimdall:443 as @aptalca said or add FORCE_HTTPS=true to you .env, it's mentioned in the README.
