### ISSUE TITLE
Use REMOTE_USER rather than HTTP_AUTHORIZATION for basic authentication

### ISSUE THREAD

**Issue by carlchan** [linuxserver/Heimdall#275]
Right now it looks like the proxy authentication depends on HTTP_AUTHORIZATION, which decodes to PHP_AUTH_USER and PHP_AUTH_PW.  Is it possible to change this to a more general support for the REMOTE_USER variable instead?  Not all proxy authentication modules provide the password encoded in the HTTP_AUTHORIZATION header, as currently set up this means that a number of them cannot be used.

So long as REMOTE_USER matches a known username, that should be sufficient to authenticate the user without needing to pass their password to the app as well.

**Comment by KodeStar** [comment]
Got any more details on REMOTE_USER?  Don't see an issue adding that.  I don't use RP though so the support is a bit "experimental"

**Comment by carlchan** [comment]
Well the section I was looking at was in app/Providers/AppServiceProvider.php lines 57-72.  The part I get stuck on is where it tries a "Auth::attempt($credentials)".  REMOTE_USER is just another environment variable sent by the authenticating webserver, it's intended to be a trusted username, so the password is processed by the proxy authentication module.  If not authenticated, REMOTE_USER will not be populated.

So when auth::attempt tries to run, there is no password included, it's just the username from REMOTE_USER, and I think it's failing there? REMOTE_USER is still potentially safer that way because the application never sees/stores the password at all, it just has to trust the proxy to do the authenticating properly.

**Comment by KodeStar** [comment]
This is currently added on master, if anyone wants to test if it works and report back (I don't use it myself) I'd appreciate it. You can test by pulling the `linuxserver/heimdall:development` docker instead of `:latest`

**Comment by KodeStar** [comment]
Added in 2.2.2, let me know if this hasn't fixed it and re-open
