### ISSUE TITLE
[Feature Request] Search button color

### ISSUE THREAD

**Issue by kaysond** [linuxserver/Heimdall#277]
Super small thing, but it'd be nice to have a setting for the color of the search button. I went in and changed it by hand, but it'll get clobbered on updates.

**Comment by TheGammelgalopper** [comment]
It should be possible to install this project via git. Then you can make your changes and keep those. Or so I've heard...

Or you could write a small script, that automatically resets that hex value every day or so

**Comment by kaysond** [comment]
That's what I've been doing, manually.

**Comment by KodeStar** [comment]
v2.3.0 has a custom css section in the settings
