### ISSUE TITLE
Stay Logged In feature

### ISSUE THREAD

**Issue by yamlCase** [linuxserver/Heimdall#278]
When utilizing Heimdall's user authentication feature, the user has to log in once a day.  It would be nice to allow the user to stay logged in indefinitely once authenticated.

**Comment by blakkmaan** [comment]
same here, maybe a possibility to set the duration of the login cookie or a checkmark if you wanna stay logged in. for some reasons a daily based relogin is great but for some its not that necessary. i think a infinitely set cookie is great for my purpose as the family and i uses heimdall as their startpage and everyone got their own device to do so.

**Comment by iruoy** [comment]
This is a built in Laravel feature https://laravel.com/docs/5.7/authentication#remembering-users

If the default LoginController is being used it's very easy to enable.

**Comment by KodeStar** [comment]
Should remember by default since 2.2.2.
