### ISSUE TITLE
You are missing php-zip

### ISSUE THREAD

**Issue by jsiebach** [linuxserver/Heimdall#283]
Receiving this error on a fresh install:

`You are missing php-zip`

Installed using this guide: https://blog.heimdall.site/index.php/2018/02/28/installing-heimdall-on-unraid-in-under-2-minutes/

I am not sure, do I need to get `php-zip` installed on my unRaid server?  Or is this an issue with the `linuxserver` repository?

**Comment by jsiebach** [comment]
I just ran an update and it is now working.

**Comment by TheGammelgalopper** [comment]
I updated just now and have the same problem...
