### ISSUE TITLE
Add "private" apps

### ISSUE THREAD

**Issue by Cerbis** [linuxserver/Heimdall#285]
Is there a way to add custom/private (fundation/enchanced) apps to the dashboard?

**Comment by KodeStar** [comment]
Yep, copy the files from one of the other apps in `/app/SupportedApps/`, change the app.json, make up a new appid then go to the root of the app and type `php artisan register:app Foldername`. Make sure you update the Appname.php to match the Foldername, and the classname inside the Appname.php.  If you are running in docker the SupportedApps folder is in the config folder and you will need to run `docker exec -it heimdall bash` then go to `cd /var/www/localhost/heimdall/` before running the command.

**Comment by amorphobia** [comment]
Hi @KodeStar ,

I'm trying to add a new app. I followed the instruction s and saw "Application Added - <App Name> - <App ID>". However, I could not find it in application type list at http://localhost/items/create page. Would you please help?

Thanks!

**Comment by JeziL** [comment]
@amorphobia check this [#862 ](https://github.com/linuxserver/Heimdall/issues/862#issuecomment-1149051534).
