### ISSUE TITLE
Uploaded icons on wrong path

### ISSUE THREAD

**Issue by joaopsys** [linuxserver/Heimdall#289]
Uploaded icons are being uploaded to:
storage/app/public/icons/

instead of:
public/storage/icons/

**Comment by jackyaz** [comment]
Ah we raised at same time!

#290

**Comment by slimshizn** [comment]
Same thing just happened. Glad I wasn't the only one.

**Comment by slimshizn** [comment]
Also Tautulli, Pihole, are not working.

**Comment by slimshizn** [comment]
This was an update, pihole stopped showing information on heimdall as well as tautulli. I also have no icons showing up. This happened after a update in a docker container on Unraid.

**Comment by KodeStar** [comment]
1. Make sure you have the latest version of the docker
2. Go to the items section.
3. Click Update apps list button
4. Go into each item and make sure the correct app is specified in the dropdown next to the item name, if not change it, if it is try changing it to something else then back again.

**Comment by slimshizn** [comment]
Seems to have fixed it this morning, thank you.

**Comment by joaopsys** [comment]
This is still not working for me and I don't see public/storage/icons as a symlink:

public/storage/icons has all the *.png for the different applications and storage/app/public/icons/ has my uploaded icons (which I have to move to the first folder for them to show)

**Comment by KodeStar** [comment]
Are you using the docker?

**Comment by joaopsys** [comment]
Nope, using it raw, git pulling and pointing my nginx to it

**Comment by joaopsys** [comment]
I deleted the storage folder to test it out and it created a symlink, but now all the app icons are gone (since they were inside that folder). 

Anyway, I will revert it back to how it was, I'm fine with adding the uploads manually as long as it works.

**Comment by joaopsys** [comment]
I basically moved the icons to the symlink destination, and I guess it's working as expected for now :)
