### ISSUE TITLE
Problem using Caddy

### ISSUE THREAD

**Issue by MrKitty871** [linuxserver/Heimdall#295]
I am having an issue serving Heimdall from windows using CaddyServer.
I have the root set to d:\caddy\www\public per the documentation. The page loads seemingly fine and I can see the dashboard and there are no errors. But when I click the "add an application here" it takes me to domain.net/items/create and gives me a 404 error. Any link I click on the main dashboard gives me a 404. 
This is my CaddyFile
`domain.net {
	tls {
		dns cloudflare
	}
	gzip
	on startup d:\xampp\php\php-cgi.exe -b 6545 $
	fastcgi / 127.0.0.1:6545 php
	root d:\caddy\www\public
	
}`

I am new to this kind of stuff and apologize if I am doing something obviously wrong or incorrectly.

**Comment by abmurksi** [comment]
There is a log file from caddy, what does it say?
I suspect it might have something to do with trying to passing html to the cgi interpreter
I use caddy as a reverse-proxy using Heimdall in Docker, working perfectly with the transparent directive

`domain.com {
  proxy / http://10.0.0.1:6545 {
    transparent
  }
`

**Comment by MrKitty871** [comment]
I was actually able to solve this issue with:

domain.com {
  proxy / http://10.0.0.1:6545 {
    insecure_skip_verify
    transparent
  }
}

Sorry for not updating this sooner.

**Comment by JeremyKennedy** [comment]
I was able to fix it in a slightly different way (using https), this is what worked for me:

```
domain.com {
    proxy / https://HEIMDALL_HOST_IP:HTTPS_PORT {
        insecure_skip_verify
        transparent
    }
}
```

Thanks @MrKitty871 for the tip about `insecure_skip_verify`!

**Comment by Xerrion** [comment]
I had the same issue, I managed to get fastcgi working.

`domain.dk {
  tls user@email.org
  gzip
  root /var/www/heimdall/public
  fastcgi / 127.0.0.19000 php {
    index /index.php
  }
  rewrite {
    to {path} {path}/ /index.php?{query}
  }
}`
