### ISSUE TITLE
Possible File Path Issue?

### ISSUE THREAD

**Issue by bradleyherrin** [linuxserver/Heimdall#296]
Heimdall is installed. When I navigate to the web page, I am presented with a message stating I have no pinned applications, which makes sense for a fresh install. When I click "Add an application here" I am then directed to [url]/items/create and a 404 error stating that [url]/items/create isn't found.

I poked around in the folders and cannot locate a folder named items.

**Comment by aptalca** [comment]
Are you reverse proxying?

**Comment by bradleyherrin** [comment]
No I am not.

**Comment by bradleyherrin** [comment]
I was unable to find a fix and uninstalled Heimdall.

**Comment by Jacbey** [comment]
@pappscheiben [have a look at this](https://github.com/linuxserver/Heimdall/issues/369).  I also had this issue which I resolved by enabling the htaccess for the folder.
