### ISSUE TITLE
[REQUEST] Support for LE Reverse Proxy subfolder

### ISSUE THREAD

**Issue by JTT-JustTheTip** [linuxserver/Heimdall#298]
I noticed that LE has support for subdomain reverse proxy but I cant see any kind of support for subfolder reverse proxy, this may be my stupidity. But is this in the scope to be done?

As i want to use Heimdall as my front page for my ddns

Thanks!

**Comment by benfff85** [comment]
+1 Would love to see this as well!

**Comment by JTT-JustTheTip** [comment]
Update -

Sorry haven't had a chance to get back to this thread, I worked out a solution to this a couple months ago

You can edit /[PATH TO LE CONFIG]/nginx/site-confs/default

Find 
```
location / {

}
```
And change it to
```
location / {
                include /config/nginx/proxy.conf;
                resolver 127.0.0.11 valid=30s;
                set $upstream_heimdall heimdall;
                proxy_pass https://$upstream_heimdall:443;
        }
```
This will point the root directory to heimdall as opposed to the default LE root directory, hope this helps!
