### ISSUE TITLE
Heimdall not suggesting Foundation Apps

### ISSUE THREAD

**Issue by Schuermi7** [linuxserver/Heimdall#300]
I started Heimdall as described in GitHub using Docker and Compose. After Heimdall had started, it stated, that it was working and I played around a bit. Then I tried to use a foundation app, which was not working, due to it not been suggested nor anything else. As I dug deeper in die config folder, the SupportedApps Folder was empty. I googled the problem, landing on issue #290 , where someone had the same problem. Downloading the Heimdall-Apps master ZIP did not work either even though I made sure, that the permissions were set right. It just states, that App\Jobs\ProcessApps is failing.
```heimdall    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0. 
heimdall    | [s6-init] ensuring user provided files have correct perms...exited 0. 
heimdall    | [fix-attrs.d] applying ownership & permissions fixes... 
heimdall    | [fix-attrs.d] done. 
heimdall    | [cont-init.d] executing container initialization scripts...
heimdall    | [cont-init.d] 10-adduser: executing...
heimdall    |
heimdall    | -------------------------------------
heimdall    |           _         ()
heimdall    |          | |  ___   _    __
heimdall    |          | | / __| | |  /  \
heimdall    |          | | \__ \ | | | () |
heimdall    |          |_| |___/ |_|  \__/
heimdall    |
heimdall    |
heimdall    | Brought to you by linuxserver.io
heimdall    | We gratefully accept donations at:
heimdall    | https://www.linuxserver.io/donate/
heimdall    | -------------------------------------
heimdall    | GID/UID
heimdall    | -------------------------------------
heimdall    |
heimdall    | User uid:    1001
heimdall    | User gid:    1001
heimdall    | -------------------------------------
heimdall    |
heimdall    | [cont-init.d] 10-adduser: exited 0.
heimdall    | [cont-init.d] 20-config: executing...
heimdall    | [cont-init.d] 20-config: exited 0.
heimdall    | [cont-init.d] 30-keygen: executing...
heimdall    | using keys found in /config/keys
heimdall    | [cont-init.d] 30-keygen: exited 0.
heimdall    | [cont-init.d] 50-config: executing...
heimdall    | [cont-init.d] 50-config: exited 0.
heimdall    | [cont-init.d] done.
heimdall    | [services.d] starting services
heimdall    | [services.d] done.
heimdall    | [2018-12-04 09:11:55][61] Processing: App\Jobs\ProcessApps
heimdall    | [2018-12-04 09:11:55][62] Processing: App\Jobs\ProcessApps
heimdall    | [2018-12-04 09:11:55][63] Processing: App\Jobs\ProcessApps
heimdall    | [2018-12-04 09:11:55][63] Failed:     App\Jobs\ProcessApps
```

**Comment by anoma** [comment]
Have you any advert/script/CDN busting countermeasures in place?

**Comment by Schuermi7** [comment]
we got some pretty nasty enterprise proxy going on there. 
You think this could be the problem? 
I got credentials to bypass this, but there is no way to use this within a proxy isn't there?

**Comment by anoma** [comment]
From memory autocomplete needs some external assets to work. Total guesswork but it is not impossible.

**Comment by Schuermi7** [comment]
So Autocomplete is a serverside thing?
Is there a way to give the docker container my proxy-pass so it can bypass our corporate proxy

**Comment by anoma** [comment]
I dont want to speak out of turn as I dont really know how this bit works but I believe it is server side (as in your hosted Heimdall instance ) but some assets to fully experience Heimdall as it is expected to run come from CDN.

Certainly I needed to allow access to CDN i dont normally for it to work as expected.

This is normal practice these days, I am just paranoid.

**Comment by Schuermi7** [comment]
yeah after searching a bit for any way to provide it access to the free internet, i resignated.
I only have credentials for an http/https proxy which when set as env variables are not used.

**Comment by KodeStar** [comment]
This is your issue - `heimdall    | [2018-12-04 09:11:55][63] Failed:     App\Jobs\ProcessApps` for whatever reason your instance can't grab the feed/apps from apps.heimdall.site grabbing the zip and putting it in wont fix anything if you don't load them in, which is possible, but you are better off finding out why you can't grab them through the app.

**Comment by Schuermi7** [comment]
I can‘t get it through the app, because I am behind a corporate Proxy that is blocking zip-like files. I‘ve got credentials for an http-proxy to bypass this but don‘t know how to make them available to Heimdall

**Comment by Schuermi7** [comment]
So I followed the instructions in you link, registering the apps with my instance. Now there is an autocomplete and i can change the Application Type field, but neither does it set any icons for the applications, nor is there any of the apps functionality
