### ISSUE TITLE
Site using FQDN and protocol instead of relative links in href fields.

### ISSUE THREAD

**Issue by TimPansino** [linuxserver/Heimdall#301]
All of the href links in the head portion of the site and any scripts in the body are using the Fully Qualified Domain Name with http:// or https://. This breaks some basic functionality when terminating SSL at the load balancer (in my case, Traefik). Unless I'm missing something there's no reason to be using these links instead of relative links on sites that don't serve these resources from another sub-domain or something external.

From reading other issues people have posted about reverse proxies, some people have gotten it to work by enabling FORCE_HTTPS=true or by forwarding to port 443 instead of 80. This is much more of a work around to fix a really basic issue, and also is not working for me as Traefik does not seem to like the self-signed certificate on port 443. Additionally, the site shouldn't require a work around anyway.

Example:
```
<link rel="stylesheet" href="http://heimdall.mydomain.com/css/app.css" type="text/css">
```

Should be:

```
<link rel="stylesheet" href="/css/app.css" type="text/css">
```

**Comment by penguincoder** [comment]
The app needs to support the `X-Forwarded-Proto` header. Most web frameworks honor that flag. Then Traefik could add the header in your frontend and the backend app could change all of the links.

[MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto)

**Comment by KodeStar** [comment]
PRs are welcome... the reason the links are hardcoded instead of being relative is in an attempt to get it working with subfolder RP as well as subdomain. The app can support X-Forwarded-Proto but it needs to be added to the TrustProxies middleware as detailed here - https://laravel.com/docs/5.7/requests#configuring-trusted-proxies however, this changed would be lost on update if you were using the docker. I don't use the app with any kind of reverse proxy and the "workarounds" should work so it's not a major priority for me.

**Comment by mabushey** [comment]
@TimPansino I use Traffik too and was looking to see if Heimdall supported Traefik. There are 81 forks but they all look out of date, I was hoping someone added this functionality.

**Comment by KodeStar** [comment]
In 2.2.0 I've added private network addresses to the trusted proxy list, so this should work now https://github.com/linuxserver/Heimdall/blob/master/app/Http/Middleware/TrustProxies.php#L15 . Reopen if that's not the case.

**Comment by mabushey** [comment]
Thanks @KodeStar, it's working great (Image ID: 04962ff9170d created 9 hours ago) via traefik. I get that this is not something that you needed but you did for a few us having issues. It is appreciated. :)

**Comment by moretocome** [comment]
That is great @KodeStar, thanks a lot. I run Heimdall from a Raspberry Pi. NginX handles SSL encryption in front of my apps and resources are scarce, so it is a pain to do SSL validation twice for every connection to the small machine.

FYI, the instructions for setting up [Reverse proxy](https://github.com/linuxserver/Heimdall#reverse-proxy) can be changed to:

### Reverse proxy

If you'd like to reverse proxy this app, we recommend using our letsencrypt/nginx docker image: [Letsencrypt/Nginx](https://hub.docker.com/r/linuxserver/letsencrypt/). You can either reverse proxy from the root location, or from a subdomain (subfolder method is currently not supported).
```
    # Heimdall in root
    location / {
        include                            /etc/nginx/proxy.conf;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass                         http://localhost;
    }
```
