### ISSUE TITLE
400 Bad Request after manual install

### ISSUE THREAD

**Issue by lentidas** [linuxserver/Heimdall#304]
I couldn't get Heimdall working through the Docker install (when going to the URL I was always presented with a nginx `502 Bad Gateway` error). Because of that I've decided to manually install Heimdall by downloading the zip file and extracting it to `/var/www/heimdall`. Sadly, I can't get it to work either. I always get a `400 Bad Request` error when navigating to the URL.

I'm running **Debian 9** with **Apache 2.4.5** and **PHP 7.2**.

Below are my active PHP modules (output of `php -m`):
```
[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

Apache configuration is the following:
```
ServerAdmin <<MYEMAIL>>
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

<VirtualHost *:80>

    ServerName heimdallserver.<<MYDOMAIN>>

    DocumentRoot /var/www/heimdall/public

    Options +FollowSymLinks

    <IfModule mod_rewrite.c>
        
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]

    </IfModule>

</VirtualHost>
```

I've also tried simply using the `AllowOverride All` instruction, but get the same error. The same happens when copying the totality of the `.htaccess` file to the vhost configuration.

Please let me know if I can provide any other useful information.

**Comment by xgodon** [comment]
yeah same issue :/
502 with nginx. that's a bummer.
i have 10 other services working fine.

**Comment by xgodon** [comment]
can you post your dockerfile?

**Comment by tsiewert** [comment]
I had the same problem. For me it was https:// in front of the ip (silly me). Without https and port 443 i got the 400 bad request. port 80 wasn't working at all. With https and port 443 it worked instantly.
