### ISSUE TITLE
"Public access to front" not working as intended

### ISSUE THREAD

**Issue by ruffy91** [linuxserver/Heimdall#306]
Enabling "Allow public access to front - Only enforced if a password is set." on 2.1.12 allows access to all settings for anonymous users, even changing passwords for all users and changing settings.

**Comment by nickbe** [comment]
Just saw this too. I was hoping that the user login prevents a non admin from accessing any settings, while allowing normal users access to the menues.

Also there does not seem to be any option to grant/deny access to links for users.

**Comment by KodeStar** [comment]
Have you set a password?

**Comment by KodeStar** [comment]
Each user has their own set of links

**Comment by nickbe** [comment]
Ah ok, thanks. So the admin cannot create them for each user? 
It might be a good idea if the admin could create links for each user and then prevent users
from createing / changeing links on their own.

**Comment by KodeStar** [comment]
That can be achieved by just creating a user with a password, set "Allow public access to front" and keeping the password to yourself?

**Comment by nickbe** [comment]
But then the user can not be restricted to only his/her own links. mmmh.
It would be nice to create links for each user and allow them access to those links only after logging in.
And prevent them from changing anything themselve.
So it's ALMOST like that now, but not quite.....

**Comment by mansfieldweb** [comment]
The locking out of normals changing settings just doesn't seem to work.

**Comment by Blackraz0r** [comment]
this is still an issue
these are my settings:
https://i.imgur.com/WSVP01h.jpg

when i open heimdall there seems to be no way to login also one can change all the settings including add users, apps change password ( whatever they atre useful for)

is this a bug or a feature?
