### ISSUE TITLE
Feature: Customize search provider list

### ISSUE THREAD

**Issue by alxlaxv** [linuxserver/Heimdall#307]
Hello,

I would be grateful to be able to create my own Search Provider config (Name + URL) in Heimdall to use my internal search agent instead of Google for example. 

Thanks a lo!

**Comment by magiruuvelvet** [comment]
This needs to be implemented, I have a Searx instance running at localhost under the address `search.local` and I want to add it to the dashboard.

**Comment by KodeStar** [comment]
Add it as a foundation app and implement SearchInterface .

You can see an example here: https://github.com/linuxserver/Heimdall-Apps/blob/master/NZBHydra/NZBHydra.php
