### ISSUE TITLE
Update broke heimdall

### ISSUE THREAD

**Issue by slimshizn** [linuxserver/Heimdall#309]
![image](https://user-images.githubusercontent.com/23506499/50501984-fd3bc380-0a29-11e9-9063-16d836455665.png)
![image](https://user-images.githubusercontent.com/23506499/50502007-09278580-0a2a-11e9-8c17-48c2dcecd76b.png)
Went from an update in September to the latest using docker. Changed nothing otherwise. Tag is 2.1.12-ls21

**Comment by slimshizn** [comment]
Cleared cache, purged cloudflare cache as well.

**Comment by Dev-Time** [comment]
I also have this issue, though with a fresh docker install.  Is there a version/docker tag that works?

**Comment by KodeStar** [comment]
Not a lot to go on from that screenshot, my guess though is you are reverse proxying and using https if so see if this helps https://github.com/linuxserver/Heimdall#reverse-proxy specifically the part about `FORCE_HTTPS=true`
