### ISSUE TITLE
A default app key isn't safe

### ISSUE THREAD

**Issue by iruoy** [linuxserver/Heimdall#311]
The app key is used to encrypt all Laravel managed data.
Right now it is the same for all Heimdall users. This should be generated on the first run.

**Comment by KodeStar** [comment]
Currently the only thing the app_key is used for is sessions I think.  In any case I've created a PR to fix this, but the docker also needs to be updated as well. Basically what will happen is on first access for non docker users if the .env is missing it copies the .env.example (updated to be the same as the current .env minus the appkey) and then runs php artisan key:generate, docker users it's basically the same but it's done in the docker init script

**Comment by homerr** [comment]
Link to docker pr for reference https://github.com/linuxserver/docker-heimdall/pull/30

**Comment by KodeStar** [comment]
fixed on master and will be in next release
