### ISSUE TITLE
Add option to open links in current window or new tab

### ISSUE THREAD

**Issue by KodeStar** [linuxserver/Heimdall#32]

**Comment by RichardUUU** [comment]
Right now, I get a new tab sometimes, and other times I don't, particularly when navigating to a tag page and back to the home page.

**Comment by KodeStar** [comment]
That sounds like it's working?  Tab pages should open in the same window (as you are still within Heimdall) and apps should open in a new window (as you are going away from the app)

**Comment by RichardUUU** [comment]
Ok. I've added "apps" on each tag page that take me back to my home page. The first time I click on one of these "home apps", it creates a new tab so I am now looking at the second tab. From then on, I can click on "home apps" back and forth from home page to any tag page as much as I want, and it does not create any new tabs, even if I delete the first tab and there is only one tab left.

**Comment by aptalca** [comment]
Right now, clicking on a link in Heimdall will open it in a new tab. If one goes back to Heimdall and clicks on another link, it will be opened in the same tab as the previous click.

Could there be an option to make all clicks open in a separate new tab?
I like to be able to open multiple tabs through Heimdall simultaneously, without having them open on top of each other in the same tab

Thanks

**Comment by kmlucy** [comment]
I would prefer an option to open in the same tab, but separate new tabs would be better for how I use it than the way it currently works.

**Comment by kmlucy** [comment]
For now, if anyone wants links to open in the same tab, just swap `linuxserver/heimdall` with `kmlucy/docker-heimdall`: https://github.com/kmlucy/docker-heimdall.

It's super hacky, but it does work. If you want separate new tabs, just change the sed command that changes `"heimdallapp"` to `""` to `"_blank"`.

**Comment by KodeStar** [comment]
This is now done, there is a setting that lets you select the behaviour, thanks to @ullbergm it will be available in the next build (or if you are using master you can pull the changes and manually update the app version in config/app.php to a higher number to kick of the settings seeder)
