### ISSUE TITLE
[Bug] Cannot pin or unpin when an app is tagged

### ISSUE THREAD

**Issue by pierre-le** [linuxserver/Heimdall#321]
**Issue**

When an app item is tagged, we're unable to pin or unpin it.
When trying to do so, a 404 error pops out in the inspector, with the following URL: `/tag/items/pintoggle/1/true` (where `1` is the item ID).
It works properly when the item is not tagged.

**Expected behavior**

We should be able to pin or unpin an app from the dashboard, whether it is pinned or not.

**Steps to reproduce**

Browser: Chrome 71

1. Create an item, and assign a tag to it.
2. Open the contents of the tag from the dashboard.
3. Click on the "double-arrow" icon on the right to enable the "pin/unpin" triggers.
4. Click on the pin icon on the app.

**Comment by PostPollux** [comment]
I can confirm this. I have exactly the same bug on my server.

**Comment by HoboMechanistic** [comment]
Hello, just to add to this, I've got the same issue happening on my server using: 
"build_version": "Linuxserver.io version:- 2.1.13-ls40 Build-date:- 2019-04-19T22:15:20-04:00"
 Running in Docker. Both Firefox and Chrome on Ubuntu. Using HTTP (no HTTPS).

**Issue**:
Attempting to pin an app that is tagged using the pin menu (double arrows) will not pin the item.
Attempting to pin an app that is untagged using the pin menu (double arrows) will cause all pinned applications to show on page until the page is refreshed, before showing main tag categories again.

Workaround:
Pin items when adding the application the first time.
Use Application menu to pin items in edit mode.
Right click on pin in pin menu and select open in new tab -> the new page will list the item as pinned.

**Comment by KodeStar** [comment]
Fixed in 2.2.1
