### ISSUE TITLE
Continous CPU load from php-fm processes even if not accessed

### ISSUE THREAD

**Issue by GreenTeaBalls** [linuxserver/Heimdall#322]
There are three php-fm processes which are continously running and are causing a cpu load of ~ 3-5% on my Synology DS1817+.

I've had two enhanced apps but deleted them as I suspected them to be the culprit and restarted the Docker container. That hasn't made a difference though.

Heimdall is version 2.1.13.

Any ideas what causes this behaviour and if it is avoidable? Thanks!

**Comment by KodeStar** [comment]
Have you tried looking at the docker logs to see if it gives you any clues? I'm guessing the process is the background queue worker, I don't think it should be causing a noticeable CPU load though unless it's consistently failing to process a job maybe.

**Comment by GreenTeaBalls** [comment]
The docker logs we're empty but for the standard lsio startup logging.

I found in the nginx access log that something tries to access nginx every 2 seconds causing a 500 return code:
<details>
172.17.0.1 - - [29/Jan/2019:12:37:57 +0100] "GET /get_stats/1 HTTP/1.1" 500 15939 "https://<fqdn_of_my_server>/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
172.17.0.1 - - [29/Jan/2019:12:37:59 +0100] "GET /get_stats/1 HTTP/1.1" 500 15939 "https://<fqdn_of_my_server>/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
172.17.0.1 - - [29/Jan/2019:12:38:01 +0100] "GET /get_stats/1 HTTP/1.1" 500 15939 "https://<fqdn_of_my_server>/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
</details>

When trying to open the `/get_stats/1` endpoint manually in the browser I get a webpage showing this:
![image](https://user-images.githubusercontent.com/4040549/51906214-dc1d1880-23c3-11e9-9320-07dc2b8af69a.png)

**Comment by KodeStar** [comment]
Ok, well get_stats is run on enhanced apps, whatever id 1 is the system thinks it's an enhanced app and is trying to get the details, except that the system seems to be saying id 1 doesn't exist

**Comment by XabiAlonso86** [comment]
I don't know if this would help but I was suffering this issue. I have Heimdall after traefik proxy. On traefik I got SSL configuration with cert.pem and privkey.pem. I switched cert.pem with fullchain.pem and the issue on Heimdall was solved.

**Comment by mhbates** [comment]
I just encountered this as well. Strangely, I couldn't actually disable the config/enhanced feature of Transmission, Radarr, Sonarr, or Tautulli. Toggling the enable switch wouldn't take. Removing them and re-adding (without config) seems to have fixed it.
