### ISSUE TITLE
Error when adding new App to new installation

### ISSUE THREAD

**Issue by aheinricy** [linuxserver/Heimdall#325]
I just installed Heimdall and everything is working great except I get an error when trying to add a new app.  I add the application., type, and url and save it and it gives me the following error. 

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method App\Search::storeSearchProvider()

Symfony
\Component
\Debug
\Exception
\FatalThrowableError
…
/app
/Http
/Controllers
/ItemController.php
172 

If I go back to the start page the app has been added even through I received the error.  Any idea why its giving me an error ?

**Comment by KodeStar** [comment]
I've commented it out of master and will push a new version shortly
