### ISSUE TITLE
No CSS behind reverse proxy

### ISSUE THREAD

**Issue by penguinsam** [linuxserver/Heimdall#326]
I am hosting in docker and behind reverse proxy using nginx-proxy and letsencrypt-nginx-proxy-companion, the site can launch but the UI is totally off. 

![image](https://user-images.githubusercontent.com/6859350/52192999-dfaf1480-2887-11e9-8421-7bf867870b06.png)

**Comment by KodeStar** [comment]
Not a bug, configuration error. Check out https://github.com/linuxserver/Heimdall#reverse-proxy see if any of that helps.
