### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by b0red** [linuxserver/Heimdall#328]
I like the software, but would it be possible to add a small checkbox for "active" apps, sometimes I'm running docker containers for test and it would be nice to mark an app as active and show up on the dashboard (and inactive apps not showing up)?
And some way of reorganizing the apps in the dashboard? 
Otherwise, keep up the good work.

**Comment by KodeStar** [comment]
I mean.. that's what "pinning" the apps is for... and you can drag and drop the tiles into any order you want..  The animated gif / video on the readme shows exactly this?  Or am I misunderstanding you?

**Comment by b0red** [comment]
Sorry. Totally missed it. My bad. :)

**Comment by KodeStar** [comment]
👍
