### ISSUE TITLE
Additional requirements for install

### ISSUE THREAD

**Issue by manderso7** [linuxserver/Heimdall#331]
Wanted to let you know that I needed to install php72-filter on my system. Otherwise I was getting: 
```
#4 
/usr/local/www/nginx-dist/Heimdall/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engin...
PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function Illuminate\Routing\filter_var() in /usr/local/www/nginx-dist/Heimdall/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:538
Stack trace:
#0 /usr/local/www/nginx-dist/Heimdall/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php(235): Illuminate\Routing\UrlGenerator->isValidUrl('/svg/500.svg')
#1 /usr/local/www/nginx-dist/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(148): Illuminate\Routing\UrlGenerator->asset('/svg/500.svg', NULL)
#2 /usr/local/www/nginx-dist/Heimdall/storage/framework/views/1283bbe69399bc7cccbd8ce8673868ab73cca64b.php(5): asset('/svg/500.svg')
```

You may want to update your dependencies. I installed via nginx in a freenas jail.
Cool project, is now my home page.

**Comment by KodeStar** [comment]
That's weird, I've never heard that being needed before, from a quick read it should be available in default PHP installs.

I just checked what is installed for the docker and it installs: 
`php7 php7-fileinfo php7-fpm php7-json php7-mbstring php7-openssl php7-session php7-simplexml php7-xml php7-xmlwriter php7-zlib php7-ctype php7-pdo_sqlite php7-tokenizer php7-zip`

I'll add it to the readme anyway though.
