### ISSUE TITLE
NAT loopback, LAN/WAN access

### ISSUE THREAD

**Issue by mhbates** [linuxserver/Heimdall#332]
Is there a best practice or known workaround for NAT loopback? i.e. an app's URL is its local IP. If Heimdall is exposed to WAN via reverse proxy, then apps' local IP addresses won't be accessible when connecting externally. But, unless you have NAT loopback, you can't put the external address for apps, as that would mean you can't access them from the LAN without doing various DNS tweaking.

**Comment by anoma** [comment]
Typically this is solved with split horizon DNS where you host all your apps on a a real TLD (perhaps reverse proxy or multiple subdomains) and then set your internal DNS server to resolve this domain to its internal private address. 

So yes best practice calls for `various DNS tweaking`.
