### ISSUE TITLE
Suggestion - add requirement for apache mod-rewrite to readme/faq etc. 

### ISSUE THREAD

**Issue by JasonDictos** [linuxserver/Heimdall#333]
e.g.:
```
/etc/apache2/mods-enabled# sudo ln ../mods-available/rewrite.load rewrite.load
````

^-- without that I could not get any of the redirected links to work in the portal. Didn't see it in the manual, and I'm a n00b at web dev so took longer then it should've I imagine...

Cool project though, really happy I can portalize all my various unsecured web apps with this.

**Comment by KodeStar** [comment]
I'll add a line to the apache section mentioning mod-rewrite needs to be enabled, thanks.
