### ISSUE TITLE
 Class 'null' not found (View: /var/www/localhost/heimdall/resources/views/items/form.blade.php) 

### ISSUE THREAD

**Issue by SirTerrific** [linuxserver/Heimdall#334]
Hi guys,

I'm using heimdall with the docker image on an amd64 architecture. 
Today, I meet an issue  ErrorException (E_ERROR)
Class 'null' not found (View: /var/www/localhost/heimdall/resources/views/items/form.blade.php) (View: /var/www/localhost/heimdall/resources/views/items/form.blade.php) . When I tried to add an application.

Heimdall is behind a reverse proxy nginx and I tried on another with Traefik. 
Both worked well before. 

I had that after update my image to the last one. I tried to roll back with the linuxserver/heimdall amd64-63e0d07d-ls12  and amd64-2.1.13-ls28 after wiped my config and without persistent config.

Thanks.
![Heimdall Error](https://user-images.githubusercontent.com/12296919/55341146-a6fd7700-5495-11e9-81cd-7c0215cddc4e.png)

**Comment by manikmakki** [comment]
Sorry, that was the build tagged 4980bfab-ls14.
