### ISSUE TITLE
Jupyter notebook app

### ISSUE THREAD

**Issue by daviddoji** [linuxserver/Heimdall#338]
Name: Jupyter

URL: https://jupyter.org/

License: BSD

Summary: Open source web application that allows you to create and share documents that contain live code, equations, visualizations and narrative text.

Icon Source: https://github.com/jupyter/notebook/blob/master/docs/resources/icon_512x512.svg

**Comment by dhinklexo** [comment]
Going to try and add this

**Comment by KodeStar** [comment]
App requests should be done on https://apps.heimdall.site/ more details at https://github.com/linuxserver/Heimdall-Apps/wiki
