### ISSUE TITLE
Nextcloud missing

### ISSUE THREAD

**Issue by Wdavery** [linuxserver/Heimdall#340]
I recently reinstalled Heimdall from scratch and I can't get the built it Nextcloud shortcut. It's listed on the website as supported and I know I had it as an app tile on my previous install. Something wonky with mine or can anyone else reproduce this?

**Comment by dhinklexo** [comment]
How did you install Heimdall? Are other apps working as expected?

**Comment by Wdavery** [comment]
Installed via docker. Everything is working as expected, yes.

**Comment by Wdavery** [comment]
Nextcloud has reappeared now. I manually updated the app list many times so I'm not sure what finally fixed it.

**Comment by KennyStier61** [comment]
Interestingly enough, I am having this issue on a fresh install (on Docker). Nextcloud is not an option in the menu.

Restarting the container seems to fix the issue.
