### ISSUE TITLE
Can we have more ways to add the icon?

### ISSUE THREAD

**Issue by andrewsav-datacom** [linuxserver/Heimdall#343]
Currently, as far as I can see there are two ways to add an icon:

- Use a foundation app or, if it does not exist, request one
- Upload the image from your device

Can we have a couple more please:

- Use `favicon` from the url of the site provided
- Allow to provide an arbitrary URL, e.g. <https://www.google.com/favicon.ico> with most common image formats support

**Comment by KodeStar** [comment]
Implemented in v3

**Comment by Paul-SB** [comment]
I can' t wait any longer 👍 When is the time?
