### ISSUE TITLE
No launcher showing if applicatino type is 'none'

### ISSUE THREAD

**Issue by Sebastiaan76** [linuxserver/Heimdall#344]
When creating a new 'App', if the type is set to 'None' ( i.e. no app type exists for the app i want to create ), Upon saving, it says success, but no button shows.

This means you need to assign some type of app from the dropdown in order to have something show up on the screen.

**Comment by tobbenb** [comment]
Did you enable pinned for that entry? If not, it doesn't show the new app.

**Comment by Sebastiaan76** [comment]
adding 'pinned' indeed makes it show up.
