### ISSUE TITLE
How do I unset password?

### ISSUE THREAD

**Issue by andrewsav-datacom** [linuxserver/Heimdall#345]
How to unset a password on a user?

**Comment by Aerion** [comment]
Open app.sqlite (`sqlite3 /config/www/app.sqlite`) and execute the following command 

``` sql
UPDATE users SET password=null WHERE username='yourusername'
```

**Comment by andrewsav-datacom** [comment]
I'd expect this to be an option in the UI.

**Comment by crazychatting** [comment]
also found a pretty good way from this reddit-post: https://www.reddit.com/r/selfhosted/comments/kttfg5/heimdall_remove_user_password/

it seems to be more safe to use the acces via the app-cmd from artisan :)

**Comment by Mir0ff944** [comment]
For people running Heimdall in a Docker container and cannot run `sqlite3` from inside the container, you can copy the `app.sqlite` file from the container into your host machine, update your password as shown above and copy the file back into your container.

Copy from container: (for me it is located at "/config/www/app.sqlite")
`docker cp heimdall:"/config/www/app.sqlite" "<local-path-to-file>"`

Copy back to container:
`docker cp "<local-path-to-file>" heimdall:"/config/www/app.sqlite"`

I had my container running while I did this and just had to restart it.

**Comment by GuideGlyph** [comment]
> Open app.sqlite (`sqlite3 /config/www/app.sqlite`) and execute the following command
> 
> ```sql
> UPDATE users SET password=null WHERE username='yourusername';
> ```

Did not work for me, heimdall still asking for password. So I created my own new password ( bcrypt 10 rounds https://gchq.github.io/CyberChef/#recipe=Bcrypt(10) ) and insert it instead. Work fine

**Comment by dreg35** [comment]
> > Open app.sqlite (`sqlite3 /config/www/app.sqlite`) and execute the following command
> > ```sql
> > UPDATE users SET password=null WHERE username='yourusername';
> > ```
> 
> Did not work for me, heimdall still asking for password. So I created my own new password ( bcrypt 10 rounds https://gchq.github.io/CyberChef/#recipe=Bcrypt(10) ) and insert it instead. Work fine

Would you mind describing how you went about creating a new password?
