### ISSUE TITLE
Blank Hex Color forces White Text

### ISSUE THREAD

**Issue by angdigi** [linuxserver/Heimdall#346]
Hi. I don't think this is a bug per se, but if I leave the hex color blank I get a transparent icon (which looks great IMO). However, the text color defaults to white and cannot be changed, which makes it hard to read for certain background images.

May I suggest a feature request to change the text color?

Thanks for an awesome app!

EDIT: Another way to address this is to add opacity level since the text color changes automatically depending on hex color.

**Comment by KodeStar** [comment]
This should be implemented in v3
