### ISSUE TITLE
octoprint plugin showing wrong percentage

### ISSUE THREAD

**Issue by jrucker2004** [linuxserver/Heimdall#351]
The progress percentage of the octoprint plugin appears to be off by two decimal places.  See attached image
![octoprint](https://user-images.githubusercontent.com/19860871/58278351-b213ab80-7d50-11e9-9a9a-043a13ecfa9f.png)

**Comment by KodeStar** [comment]
I'm not sure if it depends on the version of octoprint, because the api docs seem to be different to what people are saying. Not sure if they have changed something.
