### ISSUE TITLE
[Feature Request] Grouping of Applications

### ISSUE THREAD

**Issue by vxzero** [linuxserver/Heimdall#352]
I'd like to have the ability to group items and make them stay next to each other on the dash board.

For example, I have 3 Proxmox servers and would like to have them all right next to each other on the dashboard, on the bottom row, no matter how many other applications I add. Even if the row above is not full, I'd like to have these three stay where I left them or grouped so they move as one.

**Comment by KodeStar** [comment]
Create a tag and stick them in that? Otherwise there are no immediate plans for something like this.

**Comment by schittli** [comment]
To have a concept similar to [homer](https://github.com/bastienwirtz/homer) would be great 😄
