### ISSUE TITLE
User management is not working correctly

### ISSUE THREAD

**Issue by nickbe** [linuxserver/Heimdall#353]
As of now it is not clear to me how the user management works or is supposed to work.
I configured the system, so that I have to login. After creating a user I logged in as a user.
But there's no logout that would throw me back to the start screen. I can easiy delete the user even if I'm not admin which does not make any sense and I can switch between admin and user without having to re-login.

**Comment by nickbe** [comment]
Ok, it seems that as soon as you click on change user there is some kind of logout going on.
But how can I prevent users from modifying links?

**Comment by ThisIsQasim** [comment]
Same question here. How do I logout?

**Comment by djismgaming** [comment]
This seems like a good idea. Having a logout option may improve the security of the dashboard if accessed from a shared/work computer.

**Comment by KodeStar** [comment]
Implemented in v3

**Comment by nickbe** [comment]
is there any news here. Or did I miss v3 altogether somewhere different from GitHUb?

**Comment by supermuesli** [comment]
I still don't see any logout button anywhere.
