### ISSUE TITLE
Error while submitting a new item

### ISSUE THREAD

**Issue by Zciwobukaj** [linuxserver/Heimdall#354]
**Description :** 
while submitting a new item with particular kind of url (http://myalias , which is different from http://myalias.com), I obtain this error : 

ErrorException thrown with message "Class 'null' not found (View: /var/www/localhost/heimdall/resources/views/items/form.blade.php) (View: /var/www/localhost/heimdall/resources/views/items/form.blade.php)"

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalThrowableError in /var/www/localhost/heimdall/app/Item.php:162

**How to reproduce :** 
1. Open Heimdall webpage
2. submit a new item with url such as described above
3. while clicking on the save button, you are redirected to the exception page

**Environment :** 
Heimdall : 2.1.13 hosted by Docker
Web browser : Firefox 67.0 (64 bits)

**Comment by KodeStar** [comment]
Seems ok on current version 2.2.0, reopen if not the case
