### ISSUE TITLE
Error while displaying the search bar

### ISSUE THREAD

**Issue by Zciwobukaj** [linuxserver/Heimdall#360]
**Description**
While opening Heimdall on firefox, the search bar appears weird (see screenshot 1)
Opening the same page on Edge shows better result (see screenshot 2)
This problem wasn't here with the v2.1.13

![Screenshot 1](https://user-images.githubusercontent.com/35924688/59299642-72741b80-8c8d-11e9-8ec0-f63e44485048.png)
![Screenshot 2](https://user-images.githubusercontent.com/35924688/59299644-72741b80-8c8d-11e9-87ec-446617af37f0.png)

**Environment**
Heimdall version : 2.2.0 hosted on docker
Web browser : Edge 42.17134.1.0 / Firefox 67.0.1 (64 bits)

**Comment by Zciwobukaj** [comment]
I just clean the cache and this solves the problem. Should we keep this issue alive ?

**Comment by KodeStar** [comment]
Keep it alive for a few days, I should have put a version number on the css file to bust cache but didn't. In Chrome Ctrl + F5 (win) or Command + r (mac) should do the trick

**Comment by KodeStar** [comment]
Fixed in 2.2.1
