### ISSUE TITLE
No autocomplete when trying to add an app.

### ISSUE THREAD

**Issue by Dipskcit** [linuxserver/Heimdall#361]
When trying to add an app there is no autocomplete for foundation apps, the update apps list seemingly does nothing.

I'm running everything on Unraid if that makes any difference.

**Comment by KodeStar** [comment]
Is this still an issue? There was an issue with the apps site a couple of days ago but this should have been fixed.

**Comment by Dipskcit** [comment]
Seems like that was the issue, it now autocompletes.
