### ISSUE TITLE
still problems with domain name

### ISSUE THREAD

**Issue by daviddoji** [linuxserver/Heimdall#362]
Although I replicate the config using by @mabushey on this issue:
https://github.com/linuxserver/Heimdall/issues/350

can't get it work, obtaining a nice "404 page not found". With my old configuration, it kind-of work, but without the let's encript certificate and exposing the port explicitely.

@KodeStar said that reopen if still on failure.

**Comment by c-rilaun** [comment]
Your issue won't be solve, neither today neither another day, if you don't show us what your conf look like. 
Second thing is, nether replicate something without understanding it.

You have to understand what you are doing, what you are typing (or pasting) if you want it to work. 

It wasn't a pain in the a*s to get Heimdall work. I just make a heimdall conf with server_name referring to sub.domain.com and a location / with a try files (i used the nginx proxy conf suggested in the readme.md, simply as that). I also add a A entry to resolve sub.domain.fr.
Then, now it work with 80 (non ssl), i run a certbot --nginx and everything goes automatic. Heimdall now accesible via 443 on sub.domain.com.

Reach back to us with details and we'll try to help you.
