### ISSUE TITLE
Pinned tags not showing on homepage

### ISSUE THREAD

**Issue by vrelk** [linuxserver/Heimdall#367]
DB: SQLite
PHP: PHP 7.2.19-0ubuntu0.18.04.1
Heimdall version: 2.2.2

I am now running the latest version of heimdall. I still have an old 1.4 version on another server, so I am used to the tags function. I am trying to have a tag show up on the homepage, but it won't show up. I have set it to pinned, and also saved it as unpinned, then re-pinned it, but it won't show up on the homepage. The only time I have gotten it to show up temporary is when I also add the homepage tag to one of its subitems, then going to the pinned items page on the homepage and pinning/unpinning the sub-item. The tag will show up on the homepage after pinning/unpinning the subitem for that tag, but only for that page load. This happens with the tag empty, and 1-2 subitems. If I reload the page, the tag is gone again. I have replicated this issue with both firefox and chrome.

Let me try and list replication steps as that glob of text is a bit globby.

1: create tag (for this example lets call it "nodes"), and select pinned
2: create item "node 1" with the tag of nodes. At this point the tag "nodes" does not show up on the homepage, or in the pinned items list.
3: add the tag "Home dashboard" to "node 1" (leaving the "nodes" tag)
4: go to pinnable items on the homepage and pin "node 1". Immediately the tag "nodes" and the item "node 1" appear.
5: refresh the page. now only "node 1" is showing.
6: unpin "node 1" from the pinned items list. Immediately the tag "nodes" is showing again.
7: refresh the page. The tag "nodes" is now gone.

**Comment by KodeStar** [comment]
Looks like a bug, I'll look into it

**Comment by KodeStar** [comment]
Should be fixed in current release, reopen if that's not the case
