### ISSUE TITLE
Updating (non-docker) instructions?

### ISSUE THREAD

**Issue by lausvi** [linuxserver/Heimdall#368]
Hi,
could you add to the installation instructions how to update a pre-existing installation to a newer version? I have tried putting in a new install and then copying over my old app/public/backgrounds and -icons and database/app.sqlite, but that usually just breaks the installation.

**Comment by KodeStar** [comment]
I think you just need to overwrite the files, personally I use the docker on my server and clone the repo for building and testing, so never had to try updating in any other way than re-pulling the docker or doing a `git pull`.
