### ISSUE TITLE
2.2.2 gives 404 when clicking "Add an application here"

### ISSUE THREAD

**Issue by Jacbey** [linuxserver/Heimdall#369]
Fresh install on 2.2.2 and whenever I click on "Add an application here" and it sends me to domain.com/item/create

Any ideas why this is happening?

![image](https://user-images.githubusercontent.com/16065051/59969658-1d68bd00-954b-11e9-86ba-8a754976bca4.png)

**Comment by Jacbey** [comment]
The issue here was that htaccess needs to be enabled in the vhost configuration.  I fixed mine by adding this

`<Directory /var/www/html/Heimdall>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>`

to the bottom of my vhost configuration file.

**Comment by crkinard** [comment]
What if you are not use Apache? Using Nginx here.
