### ISSUE TITLE
Feature Request: App Reverse Proxy

### ISSUE THREAD

**Issue by yaroto98** [linuxserver/Heimdall#374]
So, this product wasn't what I was expecting. Yes it's a pretty dashboard/frontpage, but it doesn't do what I, and I think many people, need. I like that there's authentication build in, that's important, because what I would like this product able to do is reverse proxy local apps.

There are many apps and services I have running that I don't want to expose to the internet. I don't want to poke 30 holes in my firewall, one for each service, and I don't want to create an nginx config and dns entry for each service for a reverse proxy solution.

What would be nice, is if I can come to this dashboard, expose it to the internet, then on the backend, it does the reverse proxy for me automatically based on the url I give it. If I give it a localhost:port address (or 192.168.*.*:port) it finds the service and when I click on it, it's brought up. A full page iframe would make this possible, but I'm sure there are better ways of doing it.

**Comment by yaroto98** [comment]
Ignore this feature request. The correct answer is a VPN combined with Heimdall.

**Comment by aptalca** [comment]
Or, you can set up an actual reverse proxy, with auth and all, and use those urls in heimdall. Most of us use it that way. Heimdall itself is also reverse proxied in my case.

https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/

If you use cloudflare as your dns provider, you only need one `A` record for the main domain, and one `*` `CNAME` that covers all subdomains. You only expose one port (443) and access everything through the letsencrypt/nginx reverse proxy. It comes with preset proxy confs where most of them can be enabled by a simple conf file rename.
