### ISSUE TITLE
[Feature Request] Default Ports when adding

### ISSUE THREAD

**Issue by some1thatNeedsHelp** [linuxserver/Heimdall#378]
hey

i like to see about using default ports when adding to Heimdall

lik when i add a new app

i type: `Application Name`: `Radarr` it then has a a drop down i can click - which changes `Application Type`

it would be epic to see it put something like `URL: localhost:7878` as thats default

**Comment by tobbenb** [comment]
Localhost is not default. This depends on how you deployed Heimdall.

**Comment by Dovry** [comment]
@tobbenb localhost is being used as an example here.

**Comment by ianhopes** [comment]
Not sure it would be worth the effort as I cant code for crap but maybe a similar option to what I think the OP is suggesting (a list default ports of supported applications) would be the ability to poll a docker host to retrieve a list of the containers on the host. 
I was just looking but couldnt get the api to work to retrieve info but looking at docker ps -a as an example you get most of the info you would need to scrape. For each item drop anything before the '/' and after the ':'. There is a list of applications. For each one you could then make an array of available ports active on the host by only taking those preceded with '0.0.0.0:' then add the port to the array. 
I would like most of the image names would match to valid applications in Heimdall pretty well, maybe iterate over the name and check dropping the last character each time then if nothing go the other way. 
The scraping could then display the docker name, image details and suggested application and ports available.
More specific details are available with the inspect function, massive amounts of info in JSON format i think. Or maybe interfacing with the docker.sock
I just thought I would add my two cents for what two cents in worth these days (nothing) and I think it is a good idea even if I dont think it is needed for my usage pattern.
