### ISSUE TITLE
Heimdall requesting resources on wrong protocol

### ISSUE THREAD

**Issue by andrewsav-datacom** [linuxserver/Heimdall#380]
This is something that got broken recently `linuxserver/heimdall:2.1.13-ls40` did not have this issue and `heimdall:2.2.2-ls49` has it.

The issues is that if you run your docker container behind reverse proxy instead of using the same protocol for requesting resources as browser used for requesting the page, heimdall may use something else.

For example, request to heimdall on https from browser arrives to the reverse proxy where ssl is terminated. Reverse proxy forwards https request to the container. The page that is getting served back to the browser contains http links for the resources, where as it should have https. because this is the protocol the browser used for requesting the page.

Here is an example of what it leads to:

![heimdall01](https://user-images.githubusercontent.com/27190911/61008936-253ab500-a3c5-11e9-81a6-b7fee8da3ee5.png)

Browser blocks the mixed content and the page does not load properly.

Generally speaking when loading site assets most modern web applications use relative paths for this exact reason, otherwise it's a pain hosting it inside a container behind a reverse proxy that terminates ssl, which is increasingly common these days.

**Comment by andrewsav-datacom** [comment]
Note: `FORCE_HTTPS=true` works to fix this, but it was recently removed from `readme.md`.

**Comment by KodeStar** [comment]
Remove FORCE_HTTPS=true it shouldn't be needed any more, what's your RP conf look like, my guess the issue is with how it's set up. Quite a bit of the recent release was to get RP working properly without workarounds.

**Comment by andrewsav-datacom** [comment]
This is a fresh install no specific configuration. I only added `FORCE_HTTPS=true` because it does not work without.

What is RP?

**Comment by andrewsav-datacom** [comment]
Never mind, I think you are right, I end up getting:

```text
X-Forwarded-Port: 80
X-Forwarded-Proto: http
```

Which is wrong. Since there are a few http(s) entities that the request bounces through on it's way to the kubernetes pod some of them is clearly mis-configured. I'll investigate and fix the problem on my end.
