### ISSUE TITLE
Instructions and Debian Install

### ISSUE THREAD

**Issue by Revenger** [linuxserver/Heimdall#381]
The instructons are pretty vauge and need redoing.
I run a Virtualmin server on Debian 9.9 and cant seem to get it to install.

For one what are the exact extra dependancies we need in a way we can get them from the repo?
Something like OpenSSL PHP Extension we cant apt yum etc search and install.
A example apt cache search that string brings up,

```
apt-cache search OpenSSL PHP Extension
libapache2-mod-php7.0 - server-side, HTML-embedded scripting language (Apache 2 module)
libphp7.0-embed - HTML-embedded scripting language (Embedded SAPI library)
php7.0-cgi - server-side, HTML-embedded scripting language (CGI binary)
php7.0-cli - command-line interpreter for the PHP scripting language
php7.0-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary)
php7.0-phpdbg - server-side, HTML-embedded scripting language (PHPDBG binary)
```

So the dependancies section needs to be more refined and fleshed out and have the package names needed.

For the key generate on Debian I got this error.

```
php artisan key:generate
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/server/public_html/vendor/zendframework/zend-diactoros/src/functions/marshal_uri_from_sapi.php on line 83
```

When trying to go to the url; its installed on I get,

`Forbidden
You don't have permission to access / on this server.`

The install guide as mentioned needs redoing and things need polishing on documentation as it currently is I have no idea how to get this thing working under a Virtualmin virtual server on Debian 9.9.

**Comment by KodeStar** [comment]
Your install might go better if you weren't using an EOL version of PHP, `7.1.3` is the minimum requirement according to the laravel docs. https://laravel.com/docs/5.7/installation
I do need to update the composer.json to reflect this though, I guess it started out on laravel 5.5 which had 7.0.0 as the requirement.

**Comment by KodeStar** [comment]
I mean it is on the first line of the [Readme - Installing section](https://github.com/linuxserver/Heimdall#installing) - `Apart from the Laravel dependencies, namely PHP >= 7.1.3`
