### ISSUE TITLE
App name inconsistencies

### ISSUE THREAD

**Issue by HendrikF** [linuxserver/Heimdall#382]
It seems that the app name, which is displayed in the "Add application" dialog is taken from the class name.
That does not make sense in my opinion, because apps already have a name defined in their app.json.

I noticed this when adding the "ArchiveTeam Warrior" App. In the Application Type select box it is listed as "ArchiveTeamWarrior", although I named it "ArchiveTeam Warrior" in app.json (Notice the space).
This also leads to small icons, because the long name without spaces doesn't get wrapped by the browser, and the logo is scaled down.

The app name should be taken from app.json and displayed like that in the select box and as the default app name in the preview.

**Comment by KodeStar** [comment]
`AVM Fritzbox`, `Cloud CMD`, `Cockpit CMS` and several others disagree with your analysis `ArchiveTeam Warrior` is an odd one though

**Comment by HendrikF** [comment]
All of your examples confirm my observation actually.

`AdGuard Home` is the only app, whose spacing seems to be correct, and it is an enhanced app. So maybe it has something to do with that.
All other examples you mentioned do not have spaces, although they have some in their app.json.

For screenshot purposes, I changed the size of the select box.

![Screenshot 2019-07-19 14-04-27](https://user-images.githubusercontent.com/6961660/61533845-42f3c400-aa2e-11e9-9774-b0abe62de92e.png)
![Screenshot 2019-07-19 14-00-53](https://user-images.githubusercontent.com/6961660/61533846-438c5a80-aa2e-11e9-8c59-0bc0256746f4.png)
![Screenshot 2019-07-19 14-00-30](https://user-images.githubusercontent.com/6961660/61533847-438c5a80-aa2e-11e9-9bda-a16d506233f2.png)

Version: 2.2.2
Docker image: linuxserver/heimdall:latest
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Client OS: Ubuntu 18.04.2 LTS

**Comment by KodeStar** [comment]
I believe this is fixed, reopen if not
