### ISSUE TITLE
[Feature Request] Reverse proxy user authentication using http header

### ISSUE THREAD

**Issue by jeslinmx** [linuxserver/Heimdall#385]
Currently, if Heimdall is loaded through a request from a reverse proxy, it checks REMOTE_USER to identify the user (if authenticated through HTTP basic auth) and log the user into the corresponding user within Heimdall (#275). However, since REMOTE_USER is set through environment variables, as far as I know, this functionality only works if the reverse proxy proxies the request over fastcgi, as opposed to HTTP. In many docker setups, however, typically there is a public facing reverse proxy container (nginx-proxy, caddy, traefik, etc.) which then passes requests over HTTP to other containers, which means that this current approach doesn't work (I think? Please correct me if I'm wrong)

Request: add an option to enable proxy authentication over HTTP, which then causes Heimdall to look for a configurable HTTP header in the request for the user authenticated by the reverse proxy. This is safe as long as the server/container instance is only accessible behind the reverse proxy.

Kanboard has this implemented and I think they explain it way better than I can in their documentation: https://docs.kanboard.org/en/latest/admin_guide/reverse_proxy_authentication.html

**Comment by MorphedOverride** [comment]
Grafana's auth.proxy is another example of this.

You set a header to listen for (Grafana's default being X-WEBAUTH-USER) that contains the username provided by some means (usually an SSO provider of some description). 

When a user then visits heimdall, it will automatically login based on the username in the set header.
