### ISSUE TITLE
[Feature Request]  Implement with fail2ban

### ISSUE THREAD

**Issue by thepenguinthatwants** [linuxserver/Heimdall#386]
Heimdall works very well but sometimes I feel unsecured as it shows the username by default and someone might be able to crack the password by bruteforce.

It would be nice if it can detect the possible ip's of the people that tries to login and gives the possibility to implement it with fail2ban.

**Comment by j0nnymoe** [comment]
Put it behind our reverse proxy container which includes fail2ban.

**Comment by thepenguinthatwants** [comment]
I am using traefik with your linuxserver/heimdall:latest image.

Can you elaborate more about the reverse proxy container?

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-letsencrypt

**Comment by thepenguinthatwants** [comment]
I have fail2ban locally installed and using traefik. I guess using that image is a bit overload. Even if I use your image how can I implement fail2ban to undestand failed heimdall logins?

I tried to figure out how to get heimdall to show up failed login tries. But when I use docker-compose logs there are no info about failed logins.

**Comment by cybermcm** [comment]
Can this be reopened? I want to implement fail2ban but there is no log to identify failed logins.
@thepenguinthatwants: Did you ever manage to implement a solution?

**Comment by KodeStar** [comment]
v3 you will be able to select whether to show usernames or not, the nginx log will probably have failed logins in it

**Comment by cybermcm** [comment]
@KodeStar: I checked the nginx logs but there is no pattern for failed logins or at least I can't identify them
