### ISSUE TITLE
"cURL error 28" when running "php artisan key:generate"

### ISSUE THREAD

**Issue by Skywt2003** [linuxserver/Heimdall#387]
When i tried to install Heimdall without Docker, following the instructions, i typed:

```
php artisan key:generate
```

but i got this error:

```
In CurlFactory.php line 185:

  cURL error 28: Connection timed out after 15001 milliseconds (see http://cu
  rl.haxx.se/libcurl/c/libcurl-errors.html)

```

Centos 7 x86-64 with PHP 7.3.6, nginx...

**Comment by zedascouves** [comment]
I'm getting the same error. How did you fixed it? Thanks!

**Comment by djmixman** [comment]
Any information on how this was fixed?
