### ISSUE TITLE
Incorrect tag URL

### ISSUE THREAD

**Issue by saepachi** [linuxserver/Heimdall#390]
Fresh install today, added a tag and it lists /tag/apps as the url.  If I try to follow, I get a URL not found error.  However, if I manually go to /tag**s**/apps I can access.

**Comment by j0nnymoe** [comment]
Just tested this in our docker container and not experiencing the same issue.

Please provide more information to help us hunt down this bug.

**Comment by saepachi** [comment]
Cloned to a system running Mint Linux (Ubuntu) and Apache 2. I’m not using docker, instead I created a symlink to the public folder in my Heimdall directory and configured Apache appropriately. Everything else seems to be working fine, just the tags writing the URL without the “s” though the actual path seems to be with the “s”.

Sent from my iPhone
________________________________
