### ISSUE TITLE
Ombi Issue

### ISSUE THREAD

**Issue by dmdusn** [linuxserver/Heimdall#396]
Have Heimdall setup and everything is working great. The problem with Ombi is that when I click the link or hover over Ombi it has two IP address it is going to, the Heimdall address with 8080, and the Ombi address with 3579. 192.168.1.158:808/192.168.1.158:3579. Not sure if it is something that I am doing wrong.

**Comment by j0nnymoe** [comment]
Are you including `http://` in the link when creating the button?

**Comment by dmdusn** [comment]
> Are you including `http://` in the link when creating the button?

Yup, that was it. No idea how I let that slip. Operator error for sure.
