### ISSUE TITLE
UNC Path

### ISSUE THREAD

**Issue by kikaida** [linuxserver/Heimdall#403]
Is there anyway to add an UNC path for an application URL? I tried adding in the URL field as file://///server/test/v108/ It works in the a browser directly but when I click on the app in the dashboard it does nothing.

**Comment by kikaida** [comment]
Was this removed because it was already implemented or not needed?

**Comment by keriati** [comment]
As far as I can tell UNC path support is a browser thing not a Heimdall issue. Closing as there is also no progress.
