### ISSUE TITLE
Installation With Docker

### ISSUE THREAD

**Issue by arond1** [linuxserver/Heimdall#406]
Hello there,

sorry but I can't find the COMPLETE instructions to launch your app using docker. In the link in the README (https://hub.docker.com/r/linuxserver/heimdall/) they give us a command to run your app in a container but they never mention how to obtain and modify the config folder who is required for the container.

Thanks in advance for your answer.

**Comment by KodeStar** [comment]
No idea what you are on about. You specify the config folder here: ` -v /path/to/appdata/config:/config` Where `/path/to/appdata/config` is the path to where you want the config folder to live.

**Comment by aptalca** [comment]
Yeah, just select any path on your host like `/home/arond1/heimdall` and replace `/path/to/data` with your location. That's it.

As long as you have docker installed, the docker create command will create the container and then `docker start heimdall` will start it.
