### ISSUE TITLE
Enhancement: Global link set

### ISSUE THREAD

**Issue by Aphris-Karu** [linuxserver/Heimdall#407]
I was hoping to use this as a start page with a default set of tiles for all users. But it seems that each user has their own space and will have to manually enter the links. This is a real problem when there are over 20 items on the network that the user would need links to.

Would be nice if the admin could enter a set of tiles and pin some or all of them. Then each user added to the system would automatically get the pinned tiles and be able to pin or unpin the ones they need.

**Comment by KodeStar** [comment]
This should be available in v3, though the exact details of how this is going to work are still a bit in the air.
