### ISSUE TITLE
Tags inside tags? 

### ISSUE THREAD

**Issue by jnavarrodev** [linuxserver/Heimdall#408]
Is it possible to create a tag inside another tag to have better management of a lot of elements?

**Comment by tgc12** [comment]
That easy.
I'm doing it with apps link to /tag/yourtag

**Comment by jnavarrodev** [comment]
> That easy.
> I'm doing it with apps link to /tag/yourtag

Could you explain it a bit more? I can not (on do not know) how to do that. 
In an app, in tags, I only can choose between existing tags, cannot write anything else.

**Comment by tgc12** [comment]
Of course.
 -  First you create the desired tag inside tags, assign it to the default page and leave it unpinned.
 -  Then you can create an app with the name of the tag or something you what and leave the app empty and put into the url `/tag/yourtag/`

**Comment by jnavarrodev** [comment]
Ok, I made it...but it it possible to have apps inside that tag? I cannot found the way to do it...

**Comment by tgc12** [comment]
The app is only a redirect to the tag, just assign the apps to the tag and pin them.

**Comment by jnavarrodev** [comment]
I cannot achieve that. Probably I am doing something wrong. But it should not be so difficult....

**Comment by tgc12** [comment]
Is a matter of pinning the right stuff.

![Screenshot_20191105-211525](https://user-images.githubusercontent.com/7664285/68243203-51341300-0012-11ea-993c-eba9efc76d7b.png)
![Screenshot_20191105-211556](https://user-images.githubusercontent.com/7664285/68243224-58f3b780-0012-11ea-803c-c02f66591db9.png)
![Screenshot_20191105-211618](https://user-images.githubusercontent.com/7664285/68243238-5ee99880-0012-11ea-981c-6cbddbdbcb7e.png)
![Screenshot_20191105-211713](https://user-images.githubusercontent.com/7664285/68243252-6446e300-0012-11ea-9fa5-1cc187075f84.png)
![Screenshot_20191105-211810](https://user-images.githubusercontent.com/7664285/68243264-690b9700-0012-11ea-9e58-49af9f644e7d.png)
![Screenshot_20191105-211932](https://user-images.githubusercontent.com/7664285/68243284-758fef80-0012-11ea-8e3d-90d193b9a4e7.png)

## Home page

![Screenshot_20191105-211823](https://user-images.githubusercontent.com/7664285/68243274-6e68e180-0012-11ea-9526-f5fc24c1ddea.png)

## Tag1

![Screenshot_20191105-212525](https://user-images.githubusercontent.com/7664285/68243559-0961bb80-0013-11ea-9296-fd235c04ccdb.png)

## Tag2

![Screenshot_20191105-212548](https://user-images.githubusercontent.com/7664285/68243585-19799b00-0013-11ea-994e-a53d8c2a71a8.png)

**Comment by jnavarrodev** [comment]
Thanks, I was missing one (or two) steps!
