### ISSUE TITLE
Supported Apps Not Showing in Application Name

### ISSUE THREAD

**Issue by CrashyBang** [linuxserver/Heimdall#409]
So I am trying to add a couple of apps (Plex, and CalibreWeb) which are listed as a "foundation apps" on the main site but are not showing in the application dropdown?

This is not a major issue in the sense that I can add them manually, but I just wanted to list it as a bug in the event it had not been uncaught.

I have attached a screenshot of what I mean below (Plex not showing):

![Capture](https://user-images.githubusercontent.com/2978850/68081614-b7376380-fe75-11e9-8392-a653ca544458.PNG)

**Comment by KodeStar** [comment]
You need to click on the "update apps list" button on the page before?
