### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by Admin9705** [linuxserver/Heimdall#41]
This is our Ansible YML for Heimdall at https://plexguide.com... but it doesn't load, nor ever obtain IP.  

Location: https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/blob/Version-5/ansible/roles/heimdall/tasks/main.yml

**Comment by Admin9705** [comment]
this is what portainer displays: standard_init_linux.go:195: exec user process caused "exec format error"

**Comment by KodeStar** [comment]
It's just been tested on a Pi and it seems to work fine, according to Sparklyballs you are using the wrong arch

**Comment by Admin9705** [comment]
ya, i don't know.  using a standard xeon processor.  did some research and looks like an ARM error.  Is that the right pull?

lsioarmhf/heimdall:latest

**Comment by sparklyballs** [comment]
lsioarmhf is for armhf arch

you need linuxserver/heimdall

**Comment by Admin9705** [comment]
ah stupid me :D

**Comment by Admin9705** [comment]
Ok tried it, download and got an IP Address: portainer reported - 
0 with exit code

and nothing happens from there :D

**Comment by KodeStar** [comment]
Lol, you spelled it wrong, It's Heimdall, not HemiDall
