### ISSUE TITLE
Ubuntu 18.04 Install

### ISSUE THREAD

**Issue by FanyangMengDev** [linuxserver/Heimdall#410]
I have to say sorry that I just have my first Ubuntu for not such long time, and I really cannot find one FULL INSTRUCTIONS about installing this on Ubuntu 18.04.
This page : https://github.com/linuxserver/Heimdall-Apps/wiki even not contains a full guide.
Could you please write a more perfect install instruction? I think not just me meet this problem, see the problem at this url: https://www.reddit.com/r/selfhosted/comments/ag1wzl/installing_heimdall_in_ubuntu_1804_lts/
I do not know that whether this will work well cause it is not from your offical instruction.
Docker.... emmmm.. I really do not like docker at the same time.
Anyway, please write a page which is better fot us.....
Thanks.
P.S.: The reason I am afraid of try to install it without full instruction is because that my server also host many other of my websites, I am afraid that maybe some step will cause the server down...........

**Comment by c-rilaun** [comment]
First of all, hello. It work better if you are polite.

There is no issue with Heimdall installation instruction : 

> ** Installation is as simple as cloning the repository somewhere, or downloading and extracting the zip/tar and pointing your httpd document root to the /public folder then creating the .env file and generating an encryption key (this is all taken care of for you with the docker). **

You can have Ubuntu, Debian or CentOS, a webserver is a webserver, php is php. 

You are on Github, a place for developper, if you can't get your hands dirty by testing things, you are not welcome here. **This is not Google mate.**

So, what is your issue ?

**Comment by FanyangMengDev** [comment]
I am wondering that where I am not polite?
I just report a suggestion to you, then you said that I am not polite, are you kidding me?
I have to say that many self-hosted applictaions such as Restya, Gitea, Bitwarden, all of them have a perfect instructions about how to install all the necessary kits. I am not saying that yours is not as good as theirs, but making it more perfect is better for the user, right?
You can see the reddit post that I sent you before. It’s not that no one has mentioned this probelm. I just put these suggestion in the issue and tried to clarify the problem. How dare you said that I am not polite, it is really rude and we are not enemies, OK?
I report this issue only because the server I am using has so much applications now, and if without perfect instruction I am just afraid of breaking some APP. You do not need to say that this is github, not google, and I am not welcome here if I do not wanna get my hands dirty by testing things, do you think I don't know that? Just wanna make you realize maybe there is something more can be done to make it better, OK?
I am just an ordinary user, it will be better if you are polite and more patient.
Thanks anyway.

**Comment by FanyangMengDev** [comment]
And I will follow your advice by purchasing a brand new server to test the installation by myself. No need to offer any help if you are not willing to. I hope you can just be more patient next time.

**Comment by FanyangMengDev** [comment]
From the server I use, it just keep alerting me this 
`Warning: require(): open_basedir restriction in effect. File(/hdd2/www/websites/heimdall.fanyangmeng.com/vendor/autoload.php) is not within the allowed path(s): (/hdd2/www/websites/heimdall.fanyangmeng.com/public/:/tmp/:/proc/) in /hdd2/www/websites/heimdall.fanyangmeng.com/public/index.php on line 24

Warning: require(/hdd2/www/websites/heimdall.fanyangmeng.com/vendor/autoload.php): failed to open stream: Operation not permitted in /hdd2/www/websites/heimdall.fanyangmeng.com/public/index.php on line 24

Fatal error: require(): Failed opening required '/hdd2/www/websites/heimdall.fanyangmeng.com/public/../vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /hdd2/www/websites/heimdall.fanyangmeng.com/public/index.php on line 24`

Could you please tell me how to fix it? I just do all the things as the instruction said. Set the root to /public , custom the .env file, and generated an encrypt key. All I have got is this.
