### ISSUE TITLE
How to make example.com/userselect the only page available for users who are not logged in?

### ISSUE THREAD

**Issue by MnM001** [linuxserver/Heimdall#411]
Hi,

Will appreciate if someone can assist me.
For a number of reasons (including the cookie error) I want to me /userselect the landing page and the only page available to users who are not logged in.
I have looked around but I have no idea how to achieve this.

Add example.com/userselect in my nginx redirection doesnt work very well - white page with a password box. Cant select users, etc

Will appreciate any assistance.

Thanks.

**Comment by KodeStar** [comment]
I think it should show the user select page by default if all your users have passwords and public page is turned off for all users
