### ISSUE TITLE
Feature Request: sessions, multi-user, user profiles

### ISSUE THREAD

**Issue by cocoonkid** [linuxserver/Heimdall#415]
Feature Request: sessions, multi-user, user profiles

I would love to contribute but PHP is not my strength so I reasoned I might as well at least submit the feature request, in the hope the ghosts of our machines give us the almighty code to make that happen.

Making it possible to set up it up for multiple users through an auth module would make Heimdall so golden!

**Comment by KodeStar** [comment]
I'm not sure if I understand what you mean? You can already add extra users?

**Comment by cocoonkid** [comment]
oh. I stand corrected. My sincere apology. I must have really overseen that.
Closing this issue :-)
