### ISSUE TITLE
Feature Request: Hide navigation buttons on public facing homepage

### ISSUE THREAD

**Issue by Rogue136198** [linuxserver/Heimdall#418]
It would be nice if we could hide the admin buttons that are in the bottom right of the homepage. My users never need these links and I access an admin tag so they would be visible there for me. Basically less clutter for the end-user.

**Comment by KodeStar** [comment]
Not a bad idea, I'll look into it.

**Comment by KodeStar** [comment]
Implemented in v3 of the app
