### ISSUE TITLE
Add password field support to config items

### ISSUE THREAD

**Issue by KodeStar** [linuxserver/Heimdall#42]
Encrypt the password in password field config items and display passwords in a password field, add an eye icon so you can see the password

**Comment by anoma** [comment]
Subset of https://github.com/linuxserver/Heimdall/issues/48

**Comment by RichardUUU** [comment]
This works with NZBGet: http://192.168.1.1:6789/nzbget:tegbzn6789/
It would be nice if they all did.

**Comment by KodeStar** [comment]
@RichardUUU this is something different, it was a reminder for me, in any case though, anything with basic auth should work with http://user:pass@192.168.1.1:6789/
