### ISSUE TITLE
Dashboard live stats not working with qBittorrent 4.2.0

### ISSUE THREAD

**Issue by lldsolitude** [linuxserver/Heimdall#420]
Enhanced qBittorrent worked fine with qBittorrent 4.1.x in LSIO docker container, but after recently upgrading to 4.2.0, the feature stopped working. Config test returns `Failed: Please make sure your URL is correct and that there is a trailing slash`.

**Comment by somedevreally** [comment]
qbit did some major changes to API, hope this issue is fixed soon

**Comment by somedevreally** [comment]
any update?

**Comment by jeremysherriff** [comment]
I've already created an issue over on the Heimdall-Apps github page, and submitted a PR that addresses it. Just waiting on a dev to merge the PR. See linuxserver/Heimdall-Apps#147

**Comment by Tuumke** [comment]
Over at Organizr they have fixed it somehow? They add a choice if you need V1 or V2 api? 
Commit: https://github.com/causefx/Organizr/commit/a3db9a3bb0a3b888a76ff1d9cb1125c265f33b99
qBit documentation: https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#get-api-version

I asked on discord if some could take a loook at linuxserver/Heimdall-Apps#147

**Comment by juligreen** [comment]
If you use the development image (linuxserver/heimdall:development) the issue is fixed already

**Comment by lldsolitude** [comment]
This issue has been resolved by [linuxserver/Heimdall-Apps#147](https://github.com/linuxserver/Heimdall-Apps/pull/147), closing.
