### ISSUE TITLE
Feature Request: Allow using the colour picker to set a background colour

### ISSUE THREAD

**Issue by bunwayenterprises** [linuxserver/Heimdall#422]
At the moment, if you wish to have a solid colour for the background you have to create and upload a wallpaper image of just that colour.

It would be great to be able to set the background to a static colour by using the colour picker (as you do when creating an app box), thereby avoiding having to upload a wallpaper image altogether.

**Comment by KodeStar** [comment]
I've added it to the V3 list of things to do, thanks. The plan is to allow either a solid colour or a simple gradient.
