### ISSUE TITLE
running behind https reverse proxy?

### ISSUE THREAD

**Issue by sigmonsays** [linuxserver/Heimdall#423]
heimdall is generating http links when I want it to generate https links. 

I setup heimdall using docker container in kubernetes. I used https://hub.docker.com/r/linuxserver/heimdall/. The container is listening on port 80 (http). 

After initializing the application data, I edited www/.env and changed APP_URL to be "APP_URL=https://start.example.org" and restarted. Links are still incorrectly being generated. 

it is my understanding that heimdall uses laravel and it seems to have a lot of confusion surrounding generating HTTPS urls when run with a reverse proxy. 

Is there anything else to get heimdall to work in this environment?

**Comment by sk33z3r** [comment]
This is related to https://github.com/linuxserver/docker-heimdall/issues/61. I'm having all sorts of issues based around the SSL configs that are making the app only work as a homepage for links. Pretty much all other features are broken because of whatever this internal SSL confusion is.

**Comment by aptalca** [comment]
If you're reverse proxying with ssl, use port 443 with ssl as the proxy address

**Comment by Tokugero** [comment]
I'm running heimdall in k8s with Ambassador ingress with no special configurations on the application, my links all work fine. I may not be understanding your issues but maybe I can help share my details with you.

In my .env I have it defaulted to `APP_URL=http://localhost`, I have my ingress pointed at the :80 service bound to the heimdall pod, and for my links I just specify "http" or "https" in the protocol section to specify which protocol I want:

![image](https://user-images.githubusercontent.com/7573214/90822527-77991580-e2e9-11ea-85a1-b937f513b434.png)

If I wanted my ingress to point to the https port on heimdall within the cluster I would do the same when specifying my mapping, but this feature is being phased out in favor of ingress and that's a whole other topic.

**Comment by Tokugero** [comment]
I have this deployed in k8s, I did not edit my www/.env, it's still set to APP_URL=http://localhost

My 443 ports are forwarded to my SSL managed ingress
My ingress points to my port 80 heimdall service
My heimdall service is listening on port 80

If you expect your links to be HTTPS, make sure that your input https as part of the whole URL. (e.g. `https://mycool.domain.com` as opposed to `mycool.domain.com`)

**Comment by travelg** [comment]
any fix for this? I have still issue running nginx ssl proxy to heimdall http port. Images and css are broken. 
Thank you for reply.

**Comment by gsmlg** [comment]
This needs support `x-forwarded-proto` header.

**Comment by wikijm** [comment]
Hi everyone,

As @gsmlg  proposed, I tried to define an NGINX location block as listed below:
    location /dashboard/ {
        root /dashboard;
        proxy_pass http://172.19.0.2/; #172.19.0.2 is the Heimdell IP inside the network nginxproxymanager_default (NGINX Proxy Manager)
        proxy_set_header     Host $http_host;
        proxy_set_header     X-Real-IP $remote_addr;
        proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
        # Requis pour indiquer à iceScrum son port externe
        proxy_set_header     X-Forwarded-Port 80;
    }

I also defined APP_URL=http://domain.tld/dashboard.

My goal is to access to Heimdall like this ([XXXX] are networks and *XXXXX* are containers):
http://domain.tld/dashboard/ --> [bridge] --> *nginxproxymanager* --> [nginxproxymanager_default] --> *heimdall*

Where [XXXX] are networks and *XXXXX* are containers.

Here is the result:
![image](https://user-images.githubusercontent.com/10724809/116921285-11c0a400-ac54-11eb-97e5-0b25df860f97.png)

**Comment by michaelkrieger** [comment]
Look at (configdir)/www/.env and change APP_URL from http://localhost/ to https://host.domain/path and restart the app.  It will then work.

**Comment by jfl1616** [comment]
I'd like to share this message if anyone is still experiencing issues with blocked HTTPS requests. Specifically, my CSS requests have been blocked. After modifying (configdir)/www/.env and changing APP_URL from http://localhost/ to https://domain.tld, the issue did not resolve. Here is the alternative solution from another [issue.](https://github.com/linuxserver/Heimdall/issues/315)

Modify /config/www/.env:

This issue is resolved by adding the below last line.

`FORCE_HTTPS=true`

**Comment by gesquive** [comment]
@jfl1616 THIS WORKED, this should be in documentation somewhere.

**Comment by cpatscheider** [comment]
i stumpled upon this as well. This definitly needs to be documented. Took me several hours to get running.

**Comment by zakria03** [comment]
> I'd like to share this message if anyone is still experiencing issues with blocked HTTPS requests. Specifically, my CSS requests have been blocked. After modifying (configdir)/www/.env and changing APP_URL from http://localhost/ to https://domain.tld, the issue did not resolve. Here is the alternative solution from another [issue.](https://github.com/linuxserver/Heimdall/issues/315)
> 
> Modify /config/www/.env:
> 
> This issue is resolved by adding the below last line.
> 
> `FORCE_HTTPS=true`

You just saved my marriage tonight...

**Comment by vincejv** [comment]
For anyone still having issues with nginx subfolder, like enhanced apps and sorting the tiles not working, updated @bamhm182 config to
```nginx
location /heimdall {
  return 301 $scheme://$host/heimdall/;
}

location ^~ /heimdall/ {
  # Proxy config
  proxy_pass http://heimdall.docker.internal:80;
  include snippets/authelia-authrequest.conf;
  include snippets/proxy.conf;

  rewrite /heimdall/(.*) /$1 break;
  rewrite ^/heimdall$ /heimdall/ permanent;
}
```

and on `.env` should have a trailing slash **/**
```env
APP_URL=https://my.website/heimdall/
```
