### ISSUE TITLE
🌟 Feature req: Display URL at the bottom of an item

### ISSUE THREAD

**Issue by thibmaek** [linuxserver/Heimdall#427]
When running multiple instances of Heimdall (e.g one for LAN and one for WAN) it would be useful to see the URL you are going to visit at the bottom of an item:

![image](https://user-images.githubusercontent.com/6213695/72108726-84599200-3334-11ea-80f1-9d07277367cc.png)

So here, maybe in light blue or gray pointing to http://localhost:8000 just to get a visual indication of where you are going and that you are not visiting the WAN address instead of the LAN one.

**Comment by KodeStar** [comment]
Hover over the item and look at where the link is going to? In V3 tags work differently which should make it easier, but I'll have a look at adding more information as well, I just need to be wary that I don't make the tiles too crowded looking
