### ISSUE TITLE
Illegal string offset 'name'

### ISSUE THREAD

**Issue by calvinbui** [linuxserver/Heimdall#433]
Getting the PrettyPageHandler when trying to edit my NZBGet and qBittorrent items when the integration fields are filled in.

```
ErrorException (E_ERROR)
Illegal string offset 'name' (View: /config/www/SupportedApps/Nzbget/config.blade.php) (View: /config/www/SupportedApps/Nzbget/config.blade.php) (View: /config/www/SupportedApps/Nzbget/config.blade.php)
```

![image](https://user-images.githubusercontent.com/3604363/73073080-a9402e80-3f0a-11ea-9e60-8b10fbec3329.png)

**Comment by LilTrublMakr** [comment]
Same thing for Deluge when trying to edit it.

**Comment by LeoShivas** [comment]
Same thing for Transmission when trying to edit it

**Comment by TheBekker** [comment]
Same for Deluge on my brand new Unraid docker instance.
Just added Unraid and then Deluge, and then got the error when trying to edit.

**Comment by KodeStar** [comment]
Does this happen on the master version as well? If you are using docker try the development tag

**Comment by TheBekker** [comment]
Just tried to pull the development one instead, same error.
Noticed that it only happens if i fill in a password for the enhanced features.

**Comment by bonesoul** [comment]
same issue here.
and even more enchanced features doesnt work.

**Comment by shaohao** [comment]
I just figured out how to solev this issue:
the 'password' input in config.blade.php file of all enhanced apps should be changed like:
```
{!! Form::password('config[password]', array('value' => (isset($item) ? $item->getconfig()->password : null), 'placeholder'......
```
Just move the 'value' field of password into the options array.
'Cause I found larav webfx's formbuild function 'password' only takes two arguments, one is the name, the other is the options.
BUT.... I found $item->getconfig()->password always retun "". Where does heimdall store the password to?

**Comment by shaohao** [comment]
Yeah. I got it. The final solution:
```
/var/www/localhost/heimdall/vendor/laravelcollective/html/src/FormBuilder.php:334 change it like below:
public function password($name, $value, $options= [])
{
    return $this->input('password', $name, $value, &options);
}
```
And all of the config.blade.php of apps can keep untouched.
I guess heimdall pull the lastest laravel fx which had changed the usage of password input.

**Comment by shaohao** [comment]
just submitted a PR

**Comment by farnots** [comment]
This is working great thanks @shaohao ! (it's an `$options` in case someone want to make the change)

**Comment by lclc98** [comment]
I think this [commit](https://github.com/linuxserver/Heimdall-Apps/commit/622dc4c8d329467cc37c2d794961c314ce767fbb) is what introduced the error. Looking at the PR to fix it, I think it causes a new bug with default value not being set after refreshing(haven't had a chance to test) as `skipValueTypes` prevents value being set for password types.

**Comment by fpellicciotti** [comment]
I'm getting the same thing for qBittorrent
