### ISSUE TITLE
Use LDAP as a user store

### ISSUE THREAD

**Issue by aroberts** [linuxserver/Heimdall#436]
Currently, even though reverse proxy authentication is supported, a parallel user base must be maintained in Heimdall - it can't use the upstream user base that controls auth.

It would be great to have support for user administration in a separate data store, and I would imagine that LDAP is the most common system of record for this problem.

**Comment by KodeStar** [comment]
V3 of heimdall will have reverse proxy baked in using the lsio letsencrypt container as a base, you will be able to use your Heimdall users to control which reverse proxied apps users have access to

**Comment by aroberts** [comment]
Just to confirm, your plans for v3 do not include installing heimdall as a service with an existing (external) reverse proxy, and an existing (also external) user store?

**Comment by lhanson** [comment]
I'm also confused; is the intention that users are expected to use Heimdall as their central user administration system? If so, I don't think it's reasonable to expect that I rearrange my network to accommodate an HTML dashboard.

**Comment by KodeStar** [comment]
The intention is you *can* use heimdall as your central user administration system, no one is forcing you to though. As for an external proxy and an external user store, it will probably work, it's just not something we are focusing on, but as ever PR's will be welcome.

**Comment by wachtell** [comment]
Hi @KodeStar - is it possible to link Heimdall to LDAP?
