### ISSUE TITLE
URL validation

### ISSUE THREAD

**Issue by knudsvik** [linuxserver/Heimdall#437]
When putting in an ip-adress:port in the url field in new entries, a url validation would be welcome, i.e adding http:// or https:// in front of the domain name or ip address automatically. Not a big deal when you know about it, but creates frustration for new users (me yesterday).

**Comment by KodeStar** [comment]
Url validation was removed because people were complaining about non standard urls not being allowed. You are right that it should mention a missing prefix, but it's not quite that simple as http:// and https:// aren't the only valid prefixes
