### ISSUE TITLE
Cpanel not compatible with Heimdall

### ISSUE THREAD

**Issue by TUISTERa** [linuxserver/Heimdall#441]
Hello, I try to deploy Heimdall to cpanel, but symlink is disabled as security feature. Please advise what change i need to make to have it working without symlink. 

![image](https://user-images.githubusercontent.com/1550326/74089773-55f2e200-4aad-11ea-8bc3-8f0fd4cea001.png)

**Comment by KodeStar** [comment]
You could try creating a storage folder in public and copying the contents from /storage/app/public, no idea if that will work though, it wasn't designed with something like that in mind.

**Comment by TUISTERa** [comment]
The problem is not the missing folder. It is that Heimdall is still trying to make symlink. Any idea how what to change in code so i can skip the symlink and hardcode the folder in public?

**Comment by TUISTERa** [comment]
Actually it is working .
