### ISSUE TITLE
419 "Sorry, your session has expired" when submitting new app

### ISSUE THREAD

**Issue by mortenmoulder** [linuxserver/Heimdall#443]
Not exactly sure why this is happening. I've not changed the .env file at all, except added `FORCE_HTTPS=false`.

I can see that the session file gets created in `storage/framework/sessions/`, and they do contain the correct CSRF token, but I still get the error.

I was worried about wrong dates, but they're the same. I did set `SESSION_LIFETIME` to 999999 just to see, but that didn't work either.

I did run `chown www-data:www-data Heimdall/ -R` to make sure all permissions were correct.

Not sure what else I can do now, but it's kind of annoying :(

**Comment by mheppner** [comment]
I'm getting the same error. Also chown'ed to the correct permissions and verified the session files are being created. The CSRF tokens also match.

Using PHP 7.3.15.

**Comment by brandon-dacrib** [comment]
me 3, the thing I will note is that I am fronting heimdall by traefik which is handling ssl termination

**Comment by daledali** [comment]
Samw here

**Comment by yamlCase** [comment]
i also am getting the 419 error.  This and another 419 issue have not been responded to by devs.  Is there something we can add to help troubleshoot?

**Comment by KodeStar** [comment]
This may be resolved in 2.3.0, if not create a new issue if you can reliably recreate the issue so I can try and figure it out.
