### ISSUE TITLE
Can't edit NZBGet after adding it

### ISSUE THREAD

**Issue by ratnose** [linuxserver/Heimdall#447]
Describe the bug

To Reproduce

    Go to Items config
    Click on Edit for nzbget
    See error

Expected behavior
I expected to get to the edit page of the chosen item.

Desktop (please complete the following information):

    OS: Debian 10.1
    Browser Firefox 71 and 72, Safari 13.0.4
    Version Latest via hib.docker.com and Linuxserver.io

**Comment by tobbenb** [comment]
It might be a good idea to mention what the error is also. If we can't reproduce the error, we don't see the error message.
