### ISSUE TITLE
How to order items on the dashboard?

### ISSUE THREAD

**Issue by olvll** [linuxserver/Heimdall#448]
I'm trying Heimdall. I like the looks of it. Stupid question perhaps but I couldn't find out how to order items on the dashboard. I would expect to be able to do it from the "Application list". Am I missing something? Thank you.

**Comment by dbeley** [comment]
Click on the first item in the "taskbar" (the icon with two arrows), you can reorder the apps from there.

**Comment by olvll** [comment]
Thank you dbeley! So indeed I was missing something, it's even easier than I expected.

**Comment by paxmobilepi** [comment]
I find the Backup / Restore function is genious, but have a great issue: deleting the sites ono by one takes a lot of time, especially when you're on a relatively slow ping connection so when I have to delete a number of Sites from the list it takes too long compared by the restore by backup file speed. Is there a way to delete the whole list in one hit ?
