### ISSUE TITLE
Add option to add custom search engine

### ISSUE THREAD

**Issue by jessedezwart** [linuxserver/Heimdall#449]
Since everyone uses the omnibox or other browser build-in search box, I think it would be more useful to add a custom search option so you can use the search box for your in-house applications.

I will take a look at it myself when I have the time.

**Comment by KodeStar** [comment]
I'm looking at making it easier to add custom search in the new version

**Comment by Pimmetje** [comment]
@KodeStar could you link any info about this into this ticket because i am unable to find info about it.

**Comment by cybermcm** [comment]
Probably this wiki link?
https://github.com/linuxserver/Heimdall-Apps/wiki/Creating-search-providers
It would be great to add a custom search engine via web interface. I use an self-hosted search engine which I won't add to the repository here
