### ISSUE TITLE
Support NGINX Auth Request

### ISSUE THREAD

**Issue by kmlucy** [linuxserver/Heimdall#45]
Can Heimdall support NGINX's Auth Request module? Or if not, could support be added?

https://github.com/causefx/Organizr/wiki/Authentication-%7C-Server-Based
https://nginx.org/en/docs/http/ngx_http_auth_request_module.html

**Comment by aptalca** [comment]
Heimdall itself is just the web app. You can set your web server to utilize http auth. In that case, the directions in that Organizr wiki also apply here.

If you mean http auth in docker, you're in the wrong repo ;-) In that case, you can make a request for the docker, but using letsencrypt/nginx image to reverse proxy and adding http auth there is the better option

**Comment by kmlucy** [comment]
I didn't realize there was no authentication associated, so this isn't actually relevant. If you do end up adding an authentication module, it would be a nice feature though.
