### ISSUE TITLE
Increase the maximum file upload limit by default.

### ISSUE THREAD

**Issue by AriaanBruinsma** [linuxserver/Heimdall#451]
I think the maximum file upload limit should be >2MB by default, since most desktop sizes are also >1080p.

I myself run with 4K and I can't change the wallpaper because of this cap. I've changed it to 8MB, to give it some headroom, but 2MB is just too low for this day & age.

**Comment by KodeStar** [comment]
Heimdall doesn't impose an upload limit, it is determined by the PHP settings on your system. If you are using the docker make the request at https://github.com/linuxserver/docker-heimdall
