### ISSUE TITLE
SupportedApps 

### ISSUE THREAD

**Issue by JarboU** [linuxserver/Heimdall#453]
https://apps.heimdall.site/list   Not Found!

**Comment by shaohao** [comment]
You should find a proper way to access Internet.

**Comment by JarboU** [comment]
google is ok。Application list is none，Heimdall-Apps-master.zip to /path/www/SupportedApps，still none

**Comment by shaohao** [comment]
I guess there is something wrong with you dns of apps.heimdall.site.
Try  below if you use docker run
--add-host=apps.heimdall.site:78.157.210.66

**Comment by JarboU** [comment]
solved it。You are good man
