### ISSUE TITLE
Excessive drive IO usage

### ISSUE THREAD

**Issue by BrightCandle** [linuxserver/Heimdall#456]
Heimdall seems to constantly hit on the disk every few seconds and utilises 1% of the drive  IO constantly. This seems a little excessive when the page isn't opened by anyone at all. Updates should not be happening this rapidly. It is on my machine by far the biggest idle processes, that is pretty bad especially compared to sonarr or radarr with large libraries. IOTop shows its processes "php-fp: pool www" 's being the processes that are utilising the disk.

In the space of a couple of minutes it will have written at least half a megabyte, but in lots of tiny writes.

Any chance we could tone this down a bit or at least make it configurable what the rate of update is?

**Comment by keriati** [comment]
Should be resolved with: https://github.com/linuxserver/Heimdall/pull/1059
