### ISSUE TITLE
Show uploaded icon before saving

### ISSUE THREAD

**Issue by anoma** [linuxserver/Heimdall#46]
Currently when selecting a custom icon the `upload a file` dialogue shows no progress notifications and the GUI does not show the uploaded image until after you have saved.

It would be better if the icon was shown after it was uploaded and prior to committing the save

**Comment by justrynahelp** [comment]
I'm using 2.1.12, installed on unraid via Community Apps, and this is not working – the preview doesn't work for an unsaved image, only for the colour.
