### ISSUE TITLE
Application Type is missing

### ISSUE THREAD

**Issue by mylovesaber** [linuxserver/Heimdall#461]
When I first used the docker version of heimdall, I found that when I click on the Application Type option in the creation interface, there are various preset program options in the list that appears. After a few months, I tried to use it on other machines and found that Application Type only displays "none". Does a specific version of heimdall have a list of preset programs and other versions do not? I tried the latest and development tags, they only show "none"

**Comment by goku-son** [comment]
1+ application type none under docker

**Comment by goku-son** [comment]
Any status on this? Any additional information I could share to help isolate this issue? Thanks in advance.

**Comment by KodeStar** [comment]
If you are missing them try clicking the update apps button, also make sure your container can contact the outside world
