### ISSUE TITLE
Fontawesome unicode not displaying

### ISSUE THREAD

**Issue by newhinton** [linuxserver/Heimdall#465]
In the alert-box, which is displayed when adding an item or no item is set, no icon is shown. Instead, the unicode representation of the icon is shown as a small square box. 

Heimdall Version 2.2.2 
Firefox 75.0
Chromium 80.0.3987.163

(On chromium, f00c is a flag to the right, and f00d a flag to the right)

**Comment by KodeStar** [comment]
Should be fixed in 2.3.0
