### ISSUE TITLE
Default Close dialogue button

### ISSUE THREAD

**Issue by anoma** [linuxserver/Heimdall#47]
It is perhaps a bit unintuitive that the location typically occupied by the  close `X` icon is often occupied by other functions

For example

![Add not close](https://i.imgur.com/fDKj7fu.jpg)

Consideration should be given to a more traditional layout allowing for users to back out all the way to the homescreen by pressing a similarly located close dialogue as many times as needed.

**Comment by KodeStar** [comment]
I could put a cancel button next to it

**Comment by anoma** [comment]
Sounds good to me. If the top right icon is always there and is always cancel I think it would be instantly intuitive to all users.
