### ISSUE TITLE
installation error with php7.4

### ISSUE THREAD

**Issue by muralikodali** [linuxserver/Heimdall#470]
while installing, issuing command as suggested  - php artisan key:generate giving the below error: 

In ArrayInput.php line 135:

  Trying to access array offset on value of type int

**Comment by AntaeusNar** [comment]
Seconding this issue.  Trying to install php7.3 to see if that downgrade allows a work around.

**Comment by notfixingit3** [comment]
Note you can just comment out line 135 and 136 in ArrayInput.php and it will work (tested on Ubuntu 20.04 with php 7.4)

**Comment by dpantel** [comment]
Fixed upstream: https://github.com/symfony/symfony/pull/32806.

Here is the change: https://github.com/symfony/symfony/commit/3f431860c6992540d984f461b8dfa6ad19289ca2

**Comment by geneb** [comment]
Are there any plans to actually fix this issue? It's present in the 2.2.2 release, and there's not been a release since.

tnx.

**Comment by gerald-b** [comment]
+1

The change from @dpantel worked but on a fresh install it is not great to hack the source.

Is this fixed or not? There are many merges maybe related to this issue.

I will try the master and report.

**Comment by jacklocke** [comment]
+1

**Comment by KodeStar** [comment]
Fixed in 2.3.0
