### ISSUE TITLE
No Style behind reverse Proxy

### ISSUE THREAD

**Issue by Blackraz0r** [linuxserver/Heimdall#471]
I use apache as an RP in this scenario

i use the latest docker immage
```
sudo docker run -d \
  --name=Heimdall \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Berlin \
  -p 8060:80 \
  -p 8061:443 \
  -v /mnt/DS1512_docker/volumes/Heimdall/config:/config \
  --restart always \
  linuxserver/heimdall
```

this is my rp configuration:

```
<IfModule mod_ssl.c>
<VirtualHost subdomain.domain.tld:443>
ServerAdmin name@domain.com
ServerName subdomain.domain.tld
ProxyPreserveHost  On
RequestHeader set X-Forwarded-Proto "https" 
ProxyPass / https://10.220.2.40:8061
ProxyPassReverse / https://10.220.2.40:8061

SSLCertificateFile /etc/letsencrypt/live/subdomain.domain.tld/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/subdomain.domain.tld/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLProxyEngine on
SSLProxyVerify none 
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off
</VirtualHost>
</IfModule>
```

this is what heimdall looks right now:
(iu have only one app activated for testing, my vcenter
https://i.imgur.com/M9Mo55V.jpg

can one tell me the exact settings i need to modify or add to the reverse proxy file to actualle make heimdall display something else than plain text?

**Comment by Mpercy-Git** [comment]
Same issue with NGINX, I too am using the docker container.

**Comment by mattycourtney** [comment]
@Mpercy-Git it works great for me behind nginx. My config is below:
```location / {
   # proxy config
    client_body_buffer_size 128k;

    #Timeout if the real server is dead
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    # Advanced Proxy Config
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;

    # TLS 1.3 early data
    proxy_set_header Early-Data $ssl_early_data;

    # Basic Proxy Config
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    #proxy_cookie_path / "/; HTTPOnly; Secure"; # enable at your own risk, may break certain apps
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 32 4k;
    proxy_headers_hash_bucket_size 128;
    proxy_headers_hash_max_size 1024;

    # Heimdall config
    resolver 127.0.0.11 valid=30s;
    set $upstream_app heimdall;
    set $upstream_port 443;
    set $upstream_proto https;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}
```

**Comment by j0nnymoe** [comment]
We provide working configs for reverse proxy with our letsencrypt container:
https://github.com/linuxserver/reverse-proxy-confs/blob/master/heimdall.subdomain.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/master/heimdall.subfolder.conf.sample

**Comment by Mpercy-Git** [comment]
To be clear I'm running Heimdall 2.2.2 using the linuxserver/heimdall and I have a separate nginx container reverse proxying. The base URL seems to be incorrect as the subfolder seems to get stripped from all the asset urls. If I manually edit the HTML in the browser and put the subfolder back in everything starts working. See below for my proxying nginx conf.

`    location /start/ {
      
      auth_basic           "Restricted";
      auth_basic_user_file /etc/nginx/.htpasswd;

      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_pass http://192.168.1.109:8001/;`

**Comment by mattycourtney** [comment]
Try putting `rewrite /start(.*) $1 break;` in your location block.

**Comment by Mpercy-Git** [comment]
> Try putting `rewrite /start(.*) $1 break;` in your location block.

Unfortunately doesn't make any difference.

**Comment by Blackraz0r** [comment]
thenk you for all the help, but the problem is still not resolved on apache reverse proxy. any idea?

**Comment by Elegant996** [comment]
Same issue with Caddy. The `master` branch and version 2.2.2 produce the same results.

```
:2015 {
  root * /var/www/html/public
  encode gzip
  php_fastcgi unix//run/php-fpm/php-fpm.sock
  file_server
  log stdout
  handle_errors stderr
}
```

**Comment by jpoggi** [comment]
Hi @Blackraz0r ,

I'm using heimdall behind apache2 reverse proxy and everything is working, fine, here is my config:
`<VirtualHost *:80>
        Define SERVER_NAME heimdall.domain.org
        ServerName ${SERVER_NAME}

        RewriteEngine On
        RewriteCond %{SERVER_NAME} =${SERVER_NAME}
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

        CustomLog ${APACHE_LOG_DIR}/${SERVER_NAME}_access.log combined
        ErrorLog ${APACHE_LOG_DIR}/${SERVER_NAME}_error.log
</VirtualHost>

<VirtualHost *:443>
        ProxyRequests Off
        ProxyPreserveHost On

        ServerName ${SERVER_NAME}
        SSLProxyEngine On
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off

        ProxyPass / https://localhost:84/
        ProxyPassReverse / http://localhost:84/

        #Gestion du HTTPS depuis le reverse proxy
        RequestHeader set X-Forwarded-Proto "https"

        SSLEngine On
        SSLCertificateFile fullchain.pem
        SSLCertificateKeyFile privkey.pem

        CustomLog ${APACHE_LOG_DIR}/${SERVER_NAME}_access.log combined
        ErrorLog ${APACHE_LOG_DIR}/${SERVER_NAME}_error.log
</VirtualHost>`

I'm also using docker as well.

**Comment by Blackraz0r** [comment]
@jpoggi thank you for your help!

unfortunately the issue is still the same:/

![6I7ppy1 1](https://user-images.githubusercontent.com/26622216/82577443-4a728500-9b8b-11ea-98f1-7744eda3e5f9.jpg)

**Comment by Blackraz0r** [comment]
i think if i  could just use the plain http connection for the reverse proxy i didnt had to hassle with ssl. i do this in all the other services ^^

**Comment by Blackraz0r** [comment]
also i get THIS:
![NQikrh6 1](https://user-images.githubusercontent.com/26622216/82578756-2152f400-9b8d-11ea-9739-971b67ec394e.jpg)
when open on of the links.

so i think i have to tell heimdall somehow that its not internal lan anymore but it is external domain now ? how or where do i do that?

**Comment by jpoggi** [comment]
The last error DNS lookup failure is pretty strange.

It look like your reverse can't contact the container in the backend.

For the module I've got the same loaded:

```
access_compat.load  auth_basic.load  authz_core.load  autoindex.conf  deflate.conf  dir.load     headers.load  mpm_prefork.conf  negotiation.load  proxy.load           reqtimeout.load  setenvif.load       ssl.conf     status.load
alias.conf          authn_core.load  authz_host.load  autoindex.load  deflate.load  env.load     mime.conf     mpm_prefork.load  proxy.conf        proxy_wstunnel.load  rewrite.load     slotmem_shm.load    ssl.load
alias.load          authn_file.load  authz_user.load  dav.load        dir.conf      filter.load  mime.load     negotiation.conf  proxy_http.load   reqtimeout.conf      setenvif.conf    socache_shmcb.load  status.conf
```
Can you check your apache logs ?

Add this to your vhost configuration maybe first:

```
CustomLog ${APACHE_LOG_DIR}/${SERVER_NAME}_access.log combined
ErrorLog ${APACHE_LOG_DIR}/${SERVER_NAME}_error.log
```

**Comment by Blackraz0r** [comment]
my heimdall container is in a separate docker host, wich is a ubuntu vm. wich also hosts all my other containers. like nextcloud, organizr, jdownloader and so on. all of them are working fine via apache reverse proxy.

the reverseproxy itself is a ubuntuvm with webmin. i like to edit the files via clicky interface.

this is my errorlog:
```[Thu May 21 18:17:41.323861 2020] [proxy:error] [pid 12219:tid 139841272076032] [client 176.198.182.97:62106] AH00898: DNS lookup failure for: 10.220.2.40:8061css returned by /css/app.css, referer: https://links.domain.tld/
[Thu May 21 18:17:41.550190 2020] [proxy:error] [pid 12219:tid 139841173972736] [client 176.198.182.97:62165] AH00898: DNS lookup failure for: 10.220.2.40:8061js returned by /js/app.js, referer: https://links.domain.tld/
[Thu May 21 18:17:41.550907 2020] [proxy:error] [pid 12219:tid 139841288861440] [client 176.198.182.97:62105] AH00898: DNS lookup failure for: 10.220.2.40:8061js returned by /js/jquery-3.3.1.min.js, referer: https://links.domain.tld/
[Thu May 21 18:17:41.551376 2020] [proxy:error] [pid 12291:tid 139841314039552] [client 176.198.182.97:62065] AH00898: DNS lookup failure for: 10.220.2.40:8061js returned by /js/fontawesome.js, referer: https://links.domain.tld/
[Thu May 21 18:17:41.719107 2020] [proxy:error] [pid 12219:tid 139841148794624] [client 176.198.182.97:62165] AH00898: DNS lookup failure for: 10.220.2.40:8061js returned by /js/jquery-3.3.1.min.js, referer: https://links.domain.tld/
[Thu May 21 18:17:41.871790 2020] [proxy:error] [pid 12291:tid 139841140401920] [client 176.198.182.97:62097] AH00898: DNS lookup failure for: 10.220.2.40:8061js returned by /js/jquery-ui.min.js, referer: https://links.domain.tld/
[Thu May 21 18:17:42.167933 2020] [proxy:error] [pid 12219:tid 139841140401920] [client 176.198.182.97:62105] AH00898: DNS lookup failure for: 10.220.2.40:8061js returned by /js/jquery-ui.min.js, referer: https://links.domain.tld/
[Thu May 21 18:17:42.228847 2020] [proxy:error] [pid 12219:tid 139841297254144] [client 176.198.182.97:62106] AH00898: DNS lookup failure for: 10.220.2.40:8061storage returned by /storage/icons/vmwarevcenter.png, referer: https://links.domain.tld/
[Thu May 21 18:17:42.235823 2020] [proxy:error] [pid 12291:tid 139841132009216] [client 176.198.182.97:62065] AH00898: DNS lookup failure for: 10.220.2.40:8061js returned by /js/app.js, referer: https://links.domain.tld/
[Thu May 21 18:17:42.609285 2020] [proxy:error] [pid 12219:tid 139841123616512] [client 176.198.182.97:62106] AH00898: DNS lookup failure for: 10.220.2.40:8061android-icon-192x192.png returned by /android-icon-192x192.png
[Thu May 21 18:17:42.688510 2020] [proxy:error] [pid 12291:tid 139841123616512] [client 176.198.182.97:62097] AH00898: DNS lookup failure for: 10.220.2.40:8061favicon-16x16.png returned by /favicon-16x16.png
[Thu May 21 18:17:54.201953 2020] [proxy:error] [pid 12219:tid 139841064867584] [client 176.198.182.97:62065] AH00898: DNS lookup failure for: 10.220.2.40:8061items returned by /items, referer: https://links.domain.tld/
[Thu May 21 18:17:54.291089 2020] [proxy:error] [pid 12219:tid 139841056474880] [client 176.198.182.97:62065] AH00898: DNS lookup failure for: 10.220.2.40:8061favicon.ico returned by /favicon.ico```

this is my accesslog:
```176.198.182.97 - - [21/May/2020:18:17:40 +0000] "GET / HTTP/1.1" 200 6420 "https://links.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:40 +0000] "GET /css/app.css?v=2 HTTP/1.1" 502 678 "https://links.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:41 +0000] "GET /js/app.js?v=4 HTTP/1.1" 502 1237 "https://links.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:41 +0000] "GET /js/jquery-3.3.1.min.js HTTP/1.1" 502 1237 "https://links.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:41 +0000] "GET /js/fontawesome.js HTTP/1.1" 502 1237 "https://links.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:41 +0000] "GET /js/jquery-3.3.1.min.js HTTP/1.1" 502 677 "https://links.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:41 +0000] "GET /js/jquery-ui.min.js HTTP/1.1" 502 1253 "https://links.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:42 +0000] "GET /js/jquery-ui.min.js HTTP/1.1" 502 677 "https://links.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:41 +0000] "GET /storage/icons/vmwarevcenter.png HTTP/1.1" 502 682 "https://links.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:42 +0000] "GET /js/app.js?v=4 HTTP/1.1" 502 677 "https://links.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:42 +0000] "GET /android-icon-192x192.png HTTP/1.1" 502 699 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:42 +0000] "GET /favicon-16x16.png HTTP/1.1" 502 692 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:54 +0000] "GET /items HTTP/1.1" 502 1240 "https://links.domain.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
176.198.182.97 - - [21/May/2020:18:17:54 +0000] "GET /favicon.ico HTTP/1.1" 502 686 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"
```

also to answer your other question. i can access heimdall  via local ip without any problems. works fine for private ranges.

**Comment by jpoggi** [comment]
I'm quite sure there is just a typo problem on your vhost.

Try adding a slash at the end of those two lines
```
ProxyPass / https://10.220.2.40:8061
ProxyPassReverse / https://10.220.2.40:8061
```
must be

```
ProxyPass / https://10.220.2.40:8061/
ProxyPassReverse / https://10.220.2.40:8061/
```


I've just try on my own heimdal I've got a buggy interface like you.

**Comment by jpoggi** [comment]
@Blackraz0r any news ?

**Comment by Blackraz0r** [comment]
i shit you not, this was the god damn error. wow. i feel like an idiot now. 

thank you so much for pointing that out. i compared my config to the one of alle the other ones but didnt see it. thank you mate!

**Comment by jpoggi** [comment]
Glad i could help !
I suggest you to use ansible to deploy such configuration, it helps avoid this errors ;-)

**Comment by Elegant996** [comment]
Still experiencing the same issue on Caddy 2.0.0 with the below config:

```
:2015 {
  root * /var/www/html/public
  encode gzip
  php_fastcgi unix//run/php-fpm/php-fpm.sock
  file_server
  log stdout
  handle_errors stderr
}
```

Any ideas? I've tried changing the wildcard matcher in root to `/` and to specify `/` directly in `php_fastcgi` but the issue remains.

Thanks!

**Comment by Blackraz0r** [comment]
@jpoggi thank you very much!
What i s ansible for ? is there a foss edition? i try not to use propreitary stuff.
I read through the webpage but dont really get the gist of it.

**Comment by jpoggi** [comment]
Ansible is for deploying pretty much anything you want automate on several servers.

You can use template for your virtualhost for example, with variable.

https://docs.ansible.com/ansible/latest/index.html

**Comment by Blackraz0r** [comment]
oi, got it. ill look into this. thank you mate!

**Comment by jhautefeuille** [comment]
You must config` /config/www/.env` like this

```
APP_URL=https://mysite.mydomain/com
FORCE_HTTPS=true
```

It makes the job for the same Apache configuration as yours.

The documentation does not mention this anywhere, and I stumbled upon it by chance.

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName mysite.mydomain.com
        ServerAdmin admin@mydomain.com
        ServerSignature Off     

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        SSLCertificateFile /etc/ssl/mysite.mydomain.com/Cert_bundle.pem
        SSLCertificateKeyFile /etc/ssl/mysite.mydomain.com/privateKey.pem

        ProxyRequests Off
        ProxyPreserveHost On

        # Heimdall
        ProxyPass / "http://10.59.50.10:6650/"
        ProxyPassReverse / "http://10.59.50.10:6650/"

</VirtualHost>
</IfModule>
```
