### ISSUE TITLE
Lacking Documentation on Reverse proxy

### ISSUE THREAD

**Issue by coamtaker618** [linuxserver/Heimdall#472]
While I appreciate that a section titled "Reverse Proxy" exists and addresses the concern, I find it inadequate for anyone who hasn't already done this.  Is there an existing guide somewhere that gives a little more in the way of details?

**Comment by albakham** [comment]
I have no issue whatsoever with an nginx reverse proxy (heimdall in docker).

I suggest you add something like this, next to proxy_pass;

```
proxy_pass_request_headers on;

proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host  $http_host;
```

**Comment by coamtaker618** [comment]
Following the directions here:
https://blog.heimdall.site/index.php/2018/02/28/installing-docker-and-heimdall-application-dashboard-on-ubuntu/

Is that this file?
/home/kodestar/docker/heimdall:/config

that I'm adding those lines of code to

**Comment by albakham** [comment]
No.

Those are nginx http rules and should be in your reverse proxy.

---
A complete example with nginx (if you use apache I can't help you): 

*I assume that you already have an nginx installation which acts as a reverse proxy for your docker containers*

- You create a file in `/etc/nginx/sites-available/heimdall.conf

- Put this in it (and *adapt it to your config*):

```
server {
        listen [::]:80;
        listen 80;

        server_name heimdall.example.net; #change to your domain

        location / {
                proxy_pass http://192.168.0.1:8080; #change ip:port to your heimdall container

                proxy_pass_request_headers on;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host  $http_host;
        }
}
```

- Then you create a symbolic link to activate the file with something like `sudo ln -s /etc/nginx/sites-enabled/heimdall.conf /etc/nginx/sites-enabled/heimdall`

- Finally you restart nginx `sudo systemctl restart nginx`

**Comment by coamtaker618** [comment]
Had to disable default, but I ran certbot and even got HTTPS works.

Thanks @albakham :)

PS: I'm happy to close this now but that should really be made into a standalone page.  And since this is linuxserver github page, probably use nginx container rather than direct install on howto?
