### ISSUE TITLE
ErrorException thrown with message "symlink(): Permission denied"

### ISSUE THREAD

**Issue by jackberry** [linuxserver/Heimdall#473]
ErrorException thrown with message "symlink(): Permission denied"

Stacktrace:
#33 ErrorException in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:252
#32 symlink in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:252
#31 Illuminate\Filesystem\Filesystem:link in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Console/StorageLinkCommand.php:35
#30 Illuminate\Foundation\Console\StorageLinkCommand:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
#29 call_user_func_array in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
#28 Illuminate\Container\BoundMethod:Illuminate\Container\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
#27 Illuminate\Container\BoundMethod:callBoundMethod in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
#26 Illuminate\Container\BoundMethod:call in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php:572
#25 Illuminate\Container\Container:call in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Command.php:183
#24 Illuminate\Console\Command:execute in /var/www/localhost/heimdall/vendor/symfony/console/Command/Command.php:255
#23 Symfony\Component\Console\Command\Command:run in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
#22 Illuminate\Console\Command:run in /var/www/localhost/heimdall/vendor/symfony/console/Application.php:921
#21 Symfony\Component\Console\Application:doRunCommand in /var/www/localhost/heimdall/vendor/symfony/console/Application.php:273
#20 Symfony\Component\Console\Application:doRun in /var/www/localhost/heimdall/vendor/symfony/console/Application.php:149
#19 Symfony\Component\Console\Application:run in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Application.php:89
#18 Illuminate\Console\Application:run in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Application.php:188
#17 Illuminate\Console\Application:call in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:250
#16 Illuminate\Foundation\Console\Kernel:call in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:237
#15 Illuminate\Support\Facades\Facade:__callStatic in /var/www/localhost/heimdall/app/Providers/AppServiceProvider.php:52
#14 App\Providers\AppServiceProvider:boot in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
#13 call_user_func_array in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
#12 Illuminate\Container\BoundMethod:Illuminate\Container\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
#11 Illuminate\Container\BoundMethod:callBoundMethod in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
#10 Illuminate\Container\BoundMethod:call in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php:572
#9 Illuminate\Container\Container:call in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:819
#8 Illuminate\Foundation\Application:bootProvider in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:802
#7 Illuminate\Foundation\Application:Illuminate\Foundation\{closure} in [internal]:0
#6 array_walk in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:803
#5 Illuminate\Foundation\Application:boot in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php:17
#4 Illuminate\Foundation\Bootstrap\BootProviders:bootstrap in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:211
#3 Illuminate\Foundation\Application:bootstrapWith in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:162
#2 Illuminate\Foundation\Http\Kernel:bootstrap in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:146
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/localhost/heimdall/public/index.php:55

**Comment by majithphp** [comment]
sudo php artisan storage:link
