### ISSUE TITLE
13th app not shown

### ISSUE THREAD

**Issue by zilexa** [linuxserver/Heimdall#476]
I have added 13 applications. The first 12 were easy as they were auto-filled by Heimdall. Clearly they are supported and known. 
The 13th application is simply the address of my Router. 

I can see it in Heimdall > Application List
I can open the address successfully via Heimdall > application List 

However, even though it has the default tag 'home dashboard' it is not shown on the home dashboard. I only see 12 items on the home dashboard. Also when I hit the re-arrange button, the 13th application is not shown.

**Comment by WonaBee** [comment]
When you add an app that isn't recognized by Heimdall the "Pinned" flipper doesn't automatically get turned on.

Go to your application and check the top right if the flipper is in the on position or not.

**Comment by 5280Pipedream** [comment]
I am having this same issue. Turning on off the Pinned flipper doesn't add the app to the dashboard.

**Comment by kwiat** [comment]
> When you add an app that isn't recognized by Heimdall the "Pinned" flipper doesn't automatically get turned on.
> 
> Go to your application and check the top right if the flipper is in the on position or not.

Thank you - that wasn't too obvious at first. Fixed it for me as well!
