### ISSUE TITLE
Multiuser support

### ISSUE THREAD

**Issue by anoma** [linuxserver/Heimdall#48]
It is understood that this is not a small request and will require considerable effort and discussion.

Currently I authenticate users with traditional HTTP auth (.htaccess etc) using the Letsencrypt container and subfolders of a single domain

e.g.

https://my.notreal.domain/nzbget
https://my.notreal.domain/nextcloud
...

A surprising amount of applications are happy to inherit these credentials if the app is in turn configured with identical users. The net result is if a user logs in once and they are then fed their own applications specifics without ever needing to log in again.

It would be ideal if Heimdall could

- Support mutiuser
- Support inherited HTTP auth
- Allow the system admin account to control which app shortcuts each user can see to separate `user` links e.g. nextcloud from sysadmin links e.g. pihole

There is scope for unnecessary feature creep here but I cannot imagine a household application dashboard that is not multiuser capable.

related: https://github.com/linuxserver/Heimdall/issues/45

**Comment by aptalca** [comment]
If you're already reverse proxying through letsencrypt, you can add .htpasswd support through the reverse proxy here.

I'm currently rp'ing Heimdall at the main as well as a subdomain through letsencrypt with .htpasswd. The only trick was to use the https port for Heimdall in the proxy_pass directive

**Comment by KodeStar** [comment]
That something worth adding to the readme @aptalca ?

**Comment by aptalca** [comment]
Perhaps. I'll submit a PR

**Comment by KodeStar** [comment]
Awesome

**Comment by KodeStar** [comment]
Implemented in v2.0.0
