### ISSUE TITLE
[SOLVED] Jellyfin falsely listed as an enhanced app

### ISSUE THREAD

**Issue by just-an-alt** [linuxserver/Heimdall#482]
EDIT: Jellyfin is in fact an enhanced app, however, I had to update the apps list in Heimdall.

The "Jellyfin" app is listed as an enhanced app here: https://apps.heimdall.site/applications/enhanced
However, it is not enhanced, as seen in this screenshot:
![Heimdall screenshot](https://i.imgur.com/usqYsLH.png)

Please remove "Jellyfin" from the Enhanced Apps list.

**Comment by drizuid** [comment]
```
<?php namespace App\SupportedApps\Jellyfin;

class Jellyfin extends \App\SupportedApps {

}```
Jellyfin.php appears to lack any enhanced functionality, supporting this issue

**Comment by dontevenblink** [comment]
Jellyfin's enhanced functionality works for me. 
![Screen Shot 2020-05-28 at 5 07 52 PM](https://user-images.githubusercontent.com/21349125/83194177-3d631200-a106-11ea-9252-257e617b7897.png)
![Screen Shot 2020-05-28 at 5 07 32 PM](https://user-images.githubusercontent.com/21349125/83194180-3dfba880-a106-11ea-9abf-8094f5eefe91.png)

**Comment by drizuid** [comment]
> Jellyfin's enhanced functionality works for me.
> 
what did you hit to test the api functionality? just save with a valid url?

**Comment by just-an-alt** [comment]
How did you get Heimdall to test the app?
As you can see in my screenshot, there are no options as seen in other enhanced apps like Sonarr:
![Sonarr screenshot](https://i.imgur.com/Mipp7tI.png)

**Comment by dontevenblink** [comment]
What version are you on? I'm on 2.2.2 and I see the following when I add new Jellyfin 
![Screen Shot 2020-05-28 at 5 27 03 PM](https://user-images.githubusercontent.com/21349125/83196080-3f7aa000-a109-11ea-867f-fb2a2a114de3.png)

**Comment by just-an-alt** [comment]
I'm using linuxserver/heimdall, which is 2.2.2:
![Version](https://i.imgur.com/bMNDRn2.png)
I'm a bit confused right now

**Comment by kid1412621** [comment]
I used password to config, the test shown ok. But the numbers didn't show up. After I changed to API key, everything is good.
