### ISSUE TITLE
--Enhancement  Suggestion-- Getting Heimdall working as a proxy

### ISSUE THREAD

**Issue by antipiot** [linuxserver/Heimdall#49]
Is this possible to Get Heimdall to act as a proxy for any local services?

Maybe a master password to get access to any registred services may help to get the thing more secure.
I'm not very aware on how a proxy work but this might be great!

**Comment by aptalca** [comment]
You can reverse proxy this app through nginx with ssl. We have a letsencrypt/nginx image here: https://hub.docker.com/r/linuxserver/letsencrypt/

Through the reverse proxy, you can add security and password control via `.htpasswd`

**Comment by skluthe** [comment]
You can also use caddy if you don't want to mess around with getting let's encrypt certs and have something do it for you.

**Comment by aptalca** [comment]
? Same amount of work is required for both. Set the dns records and/or forward ports

**Comment by skluthe** [comment]
Oh wow, didn't look at the docker hub page. Thought you were talking about regular nginx. Definitely going to check that out.

**Comment by nuhll** [comment]
I dont think thats what the poster want.

He want it so he just needs to forward/authenticate to heimdall, and heimdall proxys all other requests/apps/pages. I also would be interested in this, would clean a lot of mess! And you could acess it from everywhere.

Why it should be added?

- You only need to forward 1 port
- You only need to remember 1 user:password

**Comment by antipiot** [comment]
> He want it so he just needs to forward/authenticate to heimdall, and heimdall proxys all other requests/apps/pages.

Exactly what i wanted to say, thanks for clarifying :-)

**Comment by yamlCase** [comment]
I'm torn.  I want this feature too, but also don't want Heimdall to bloat.  Maybe there's a "docker way" by using some intermediate container for this feature?

**Comment by Faeton73** [comment]
I would love to have this feature too, though I think it is way beyond Heimdall 's scope now. As a side note, I came across Heimdall (and firstly Organizr) looking for an application with this feature.
