### ISSUE TITLE
How to change ports?

### ISSUE THREAD

**Issue by Saroufim** [linuxserver/Heimdall#491]
Heimdall would like to use ports 80 and 443 which are already in use by cockpit. As such, the container fails to start. Picking different ports does not automatically work as Heimdall needs to be configured to listen to them somehow. How should Heimdall be configured to listen to different ports? Thanks in advance.

**Comment by aptalca** [comment]
map them to different ports on host `-p 85:80`

**Comment by Saroufim** [comment]
I admittedly feel ashamed for not thinking of simply doing that. Thank you very much.

**Comment by davidbhoward** [comment]
What do you do if you want to set network_mode: host?  Without an option to change port, port 80 is over-subscribed.

**Comment by shalafi99** [comment]
I have never tried to change those myself, but I think the http and https ports are defined inside file /config/nginx/site-confs/default.conf
