### ISSUE TITLE
Exception when trying to update app list

### ISSUE THREAD

**Issue by den27de** [linuxserver/Heimdall#495]
Hello, 
I am getting the following error when I am trying to update App list.
It looks like the problem has something to do with the for each loop.
I am running Ubuntu 18 and an Apache/2.4.29.
I hope you will be able to help me. :)

Many thanks 
Dennis

`/var/www/heimdall/app/Jobs/ProcessApps.php
     * @return void
     */
    public function __construct()
    {
      
    }
 
    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $localapps = Application::all();
        $list = json_decode(SupportedApps::getList()->getBody());
        $validapps = [];
    echo $list;
 
        foreach($list->apps as $app) {
            $validapps[] = $app->appid;
            $localapp = $localapps->where('appid', $app->appid)->first();
 
            $application = ($localapp) ? $localapp : new Application;
 
            if(!file_exists(app_path('SupportedApps/'.className($app->name)))) {
                SupportedApps::getFiles($app);
                SupportedApps::saveApp($app, $application);
            } else {
                // check if there has been an update for this app
                $localapp = $localapps->where('appid', $app->appid)->first();
                if($localapp) {
                    if($localapp->sha !== $app->sha) {
                        SupportedApps::getFiles($app);
                        SupportedApps::saveApp($app, $application);
                    }
                }  else {
                    SupportedApps::getFiles($app);
                    SupportedApps::saveApp($app, $application);
      
Arguments
"Trying to get property 'apps' of non-object"
`

**Comment by TGYK** [comment]
Just wanted to say that I am getting this exact same error when running in an iocage jail on FreeNAS v11.3U5. Freshly installed using [this plugin](https://github.com/jsegaert/iocage-plugin-heimdall). Unconfigured, went to open, error popped up.

**Comment by ventra007** [comment]
Also experiencing this problem. Running TrueNAS-12.0-STABLE.
Installed from scratch and when I select to manage brings to a page full of errors.

**Comment by ventra007** [comment]
Looks like this isn't actually an issue. Plugin just takes a long time to load everything, so managing it directly after setup doesn't work. Takes around 10 minutes (at least for me) to start working properly.
