### ISSUE TITLE
(Some) Font-Awesome icons not displaying

### ISSUE THREAD

**Issue by apollo13** [linuxserver/Heimdall#498]
When starting a new container and the dashboard is empty one gets:

![image](https://user-images.githubusercontent.com/81547/89803612-5ab75200-db33-11ea-8c5a-fea89d2b6e59.png)

This should display the times icon (https://fontawesome.com/icons/times). Looking at the html I think setting the unicode codepoint might be wrong: 
https://github.com/linuxserver/Heimdall/blob/6dcbcb452e9bbfe28efd0e4df8595dc87a82cc05/resources/assets/sass/_app.scss#L233
https://github.com/linuxserver/Heimdall/blob/6dcbcb452e9bbfe28efd0e4df8595dc87a82cc05/resources/assets/sass/_app.scss#L253

At least I see no requests to any font files, only fontawesome.js is loaded. All other icons seem to show up well, but they seem to be included via SVG: https://github.com/linuxserver/Heimdall/blob/master/public/js/fontawesome.js#L480-L501

**Comment by Sol-Illadan** [comment]
> When starting a new container and the dashboard is empty one gets:
> 
> ![image](https://user-images.githubusercontent.com/81547/89803612-5ab75200-db33-11ea-8c5a-fea89d2b6e59.png)
> 
> This should display the times icon (https://fontawesome.com/icons/times). Looking at the html I think setting the unicode codepoint might be wrong:
> 
> https://github.com/linuxserver/Heimdall/blob/6dcbcb452e9bbfe28efd0e4df8595dc87a82cc05/resources/assets/sass/_app.scss#L233
> 
> https://github.com/linuxserver/Heimdall/blob/6dcbcb452e9bbfe28efd0e4df8595dc87a82cc05/resources/assets/sass/_app.scss#L253
> 
> At least I see no requests to any font files, only fontawesome.js is loaded. All other icons seem to show up well, but they seem to be included via SVG: https://github.com/linuxserver/Heimdall/blob/master/public/js/fontawesome.js#L480-L501

Any updates on this issue ?

**Comment by KodeStar** [comment]
Fixed in 2.3.0
