### ISSUE TITLE
There should be a note on this repo that new development is happening in the heimdalljs repo

### ISSUE THREAD

**Issue by dylanmtaylor** [linuxserver/Heimdall#503]
https://github.com/linuxserver/heimdalljs is where all the new development activity is, as it is the JavaScript rewrite and, once parity is reached, the old PHP version will be deprecated and replaced in the Docker containers.

**Comment by seitzbg** [comment]
Any idea when the Docker containers will be changed over?  Will the same config still work?

Thanks!

**Comment by dylanmtaylor** [comment]
From my understanding, as soon as feature parity is reached in the rewrite, which from my brief conversation with Kode means implementing enhanced app support. I don't know if the same config files would work, but I doubt it.

**Comment by KodeStar** [comment]
This has now changed, the plan is to get the main one up to date and pull any of the useful functionality from heimdalljs back into this.
