### ISSUE TITLE
StreamHandler.php could not be opened: failed to open stream: Permission denied                 

### ISSUE THREAD

**Issue by crazypete00** [linuxserver/Heimdall#504]
Running Heimdall on Docker/Portainer on Ubuntu.
I have mounted a Windows CIFS on Ubuntu
The mnt is binded in portainer to /config

Run the container it created the filles at the mount so permissions are fine. However the log shows an error

In StreamHandler.php line 107:
The stream or file "/var/www/localhost/heimdall/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

**Comment by crazypete00** [comment]
This is the output of ls -l /config from within the docker container

root@93axxxx:/# ls -l /config
total 0
drwxr-xr-x 2 root root 0 Sep  8 10:32 keys
drwxr-xr-x 2 root root 0 Sep  8 10:32 log
drwxr-xr-x 2 root root 0 Sep  8 10:32 nginx
drwxr-xr-x 2 root root 0 Sep  8 10:32 php
drwxr-xr-x 2 root root 0 Sep  8 11:15 www
root@93af31002fab:/# chmod 0777 -R /config
root@93a93axxxx:/# ls -l /config
total 0
drwxr-xr-x 2 root root 0 Sep  8 10:32 keys
drwxr-xr-x 2 root root 0 Sep  8 10:32 log
drwxr-xr-x 2 root root 0 Sep  8 10:32 nginx
drwxr-xr-x 2 root root 0 Sep  8 10:32 php
drwxr-xr-x 2 root root 0 Sep  8 11:15 www

**Comment by j0nnymoe** [comment]
This will be a permissions issue related to your mount. The UID/GID that you're running the container as needs to be owning the files down the path/mount. We don't recommend remote mounts for `/config` mounts due to issues like these.

**Comment by crazypete00** [comment]
ye been trying for a few hours to get it to work. the UID/GID in ubuntu is 1000/1000, the mnt is created with windows credentials. Looks like docker can write the files to the mnt but the container itself cant.

for now i just used a local folder on the ubuntu host which worked fine although not ideal.

**Comment by rdgerken** [comment]
I have this problem too, and I'm using a remote mount for /config... however, it says it's trying to access "/var/www/localhost/heimdall/storage/logs/laravel.log" - where is this a reference to?  A path inside the container?  I'm not understanding how this is a remote mount /config issue.  Is there a link or something back to /config from this internal location?  

TIA

**Comment by numkem** [comment]
The problem is in the permission when they are set up in the container.

I have a NFS mount done and it's working. The fix was to do `chmod 775 /config`

Prior to that, `/` looked like this:
```
rwxr-xr-x   1 root   root    135 Oct 23 16:19 .
drwxr-xr-x   1 root   root    135 Oct 23 16:19 ..
-rwxr-xr-x   1 root   root      0 Oct 23 16:19 .dockerenv
drwxrwxrwx   5 nobody nobody   41 Oct 23 16:19 alloc
drwxr-xr-x   1 abc   abc       6 Aug 25 16:51 app
drwxr-xr-x   1 root   root     17 Oct  9 19:57 bin
d---------   1 abc   abc      36 Oct 23 16:24 config
```

**Comment by enriquedacostacambio** [comment]
@rdgerken it looks like it:
```
$ ls -la /var/www/localhost/heimdall/.env
lrwxrwxrwx 1 root root 16 Oct  1 12:10 /var/www/localhost/heimdall/.env -> /config/www/.env
```
