### ISSUE TITLE
issue with name resolution in config optional

### ISSUE THREAD

**Issue by svemonix** [linuxserver/Heimdall#505]
I'm running Heimdall in a container that's connected to a user defined bridge. For some reason, I can't use the container name instead of its IP address in the field 'config optional' for Transmission. I get error 421.

I can ping 'transmission' from the Heimdall container so I'm not quite sure what the problem is. Is Heimdall preventing name resolution?

Thanks for your help!

**Comment by keriati** [comment]
Heimdall should not prevent name resolution, I would guess there is an infrastructure issue behind this problem.

**Comment by drxen00** [comment]
> I'm running Heimdall in a container that's connected to a user defined bridge. For some reason, I can't use the container name instead of its IP address in the field 'config optional' for Transmission. I get error 421.
> 
> I can ping 'transmission' from the Heimdall container so I'm not quite sure what the problem is. Is Heimdall preventing name resolution?
> 
> Thanks for your help!

hey op, did you ever get this fixed? im having the same issue. everythings on an custom network i set up
