### ISSUE TITLE
Tag URLs do not respect APP_URL 

### ISSUE THREAD

**Issue by joszz** [linuxserver/Heimdall#507]
When hosting Heimdall outside of the root of the domain, there will be problems with the tag URLs pointing to the root.
in app/Item.php function getLinkAttribute
the link is buildup using a relative to root (starting with slash).
Either removing the starting slash (to make it relative to the current directory) or 
return env('APP_URL') . '/tag/'.$this->url;

will fix this issue.

**Comment by kg333** [comment]
resources/views/tags/list.blade.php also needs a fix:
https://github.com/linuxserver/Heimdall/blob/61a5a1a8b023771e0ff7c056add5537d20737e51/resources/views/tags/list.blade.php#L33
to:
```
<td><a{{ $app->target }} href="{{ env('APP_URL') }}/tag/{{ $app->url }}">{{ $app->link }}</a></td>
```
