### ISSUE TITLE
[Request] Show if service is online or not (eg via green/red light)

### ISSUE THREAD

**Issue by TheGammelgalopper** [linuxserver/Heimdall#51]
Hey, apart from this one feature, this is exactly, what I have been looking for! A dashboard for all your links!

BUT it would be great to have a smaller dot in the corner of each tile which could show the online status of each service.

The server polls the IP(&port) every 5 or so minutes. If he gets a response, the light will turn green, otherwise red. Future additions might include a yellow light and a number with how many minutes have passed since last seen online.

**Comment by KodeStar** [comment]
Hmm, it's an interesting request, I'll definitely put some thought into this.  It would probably have an option when adding the app as to whether to monitor it, as you probably wouldn't want to monitor everything.

**Comment by TheGammelgalopper** [comment]
Yes Exactly! This sounds good!

**Comment by skluthe** [comment]
A simple ping health monitor would probably work. Or you could see about uptime robot integration if it isn't too complex. I'm sure there's something out there that's opensource you could implement.

**Comment by bassrock** [comment]
A way to set the health check url as well would be awesome!

**Comment by anoma** [comment]
We should by default try and think of ways to do this via Enhanced App. i.e. is there a project that monitors services and has an api that can be used to provide info to Heimdall on status.

If there isnt a suitable upstream project then we should start looking into this because what at first seems like as simple idea will very quickly prove not to be. IMHO anyway.

**Comment by zag2me** [comment]
Many years ago I wrote a little php ping app, may be useful although the code is terrible :)
https://github.com/zag2me/PHP-Server-Monitor

**Comment by DavidRawling** [comment]
I'd suggest that ping isn't a great solution for this, as you might (probably will!) have hosts with multiple services. Containers, or just multiple apps on a single host fit this model. If you have (say) Plex, Sonarr and Radarr on one host, you'd want the indicator to show separate statuses for each, but ping would just show the underlying host.

If the goal is maximum flexibility, then I'd suggest a monitored item should have a "monitor URL" - which defaults to the main URL - and the HTTP status code for a HEAD {URI} operation should govern status. 200 is green, 30x to a 200 is green. 400/500 are the errors.

**Comment by TheGammelgalopper** [comment]
Oh I didn't think of that, as most of my services have their own IP.
So querying HTTP status codes is probably a better idea!

**Comment by anoma** [comment]
The problem with this idea is that its scale to be truly useful is considerable.

For example you will need to be able to test various flavors of service, TCP, UDP, ICMP... then you quickly need to understand HTTP error codes... but that leads to being able to check content as a blank page with 200 code is still an error.

And then there is "IF THENS". For example there no point alarming that all your web links are down if all that means is your internet connection broke.

On top of that we need to be able to handle the various authentications that will be required.

For sure some basic HTTP 200 test of the shortcut is up could be useful but IMHO it would be far better to find a proper project that does this and tie into their api
