### ISSUE TITLE
OCI runtime create failed: /init: no such file or directory

### ISSUE THREAD

**Issue by KennethSeiero** [linuxserver/Heimdall#511]
Hi

I've had Heimdall running great for weeks. After a restart of the docker image, i suddenly get below error message. I've tried reinstalling, running without configs etc. nothing works.

Any idea? 

`Start container linuxserver-heimdall1 failed: {"message":"OCI runtime create failed: container_linux.go:345: starting container process caused \"exec: \\\"/init\\\": stat /init: no such file or directory\": unknown"}.`

--

`

**Comment by j0nnymoe** [comment]
Please provide the information asked for in the issue template so we can help.

**Comment by KennethSeiero** [comment]
Hi @j0nnymoe , i did love to. I've tried to find the template you're referring to, but without luck. 
Any chance you can point me in the right direction?

**Comment by j0nnymoe** [comment]
Ah just checking, my the template is on the `docker-heimdall` repo. Please could you open this issue on https://github.com/linuxserver/docker-heimdall/issues/ ?
Thanks
