### ISSUE TITLE
What's the point of pinning?

### ISSUE THREAD

**Issue by dokbua** [linuxserver/Heimdall#513]
What's the point of pinning?  If I don't pin an app it doesn't show up, so I'd assume all app should be pinned?  
Sorry, just trying to understand the functionality.

**Comment by Griefed** [comment]
Pin/Unpin allows you to set a card/app aside for when it may or may not be relevant at the moment. For example:
Say I've got an apache running on a system for running some stuff with it. During those tests, it is usefull to have a quick link to said apache available. 
When testing is complete, the apache gets shut down, so the link in Heimdall is no longer necessary. BUT, it may be relevant again sometime in the future, for more tests, SO you unpin it for later use.

If you delete it, you have to enter everything again in order for it to be available again. When unpinning, you can toggle it to your hearts content.

Hope that cleared things up for you. 🙂

**Comment by dokbua** [comment]
Thanks for the explanation. I guess that kinda what I thought it might be for. Maybe calling it activate/deactivate would make more sense, just an idea ;)

**Comment by GregHilston** [comment]
It'd be nice if one could put a card/app inside a Tag, which I'm treating like a folder, without having to pin it.

If its unpinned, the card will not show up if in the tag. 

Fit its pinned, the card shows up both on the home page and the tag.

**Comment by Bomfunk** [comment]
> i was wrong, one can go into the tag (folder) and modify the pins in the UI and it will show up only in the folder
Can someone please let me know how this can be done? No matter what I do, it seems to work more like this to me:
> If its unpinned, the card will not show up if in the tag. If its pinned, the card shows up both on the home page and the tag.
