### ISSUE TITLE
Missing Check Mark Icon when crating a new Application or updating one.

### ISSUE THREAD

**Issue by eXsoR65** [linuxserver/Heimdall#517]
![image](https://user-images.githubusercontent.com/19521349/98421222-dbb0b780-2056-11eb-9ba4-627353c26dab.png)

Using the newest build linuxserver/heimdall:2.2.2-ls106 but I also see the issue in 2.2.2-ls104 & 2.2.2-ls105

**Comment by KodeStar** [comment]
Should be fixed in 2.3.0
