### ISSUE TITLE
Layout changes between arrange and display

### ISSUE THREAD

**Issue by ptr727** [linuxserver/Heimdall#518]
I am trying to arrange my cards in order.
I click the arrows, arrange them, and when I click the grid or arrows again, the layout changes.
Problem is the size of the grid is different between arrange and display, such that there are more columns in arrange mode than there is on normal grid mode.

Arrange:
```
1  2  3  4  5  6
7  8  9  10 11 12
13 14 15 16 17 18
```

Display:
```
1  2  3  4  5
6  7  8  9  10
11 12 13 14 15
16 17 18
```

**Comment by tablatronix** [comment]
How do you arrange?
All my icons are in one giant long ass row.. There is no grid whatsoever, its annoying af, what am I missing here?
Is there a basic config somewhere I missed to just say max_cols=4 ?

![Screen Shot 2022-01-31 at 9 04 37 PM](https://user-images.githubusercontent.com/807787/151907712-e0f1e826-1bbf-40e5-a94a-2bca38414442.png)

**Comment by j0nnymoe** [comment]
Arrows icon in bottom right menu then drag them accordingly.

**Comment by j0nnymoe** [comment]
oh, and the grid is reflective on screensize currently.

**Comment by tablatronix** [comment]
The new custom css works wonders! Perfect

```css
#app .content {
    margin: auto;
    max-width: 1024px;
}
```

![Screen Shot 2022-03-19 at 9 02 02 PM](https://user-images.githubusercontent.com/807787/159144807-a49bc173-9c2f-4bf5-8a12-83a86c6e473e.png)

**Comment by ZeeWeeWee** [comment]
@tablatronix my freaking hero!
