### ISSUE TITLE
Tile is renamed

### ISSUE THREAD

**Issue by ekw** [linuxserver/Heimdall#519]
I added an application for ZoneMinder:

Application name: Zoneminder
Application Type: ZoneMinder

When I load Heimdall, I see "Zoneminder" on the tile for a split second, then it changes to "Zone reducer".  

When I edit the name to "ZoneMinder", it works as expected.

When I edit the name back to "Zoneminder", it'll change to "Zone reducer" again.

So I keep the name at ZoneMinder now, but just thought it a strange bug.

**Comment by KodeStar** [comment]
Not sure if this is still an issue? I can't replicate it. Reopen if you find a way to reliably replicate it :)
