### ISSUE TITLE
App request

### ISSUE THREAD

**Issue by bretsky84** [linuxserver/Heimdall#52]
Saw this on Reddit and it looks really slick.  How hard would it be at add support for Sickrage and Piwigo?  I haven't tried it yet but I am definitely in the market for a landing page for the various things I host.  Would a "custom" app that just links to other sites be an option?

edit, nevermind, answered my own question!

**Comment by KodeStar** [comment]
:) glad we could help ;) on a serious note you can request support for foundation requests, and if you can help source images to be used for the icons then we are even more likely to help.  Icons need to be 250 x 250px, preferably PNGs with transparency.
