### ISSUE TITLE
Help getting SSL certs to work

### ISSUE THREAD

**Issue by iandstanley** [linuxserver/Heimdall#527]
I have a OpenMediaVault server running a few apps in portainer on my Raspberry Pi

1. I managed to get Heimdall up and running locally in a portainer container on the Pi via the Pi's IP adddress of 192.168.1.250 on both :1180 and :1443 the two ports I configured.

2. I have Cloudflare DNS setup with an A record pointing to 192.168.1.250 (i'm not planning on using it externally)

3. I have Nginx reverse proxy receiving the domain ad pointing it to the localhost (bridged network) on 1443

4. I created a Cloudflare Origin Server certificate for my domain and downloaded it and the key file locally.

5. I followed the  instructions in Self signed Certificates in the README (https://github.com/linuxserver/Heimdall#self-signed-certificates-and-local-cas) to copy the certificates and point the config to it 

Loading the page it loads on port 1443 but it comes up as 'Not Secure'  - when looking at the certifcate  viewer it is still using the Linuxserver.io certificate rather than the Cloudflare Origin 

Any ideas?

**Comment by in-famous-raccoon** [comment]
Hi,

i don't use a reverse proxy, but i just replaced the key and crt with my own certificates (do not change the filenames!)
you can find these in "/config/keys/"

maybe this will help you.

**Comment by iandstanley** [comment]
Thanks

Sorry about the long delay I missed the comment
