### ISSUE TITLE
Heimdall crashed?

### ISSUE THREAD

**Issue by HassanMullah** [linuxserver/Heimdall#531]
Good morning,

i have been running heimdall on docker compose since yesterday. Apparently something "over night" has passed here. Can you see from the screenshot where the problem is or how would you proceed here. Sure, I can always reboot, but that should not be the goal.

![grafik](https://user-images.githubusercontent.com/4198497/101452716-6aeb0c80-392e-11eb-84f9-c03612e5475e.png)

Thanks a lot

Greeting H-BLOGX

**Comment by KodeStar** [comment]
Fixed in 2.3.0
