### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by flok** [linuxserver/Heimdall#536]
Hey guys

i'm really struggling to find any informations how this works. Maybe i'm just stupid and missing something.

For example i add a Node-Red instance to heimdall like this:

![image](https://user-images.githubusercontent.com/37000563/103241766-81e0b580-4954-11eb-9308-7ef73a55faa6.png)

But when i click it redirects me to: https://heimdall_url:heimdall_port/node-red_url:node-red_port instead of the URL i  specified in the image above? Seems straight forward to me but doesnt seem to work obviously.

I also read about some automated finding of used apps in the network but that also doesnt seem to work.

i run heimdall as a docker container on a rpi4

Greeting and thanks for any help

**Comment by j0nnymoe** [comment]
Needs to be a full url "http://ip" etc etc

**Comment by KyleWJohnston** [comment]
I had this issue too, as did #414. Would this be appropriate to add to the README? I'm guessing most people know this inherently, but for some of us it could be useful. I'll submit a PR unless you think it's unnecessary detail.

My understanding of how the URLs work:
- If `http` or `https` is in the URL, the URL is the full absolute path
- If `http` or `https` is NOT in the URL, the URL is appended to the current path (relative path)
- Looks like it also supports files (`/file`) and network locations (`//network`)

Relevant code: https://raw.githubusercontent.com/linuxserver/Heimdall/3a9bdd2c431d70803b259990fa4d81db4b06dba4/vendor/symfony/routing/Generator/UrlGeneratorInterface.php
