### ISSUE TITLE
Troubleshoot 419 error

### ISSUE THREAD

**Issue by nilp0inter** [linuxserver/Heimdall#539]
Hi,

Since a week or so I am getting this error when I try to add new applications:

![image](https://user-images.githubusercontent.com/1224006/104583030-ebeda000-5660-11eb-81fb-e5a68ca252de.png)

I am not aware of having changed anything and I think my permissions are ok, but I can't figure out how to troubleshoot and fix this.

Any guidance on how to troubleshoot this would be very appreciated.

Thank you

**Comment by mychips70** [comment]
ive been getting the same thing for months

**Comment by KodeStar** [comment]
This may be fixed in 2.3.0, reopen if not and you can reliably replicate as I can't seem to get it to happen.
