### ISSUE TITLE
Radarr - Incorrect "Missing" & "Queue" counts.

### ISSUE THREAD

**Issue by CorneliousJD** [linuxserver/Heimdall#540]
Having an odd issue where Radarr is being reported as having 1 item in the queue, however my queue in Radarr is empty and all missing movies are currently unrelased still. 

Note that I only have 9 items in my wanted list. Yet it shows 10
Also 0 items in my queue.

Restarting Radarr/Heimdall does not help, the queue number will show 0 for a while but hten go back up to one after a few minutes.

Everyone from Radarr support Discord and support threads are telling me it's a Heimdall issue, otherwise I'd see my problems reflected somewhere in GUI.

 

Screenshots below.

 

Thanks in advance!

 

![image](https://user-images.githubusercontent.com/724777/104670641-3e9f7a00-56aa-11eb-8843-30e97d82cb8d.png)

![image](https://user-images.githubusercontent.com/724777/104670660-4828e200-56aa-11eb-80fc-bbd85852ea37.png)

![image](https://user-images.githubusercontent.com/724777/104670676-4fe88680-56aa-11eb-854c-8a826747bb7f.png)

**Comment by aptalca** [comment]
Filter for wanted and see if there is an additional one it picked up from the downloader that's stuck

**Comment by CorneliousJD** [comment]
> Filter for wanted and see if there is an additional one it picked up from the downloader that's stuck

So I was able to see an "unknown movie" in queue, removed that, but wanted/missing both are showing the same number of movies, and Heimdall is reporting 1 more than that constantly.

Is there an API command I can run to see if it will spill the beans on what that movie is that I can't see in the UI?

**Comment by CorneliousJD** [comment]
I was able to locate the issue, sorry for submitting this here, it ended up being on Radarr side, despite people telling me it had to be a Heimdall issue. :) 

The API command I ran and dumped to a text file helped me find it. 

curl -X GET "https://localhost:7878/api/v3/movie" -H "accept: application/json"

I then looked for "hasFile": false to find what movies were missing, and found one that wasn't in the GUI under missing and just removed it from Radarr entirely for now to prevent the issue.

Queue issue was an "unkonwn movie" which you can show in UI via options toggle in top right corner.

**Comment by ameyrakheja** [comment]
Thanks for the suggestion. While I wasn't able to get the `curl` command working, I was able to set a custom filter ("Size on disk" "less than" "1") in the GUI which displayed the items with no linked file.
