### ISSUE TITLE
Heimdal unable to automait load apps icons

### ISSUE THREAD

**Issue by jhemelo** [linuxserver/Heimdall#545]
I have just completed  a fresh install of Heimdall docker container with the latest image, however, I noticed that the following errors on the container log:

`Setting permissions,
[cont-init.d] 50-config: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[2021-01-20 00:40:50][142] Processing: App\Jobs\ProcessApps,
[2021-01-20 00:40:51][143] Processing: App\Jobs\ProcessApps,
[2021-01-20 00:40:53][144] Processing: App\Jobs\ProcessApps,
[2021-01-20 00:40:53][144] Failed:     App\Jobs\ProcessApps,
[2021-01-20 00:41:06][145] Processing: App\Jobs\ProcessApps,
[2021-01-20 00:41:07][146] Processing: App\Jobs\ProcessApps,

 tried download the  list of apps from this  URL https://github.com/linuxserver/Heimdall-Apps/archive/master.zip into the directory  /config/www/SupportedApps that was previously empty.. however the issue persist.

I also noticed that Heimdall application is also unable to complete the update of new background image. I also verify my router settings and I don't have any restriction that could block any ports on my system. Does anyone have any suggestion?

**Comment by tinyb0** [comment]
the same issue with you ，i restart the docker app service to fix the bg pic problem，but the app icon still can't load.

**Comment by pawelantczak** [comment]
https://heimdall.site/ site is down along with https://apps.heimdall.site/applications/foundation where supported apps are taken from.

**Comment by TNT911** [comment]
Same issue as well.  Actually I was quite surprised this happened.  Maybe it was my fault for thinking this was a true standalone application.  I was hoping to use it for multi users.

By chance is there anyway to make heimdall not dependent on heimdall.site ?!

**Comment by jd84** [comment]
I've the same problem, any status update here?

**Comment by Andrysky** [comment]
it looks like I have a similar problem - cannot get the list of applications 

laravel.log - ` laravel.ERROR: cURL error 6: Could not resolve host: apps.heimdall.site (see http://curl.haxx.se/libcurl/c/ libcurl-errors.html) {"exception": "[object] (GuzzleHttp \\ Exception \\ ConnectException (code: 0): cURL error 6: Could not resolve host: apps.heimdall.site (see http: // curl .haxx.se / libcurl / c / libcurl-errors.html) at /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185) `

pings from the host machine without problems, from docker no - `root @ 5ee6682dae74: / # ping apps.heimdall.site
ping: bad address 'apps.heimdall.site' `

**Comment by Andrysky** [comment]
I manually copied all folders from https://github.com/linuxserver/Heimdall-Apps/ to / config / www / SupportedApps /
, then connected to the container and executed
```
cd /config/www/SupportedApps/
for i in $(ls -d */); do php /var/www/localhost/heimdall/artisan register:app ${i%%/}; done
```
// https://github.com/linuxserver/Heimdall-Apps/wiki/Creating-Enhanced-Apps
![image](https://user-images.githubusercontent.com/5894390/109271199-3a758900-7820-11eb-9b65-ba75bcf71467.png)
only since he cannot perform dns resolution, you must specify ip instead of the name - otherwise there will be no statistics (

**Comment by j0nnymoe** [comment]
It's because apps.heimdall.site is down. I'll poke @KodeStar to get him to check.

**Comment by j0nnymoe** [comment]
@Andrysky Site is back up now, not sure what happened there so this should fix your issue.

> it looks like I have a similar problem - cannot get the list of applications
> 
> laravel.log - `laravel.ERROR: cURL error 6: Could not resolve host: apps.heimdall.site (see http://curl.haxx.se/libcurl/c/ libcurl-errors.html) {"exception": "[object] (GuzzleHttp \\ Exception \\ ConnectException (code: 0): cURL error 6: Could not resolve host: apps.heimdall.site (see http: // curl .haxx.se / libcurl / c / libcurl-errors.html) at /var/www/localhost/heimdall/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185)`
> 
> pings from the host machine without problems, from docker no - `root @ 5ee6682dae74: / # ping apps.heimdall.site ping: bad address 'apps.heimdall.site' `

**Comment by Andrysky** [comment]
@j0nnymoe 
for me the site works ...
but he cannot resolve dns names

**Comment by j0nnymoe** [comment]
Thats an issue outside of Heimdall itself but likely how you've deployed the container. Please can you open the issue on https://github.com/linuxserver/docker-heimdall and post the requested info.

Thanks

**Comment by Andrysky** [comment]
ok)
