### ISSUE TITLE
Custom Default Search

### ISSUE THREAD

**Issue by JacobOkanta** [linuxserver/Heimdall#548]
I am attempting to set a custom search provider as default, I used the instructions on the wiki to add the provider to heimdall (adding the search interface to an app). I know almost nothing about php code and have been unable to "reverse engineer" a solution. 

So after 2 days of failed attempts, I'm asking for help. Is there a correct solution for this or is this not possible at present?

**Comment by KodeStar** [comment]
Not currently possible, but should be as soon as I’ve imported the functionality from heimdalljs
