### ISSUE TITLE
linuxserver/heimdall:2.2.2-ls115 crashes

### ISSUE THREAD

**Issue by Feilner** [linuxserver/Heimdall#554]
Just updated the docker container to linuxserver/heimdall:2.2.2-**ls115**

It crashed during startup:
heimdall          | In ArrayInput.php line 135:
heimdall          |
heimdall          |   Trying to access array offset on value of type int

I revered the container back to linuxserver/heimdall:2.2.2-**ls114** and it works fine.

**Comment by moritz-topp** [comment]
Same here :D 
`ErrorException (E_NOTICE)
Trying to access array offset on value of type int`
`ErrorException 
…/vendor/symfony/console/Input/ArrayInput.php:135`

**Comment by radiochild577** [comment]
Same issue here - "Trying to access array offset on value of type int"

**Comment by aptalca** [comment]
yup, looks like a php update borked it, pinged the dev

**Comment by slopert** [comment]
Same issue here  "In ArrayInput.php line 135 "

**Comment by gpopesc** [comment]
same issue, after today's update

**Comment by j0nnymoe** [comment]
The changes have been reverted. Update again and it will be fixed.
