### ISSUE TITLE
App URL is being added on to end of heimdall URL when selecting an app

### ISSUE THREAD

**Issue by BlankSlate56** [linuxserver/Heimdall#562]
I'm running Heimdall via docker on my synology NAS. When I click on the icon on the dashboard, it launches a new tab with an address of http://192.168.1.14:30307/192.168.1.14:30306, and I get a 404 page not found error.

192.168.1.14:30307 is heimdall, while 192.168.1.14:30306 is photoprism. Why is Heimdall tacking the photoprism url onto the heimdall url? I have this problem for both the bitwarden app and the photoprism app, and it occurs in both firefox and microsoft edge browsers.

This is all from hardwired, LAN computers.  Below is my docker-compose file.

version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./config:/config
    ports:
      - 30307:80
      - 30308:443
    restart: unless-stopped

**Comment by Roxedus** [comment]
A *URL* includes the scheme(http/https). Without this, your browser assumes it is a relative path.

**Comment by BlankSlate56** [comment]
Sorry.  You are correct.  I have included that in the application url box, I don't know why it wasn't present in the link I posted.

**Comment by BlankSlate56** [comment]
Also, it is now working. grr. I was experimenting with leaving the https:// or http:// in and out of the url box in the hopes it'd fix something.  I added it back in after your message and now it is working.  I don't know what the difference was, I tried that about 5 different ways last night.

**Comment by BlankSlate56** [comment]
It's like taking your car to a mechanic when it is making a sound and it stops making it as soon as they step out to listen to it.
