### ISSUE TITLE
Installation instruction with Lighttpd?

### ISSUE THREAD

**Issue by mvondemhagen** [linuxserver/Heimdall#563]
Can anyone give a hint how to get this running under lighttpd? 
Lighttpd doesn't support .htaccess, and that seems to be important.
I get a 404 for http://$url/items/create and from googling, that seems to be .htaccess related.

**Comment by gstrauss** [comment]
There is a single file: `public/.htaccess` which contains some Apache directives.  To use lighttpd, those directives would need to be translated to lighttpd syntax and put into lighttpd.conf.  I am not familiar with Heimdall, but in the `public/.htaccess`, I see a small number of items, and most are probably options.  The primary functionality of directing requests to index.php can be achieved in lighttpd with [lighttpd mod_rewrite](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModRewrite)
```
server.modules += ("mod_rewrite")
url.rewrite-if-not-file = ("" => "/index.php${url.path}${qsa}")
```
and you'll have to configure [lighttpd mod_cgi](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModCGI) to run PHP as CGI, or [lighttpd mod_fastcgi](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModFastCGI) to run PHP via FastCGI.  Running PHP via FastCGI and using PHP-FPM is the recommended option.
