### ISSUE TITLE
Deprecated code when running in PHP 8.

### ISSUE THREAD

**Issue by crkinard** [linuxserver/Heimdall#568]
nginx/1.18.0
PHP version: 8.0.3

Deprecated: Method ReflectionParameter::getClass() is deprecated in /usr/local/www/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 838

Deprecated: Method ReflectionParameter::getClass() is deprecated in /usr/local/www/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 912

Deprecated: Method ReflectionParameter::getClass() is deprecated in /usr/local/www/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 838

Deprecated: Method ReflectionParameter::getClass() is deprecated in /usr/local/www/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 912

**Comment by aptalca** [comment]
Laravel version heimdall v2 is using is not compatible with 7.4 or later. You need to use 7.3 unfortunately

**Comment by crkinard** [comment]
Ahh, yay. Guess I need to build another iocage.

**Comment by aptalca** [comment]
or you can just use the docker image for heimdall it comes with everything needed
