### ISSUE TITLE
Jellyfin no longer shows counts of movies/shows...API communication is successful. 

### ISSUE THREAD

**Issue by nicizit** [linuxserver/Heimdall#570]
I had to install a new ssd cache and all my other apps in Heimdall are reporting as per usual. Jellyfin is the only one that seems affected. In the settings, the API test comes back successfully, and the URL takes me to the Jellyfin webapp no problem...but, no counts of any kind appear. I tried a library scan, delete and reinstall into Heimdall, shutting off the VPN, and changing the reverse proxy around.

Nothing seemed to fix it, any guidance is greatly appreciated!

**Comment by j0nnymoe** [comment]
Sounds like something has changed in Jellyfin's API. Issue is that the enhanced app for Heimdall was a community supplied app. Hopefully someone will submit a fixed version soon.

**Comment by nicizit** [comment]
Ah, that makes sense...thanks a bunch for the info!

Sounds a bit out of my wheelhouse to tweak on my own.

**Comment by pixxon** [comment]
I ran into this as well, I believe it could be an issue in https://github.com/linuxserver/Heimdall-Apps

My environment details:
Everything running in a docker swarm on ubuntu linux. Heimdall and Jellyfish are behind a Traefik reverse proxy.
Heimdall runs on `PathPrefix /`, Jellyfish under `PathPrefix /jellyfin`. Jellyfin has the 10th ID in the list and every other app (except transmission which i need to debug further) works fine.

Home page constantly throws: `Failed to load resource: the server responded with a status of 500 (Internal Server Error)` pointing at Jellyfin.
http://192.168.0.129/get_stats/10 shows an error:
```
ErrorException (E_NOTICE)
Trying to get property 'MovieCount' of non-object.
```
Exception is thrown at https://github.com/linuxserver/Heimdall-Apps/blob/master/Jellyfin/Jellyfin.php#L25.

Running the query by hand:
```
curl -ki http://192.168.0.129/jellyfin/emby/Items/Counts -H "X-MediaBrowser-Token: XXX"
HTTP/1.1 200 OK
Date: Mon, 29 Mar 2021 10:17:34 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked
X-Response-Time-ms: 7

{"MovieCount":27,"SeriesCount":56,"EpisodeCount":2727,"ArtistCount":0,"ProgramCount":0,"TrailerCount":0,"SongCount":0,"AlbumCount":0,"MusicVideoCount":0,"BoxSetCount":0,"BookCount":0,"ItemCount":0}
```

I'm not fluent in php, but might take a look at what went wrong here.

**Comment by pixxon** [comment]
I also have emby installed in the stack, which works just fine while using the very same php code.

```
curl -ki http://192.168.0.129/emby/emby/Items/Counts -H "X-Emby-Token: XXX"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Date, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-MediaBrowser-Token, X-Emby-Token, X-Emby-Client, X-Emby-Client-Version, X-Emby-Device-Id, X-Emby-Device-Name, X-Emby-Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
Access-Control-Allow-Origin: *
Content-Length: 231
Content-Type: application/json; charset=utf-8
Date: Mon, 29 Mar 2021 10:24:59 GMT
Expires: -1
Server: UPnP/1.0 DLNADOC/1.50

{"MovieCount":27,"SeriesCount":55,"EpisodeCount":2727,"GameCount":0,"ArtistCount":0,"ProgramCount":0,"GameSystemCount":0,"TrailerCount":0,"SongCount":0,"AlbumCount":0,"MusicVideoCount":0,"BoxSetCount":0,"BookCount":0,"ItemCount":0}
```

http://192.168.0.129/get_stats/8 ( 8 is emby ) shows
```
{"status":"inactive","html":"<ul class=\"livestats\">\n        <li>\n        <span class=\"title\">Movies<\/span>\n        <strong>27<\/strong>\n    <\/li>\n        <li>\n        <span class=\"title\">Series<\/span>\n        <strong>55<\/strong>\n    <\/li>\n    <\/ul>\n"}
```

**Comment by shuosiw** [comment]
some problem.

```
# curl http://10.0.0.2:8096/emby/Items/Counts -H "X-MediaBrowser-Token: XXXXXXXX"
{"MovieCount":217,"SeriesCount":63,"EpisodeCount":1644,"ArtistCount":0,"ProgramCount":0,"TrailerCount":0,"SongCount":1077,"AlbumCount":63,"MusicVideoCount":0,"BoxSetCount":0,"BookCount":0,"ItemCount":0}
```

Runing curl command seems work, but on dashboard of heimdall it got a 500 error

![image](https://user-images.githubusercontent.com/2578976/118989432-9cbfcf00-b9b4-11eb-8dbe-55dba6064b3b.png)

**Comment by shuosiw** [comment]
ok, I have solved it.

https://github.com/linuxserver/Heimdall-Apps/pull/321/commits/145c61c5855d23acbb15eb77279a298f2a9a4460
