### ISSUE TITLE
Undefined property: stdClass::$availablestats (View: /config/www/SupportedApps/Emby/config.blade.php)

### ISSUE THREAD

**Issue by pythonInRelay** [linuxserver/Heimdall#572]
When allowing Heimdall to use its preconfig'd settings for Emby the below error is shown when trying to **EDIT** the details for the listing.

![Screenshot_2021-03-24 Whoops There was an error ](https://user-images.githubusercontent.com/58630825/112280226-72d87d80-8c8d-11eb-816d-694439143056.png)

It's impossible to edit the config for the Emby listing. I can however delete it and add it again, but the error still occurs.

**Comment by ukjohnd** [comment]
Same issue with Edditing Jellyfin with preconfigured settings.

**Comment by KodeStar** [comment]
Not sure if this is still an issue, I can't seem to replicate it. Reopen if you can reliably replicate and I'll look at it again.
