### ISSUE TITLE
[Feature Request] Top sites from browser

### ISSUE THREAD

**Issue by liquidthex** [linuxserver/Heimdall#592]
I'd like to suggest that the browser's most visited sites could be automatically populated onto a portion of the page.
My use case is that I've used Heimdall to replace my home page on Google Chrome browser as well as the new tab page by using an extension for chrome called New Tab Redirect. This works as expected, but it does lose the browser's built-in functionality of automatically populated site suggestions based on your frequency of visit, and that's sad :(

Google Chrome has this API for retrieving the data from the browser: https://developer.chrome.com/docs/extensions/reference/topSites/
Would it be possible to incorporate this into Heimdall?

Thanks for an awesome project! Love it!

**Comment by KodeStar** [comment]
Not something currently being looked at, but maybe in the future
