### ISSUE TITLE
Heimdall + Nginx (No Docker)

### ISSUE THREAD

**Issue by Flagelmann** [linuxserver/Heimdall#593]
Hello to all,

I'm writing because I'm just trying to install Heimdall without Docker (I do not need Docker in my actual need, just a plain normal install), but it seems really painful to do that with Heimdall....

So, basically the need would be very simple:

Nginx Reverse Proxy (main domain) + Heimdall (under a custom path (like domain.com/heimdall/)

I have used the same approach with other web apps and this kind of configuration works flawlessy, but not with Heimdall.

Also, the manual installation documentation for Heimdall is basically inexistent. I have cloned the git repo in a folder for nginx and then pointing the "root" directive, for the dedicated .conf file for nginx, to the "public" folder of heimdall....and it shows the heimdall web text, but with no css, no js....

the reverse proxy config related to Heimdall, in the nginx reverse proxy config file is like the following:

 location /h/ {
        # Heimdall
        proxy_pass http://172.16.10.:85/;
 }

Just inspecting the requests done by the browser, all the URLs related  to css/js miss the "/h/" part....

Any suggestion on how to fix this?

**Comment by zhangnew** [comment]
see #533
