### ISSUE TITLE
Supported App Sync fails upon reaching Tar1090

### ISSUE THREAD

**Issue by jpaolo90** [linuxserver/Heimdall#598]
The following error is thrown:
> [2021-06-19 03:30:21] laravel.ERROR: Class '\App\SupportedApps\Tar\Tar' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class '\\App\\SupportedApps\\Tar\\Tar' not found at /var/www/localhost/heimdall/app/SupportedApps.php:164)
> [stacktrace]
> #0 /var/www/localhost/heimdall/app/Jobs/ProcessApps.php(46): App\\SupportedApps::saveApp(Object(stdClass), Object(App\\Application))
> #1 [internal function]: App\\Jobs\\ProcessApps->handle()
> #2 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
> #3 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> #4 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
> #5 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
> #6 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
> #7 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\ProcessApps))
> #8 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\ProcessApps))
> #9 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
> #10 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\ProcessApps), false)
> #11 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
> #12 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\\Queue\\Jobs\\Job->fire()
> #13 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
> #14 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
> #15 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
> #16 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
> #17 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
> #18 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
> #19 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> #20 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
> #21 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
> #22 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
> #23 /var/www/localhost/heimdall/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
> #24 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
> #25 /var/www/localhost/heimdall/vendor/symfony/console/Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #26 /var/www/localhost/heimdall/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #27 /var/www/localhost/heimdall/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #28 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #29 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #30 /var/www/localhost/heimdall/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #31 {main}
> "} 
>

**Comment by Sahasrahla** [comment]
I believe this is caused because Heimdall's backend hates numbers in app names. I was able to get App Updates working again by essentially undoing this update:
cd Heimdall-2.2.2/app/SupportedApps/
cp -r ./Tar1090/ ./TarTenNinety/
cd TarTenNinety
mv Tar1090.php TarTenNinety.php
nano TarTenNinety.php
-- Edit the lines 1 and 3 to replace "Tar1090" with "TarTenNinety" and save
nano app.json
-- Edit line 3 to replace "Tar1090" with "TarTenNinety" and save
cd ../../..
php artisan register:app all

I actually ran into another similar error with "n8n" -> "nn", but was able to resolve it in the same manner. Now I can "Update App List" in Heimdall again successfully.

https://github.com/linuxserver/Heimdall-Apps/commit/0a0ff583788c18e85b7d3c50ab8704a7a4c1a1d1

https://github.com/linuxserver/Heimdall-Apps/commit/f6464957171a2f57de52f0d72a05d33a1acfbaa6

**Comment by stevietv** [comment]
I believe these two lines in the definition of an app are the culprit:

https://github.com/linuxserver/Heimdall/blob/61a5a1a8b023771e0ff7c056add5537d20737e51/app/Application.php#L42
https://github.com/linuxserver/Heimdall/blob/61a5a1a8b023771e0ff7c056add5537d20737e51/app/Application.php#L55

they are cleaning the application name by removing anything that isn't a letter.
I think the regex should be updated to

        $name = preg_replace('/[^\p{L}\p{N}]/u', '', $name);

**Comment by KodeStar** [comment]
@stevietv I've pushed that change, thanks
