### ISSUE TITLE
[Docker] Update APPS List failed

### ISSUE THREAD

**Issue by tobasium** [linuxserver/Heimdall#599]
Hi, I used the latest tag in docker. But many Apps are not in App List. If i want to update Apps List i got the following error in Docker: Failed:     App\Jobs\ProcessApps

Don't know whats going wrong. Already downloaded container again. Same issue.

**Comment by juanjimpad** [comment]
Hi, I have exactly the same problem. The persistent folder SupportedApps have only 82 apps while the git folder have 296, and if i try update app list, in log can read:
Processing: App\Jobs\ProcessApps
Failed:     App\Jobs\ProcessApps

**Comment by tobasium** [comment]
Thanks. Solutions works for me.

**Comment by mathewrice** [comment]
I too am experiencing this issue with a fresh installation of Heimdall as well as with existing installations.
Guessing one of the recent docker updates broke the function/feature.

Will attempt provided workaround as a temporary solution.

Thanks!

**Comment by stevietv** [comment]
I believe the issue may be caused by this:
https://github.com/linuxserver/Heimdall-Apps/commit/0a0ff583788c18e85b7d3c50ab8704a7a4c1a1d1#commitcomment-52585198

**Comment by stevietv** [comment]
see my comment also here: https://github.com/linuxserver/Heimdall/issues/598#issuecomment-867370945
