### ISSUE TITLE
Specify API scan interval?

### ISSUE THREAD

**Issue by nishantbb** [linuxserver/Heimdall#603]
For enhanced apps, such as Pi-Hole and OMV, is it possible to specify the polling interval for data collection?

**Comment by yscialom** [comment]
I'd like to support this idea. On my limited resources system (a RPi), the scan of my ~5 enhanced apps every second consumes inadequately resources on my reverse-proxy, dns and log watcher. I'd be happy to be able to set this interval myself, if possible from an environment variable.

Additionally, and maybe primarily, this polling should be simply paused when the page is not displayed (focus is on another tab for instance).

**Comment by KodeStar** [comment]
In v3 you can choose to manually update app status instead of polling, but I'll look at utilising `requestAnimationFrame` as well so it only does the polling when the tile is visible
