### ISSUE TITLE
qBittorrent not opening

### ISSUE THREAD

**Issue by alecsandes** [linuxserver/Heimdall#604]
Hey,
whenter I try to open qBittorrent i get a mesage "Unauthorized"

![image](https://user-images.githubusercontent.com/19631942/124367826-6fc53400-dc63-11eb-9a0f-9a5c3e000554.png)

Settings are like this
![image](https://user-images.githubusercontent.com/19631942/124367832-73f15180-dc63-11eb-9d41-8a8a00815154.png)

**Comment by alecsandes** [comment]
Test function returns this:

![image](https://user-images.githubusercontent.com/19631942/124367858-a8650d80-dc63-11eb-8915-966ec8e87e35.png)

**Comment by PassiveModding** [comment]
qbittorrent doesn't seem to like referrer headers, if there was a way for heimdall to add ref="noreferrer" to the link ref it'd fix.
As an alternative I found a chrome extension called "NOREF" and put my qbit url in there. Seems to have fixed the issue for me

**Comment by spencerthayer** [comment]
Same problem. Commenting to know if this ever gets fixed.

**Comment by xinyo** [comment]
Same problem.

**Comment by HNJAMeindersma** [comment]
Same problem with qBittorrent (has GUI setting to disable warning) and DD-WRT (has a nvram setting `no_crossdetect=1`). A `noreferrer` option or by default would be greatly appreciated.

**Comment by drizuid** [comment]
you should access via http://<docker host ip>:15080

assuming 15080 is the port you have mapped to 8080

**Comment by drizuid** [comment]
The URL needs to be how you access it from your machine (http://<docker host ip>:<mapped port>)
the API config is where you can put the container_name and internal port, ie; qbittorrent:8080 for api access.

**Comment by simao-silva** [comment]
@drizuid even that way the error remains. Is there another way?

**Comment by j0nnymoe** [comment]
Or just disable CSRF protection within qbittorrent.

**Comment by KodeStar** [comment]
Added rel=“noopener noreferrer” to all links in 2.3.0
