### ISSUE TITLE
Alphabatically sorting on dashboard needed

### ISSUE THREAD

**Issue by hppyworld** [linuxserver/Heimdall#613]
Hello,

It would be easy to find all the apps on dashboard if they are Alphabetically sorted. Can you please add this as a option to show all the apps with sort order Alphabetically.

Without this currently it is not easy to find a app on the dashboard screen.

Thank you.

**Comment by spencerthayer** [comment]
This really is needed, or at least manual sorting.

**Comment by j0nnymoe** [comment]
You can manually sort. Hit the arrow buttons on the menu in the corner to re-arrange.

**Comment by spencerthayer** [comment]
> You can manually sort. Hit the arrow buttons on the menu in the corner to re-arrange.

Interesting. Not sure how I've missed that for like four months. Thanks!
