### ISSUE TITLE
General error connecting with API

### ISSUE THREAD

**Issue by golles** [linuxserver/Heimdall#615]
For AdGuard Home and Portainer I get this message when I try to connect to their API's with credentials.
This might be related to #535 

I've got a feeling that this is due to a very complex/long password (40 chars with special chars and spaces).

**Comment by den7007** [comment]
Hi did you ever figure out how to connect to Adguard? Getting the same error..

**Comment by golles** [comment]
No, sorry. I'm no longer using Heimdall, I don't have a need for it.
