### ISSUE TITLE
Can't login to UrBackup

### ISSUE THREAD

**Issue by Milkysunshine** [linuxserver/Heimdall#618]
Enhanced app failing to log in.

gives error "Failed: Please make sure your URL is correct and that there is a trailing slash"

**Comment by rreisrj** [comment]
in the section "Config Optional" copy the UrBackup URL and add # in the end.  i.e. http://servername:0000/#

**Comment by alexsalex** [comment]
Added #, but Heimdall doesn't show anything... (

**Comment by ron-fr** [comment]
Under truenas 25.10, with heimdall:2.7.6 and urbackup (uroni/urbackup-server:latest) it is always not possible to log in.

P.S. if you add "#" you you cant put anything as username/password, test is OK but nothing works at all.

Best regards
