### ISSUE TITLE
Traefik Enhanced Metrics not Displayed!

### ISSUE THREAD

**Issue by Drallas** [linuxserver/Heimdall#625]
For all of my Dockerized Apps I get nice Enhanced Metrics if Heimdall supports them, but somehow Traefik doesn't want to play nice.

All my docker containers are connected to the same backend (docker) network and all of them just need http://container:port to be able to communicate and display Enhanced Metrics in Heimdall.

Traefik doens't want to communicate via the backend to Heimdall it just trows an failed url error. 
When I use the frontend IP of Traefik I get a "general error connecting with api". 

I'm a bit lost is this is supposed to work and what am I missing!?

**Comment by nearcatch** [comment]
> 
> 
> > > For all of my Dockerized Apps I get nice Enhanced Metrics if Heimdall supports them, but somehow Traefik doesn't want to play nice.
> > > All my docker containers are connected to the same backend (docker) network and all of them just need http://container:port to be able to communicate and display Enhanced Metrics in Heimdall.
> > > Traefik doens't want to communicate via the backend to Heimdall it just trows an failed url error. When I use the frontend IP of Traefik I get a "general error connecting with api".
> > > I'm a bit lost is this is supposed to work and what am I missing!?
> > 
> > 
> > If you're just using `http://container:port`, which for Traefik would be `http://traefik:8080` for the api, you need to enable `--api=true` and `--api.insecure=true` to expose the api on that port.
> > If you want password protection you can avoid api.insecure by defining a router for api access. I left out most of the below compose file to avoid bloat, so use this as a guide to add the necessary lines to your own. To authenticate in Heimdall point to `http://traefik:8080`, like the insecure process, but give Heimdall a username/password defined in .htpasswd.
> 
> Tnx for your suggestions,
> 
> I have a Macvlan (Qnet) with a fixed ip for traefik, only port 80 / 443 forwarded from my router to that endpoint.
> 
> Added the lines to my yaml and rebuild the container.
> 
> ```
>     command:
>       - --api=true
>       - --api.insecure=true
>       - --entryPoints.traefik.address=:8080 
> ```
> 
> but keep on getting a "General error connecting with API" error. to http://traefik:8080/ or http://traefik:8080/api/
> 
> note: my traefik container is connected to my docker 'backend' bridge the rest of the services I can access via http://containername that's why I put in http://traefik

Possibly macvlan network makes it weird. When I add just those three lines I'm able to get api access from Heimdall.
