### ISSUE TITLE
Selected user doesn't switch for different devices

### ISSUE THREAD

**Issue by SnowyTerror** [linuxserver/Heimdall#626]
When you have multiple users setup; if for example **Device A** is using **Account A** with set items but then **Device B** then uses it, they will see **Account A** items and will display this account in the bottom-left as logged in even if they have not logged in as **Account A** previously.

**Comment by MoonHunter1988** [comment]
can it be like that enter http://server:port/userA to userA's page, and /userB to B's page

**Comment by keriati** [comment]
When Heimdall is accessed without a session, it will display the dashboard of the first user that has the setting `Allow public access to front`. This works as expected.

During testing we did not encounter any situation that Heimdall would display on the Dashboard items from multiple users.

@lish-lib I recommend using autologin URLs if you would like to link to a specific user's Dashboard.
