### ISSUE TITLE
PRTG enhanced status not showing

### ISSUE THREAD

**Issue by straybiker** [linuxserver/Heimdall#635]
Using [ip]/api/getstatus.htm?id=0 in the config section does not result in any data showing on the card. PRTG is running on Windows.
Also using the test doesn't do anything, no succes or failure message. The provided crentials are those of a PRTG admin

**Comment by KodeStar** [comment]
Best bet is to try messaging whoever created the PTRG enhanced app, have a look on the [heimdall-apps](https://github.com/linuxserver/Heimdall-Apps) repository
