### ISSUE TITLE
Portainer info not complete

### ISSUE THREAD

**Issue by WorlockM** [linuxserver/Heimdall#639]
When adding Portainer to Heimdall you can enter your credentials to get some info of your containrs.
This kind of works, but it only shows the containers of my local environment. I also have remote docker hosts in this portainer, and these containers do not show in Heimdall.

![image](https://user-images.githubusercontent.com/31441071/148253872-3d519371-cf21-470b-b5be-72a9cea576eb.png)
![image](https://user-images.githubusercontent.com/31441071/148253920-a5267bac-085c-4b2a-aa41-46cc22edb1ca.png)

**Comment by Oscaramr** [comment]
Can i know what link you entered for this?

**Comment by WorlockM** [comment]
> Can i know what link you entered for this?

Just my portainer URL, so http://<Your_Portainer>:9000
And in the bottom I enter the Username and Password

**Comment by j0nnymoe** [comment]
You will need to open an issue on this repo https://github.com/linuxserver/Heimdall-Apps/ and tag the original dev of the enhanced app as it was community submitted. https://github.com/linuxserver/Heimdall-Apps/pulls?q=is%3Apr+sort%3Aupdated-desc+portainer+is%3Aclosed
