### ISSUE TITLE
Despite French translation, some texts are displayed in English

### ISSUE THREAD

**Issue by xavier-GitHub76** [linuxserver/Heimdall#641]
Hello,

I have updated the french translation but 3 fields seems to be not supported by the translation : 
- apps.preview
- dashboard
 - alert.success.updating
despite the French translation, these texts are displayed in English

And the text "Switch User" is not in the english file

Regards

**Comment by KodeStar** [comment]
I've merged so updates today, but if there is still missing text then the lines are missing from the translation file and need to be added
