### ISSUE TITLE
group items on main page

### ISSUE THREAD

**Issue by revenz** [linuxserver/Heimdall#646]
this has been requested a few times and always dismissed.   saying tags is there, but tags require 2 clicks to go somewhere.  can an option be added to "explode tags" to show them like this

one could hack this if there was an option for custom CSS, and custom class names on the "section" elements for each item.  as you could then just create a name "Group" item with class "group", then in the CSS .group { width:100%; border-top: 1px solid black; } kinda thing.

but since this seems to be requested a lot, can this be given more consideration?  it seems to be why people look at homer and dashy.  but their configurations are terrible.

Very quick, very rough mockup
![image](https://user-images.githubusercontent.com/958400/150204328-6e300987-3c38-4bdb-a83d-4aa611d2c106.png)

**Comment by epheterson** [comment]
100% agree, just tried out Heimdall and it's pretty great except for this one glaring omission. Some basic form of organization on the top-level page would be very appreciated. 

Agree also that two clicks to tags isn't quite the same. Perhaps the two could be combined, where tags can be displayed as groups, or links to their own pages. This way you're not limited to one or the other, and can switch between them if you choose.

**Comment by KodeStar** [comment]
Have a look at how it works on heimdalljs, the plan is to try and bring some of the elements to that into heimdall

**Comment by revenz** [comment]
I gave up on this and just wrote Fenrus.

**Comment by masterlog80** [comment]
+1 Developer may consider this. For example adding a separator would be helpful.
