### ISSUE TITLE
Laravel.log filled disk

### ISSUE THREAD

**Issue by andy47** [linuxserver/Heimdall#647]
Hi, I couldn't start my VM running Heimdall because it was out of disk space.

When I investigated there was a file called `/opt/heimdall/storage/logs/laravel.log' that was over 5Gb in size. When I deleted this file the VM and Heimdall/Apache started Ok.

Is there a way to limit the size of this log file? Or even reduce the amount of logging written to it?

**Comment by chatainsim** [comment]
Got the same issue with Docker version. Seems to be a recurrent issue with Laravel.

**Comment by KodeStar** [comment]
The latest version that will soon be released should fix this. The log level was set to debug for some unknown reason plus it was missing a config file.
