### ISSUE TITLE
Class 'Predis\Client' not found

### ISSUE THREAD

**Issue by DennisGaida** [linuxserver/Heimdall#649]
I am trying to set up redis for caching, so I'm using the following environment variables:

      REDIS_HOST: redis
      REDIS_PORT: 1234
      REDIS_PASSWORD: 1234
      CACHE_DRIVER: redis

After setting the `CACHE_DRIVER` to `redis` my log is spammed with:
```
In PredisConnector.php line 25:

In PredisConnector.php line 25:

  Class 'Predis\Client' not found
```
and checking redis I don't see anything generated/stored by Heimdall. Am I doing something wrong or is something missing from my install (i.e. the "Predis\Client" class?)? I'm using the official docker image `linuxserver/heimdall:latest`.

**Comment by Rchtr** [comment]
I've got the same message in the logs. Even if I try `REDIS_HOST: redis://redis:1234`.

**Comment by KodeStar** [comment]
you probably just need to do a `composer require predis/predis`
