### ISSUE TITLE
[Feature request] Add option to hide application name

### ISSUE THREAD

**Issue by lukasgabriel** [linuxserver/Heimdall#657]
Add an option to hide the name of the application (and the "arrow" or "tag" symbols to the right of the element) on the dashboard, so that only the icon is displayed. 

Alternatively, add an option to change the font size or the wrapping - to make the interface look more like a "Windows Desktop".
For example, I really like the look of the project homepage https://heimdall.site/. 

This relates to my #658 and loosely to #175 #103 #365

**Comment by KodeStar** [comment]
Same answer as #658 that said, once 2.2.5 is released I'm looking at overhauling the interface a bit (though not too much)
