### ISSUE TITLE
[Feature request] Move icons freely, allow resizing.

### ISSUE THREAD

**Issue by lukasgabriel** [linuxserver/Heimdall#658]
Currently, there is no way to influence how many columns get displayed, how large the icons are (except for Browser zoom which is suboptimal), or how much space there is between elements. This would be really nice to have for people with many elements - or for those that want to customize their Heimdall even further and make it look really nice.

These requests were mentioned in the following issues already:

#175 #103 #365 

But unfortunately, they were all closed without comment.

**Comment by KodeStar** [comment]
The next version has the option to add css in settings, you you can put in there any changes you would like to influence the size of the icons and how much room they take up, you can test it now by pulling from master or pulling the `development` tag on docker
