### ISSUE TITLE
400 - Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by UtopiaOpera** [linuxserver/Heimdall#659]
Installing in Docker / Portainer  using image **linuxserver/heimdall:arm32v7-2.2.2** gives me the following error on opening web interface (same issue on :lastest tag):

  **400 Bad Request
  Request Header Or Cookie Too Large
  nginx/1.18.0**

Container log doesn't seem to show any errors:
```

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
Setting permissions
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
Searching the general error for nginx suggests editing **etc/nginx/nginx.conf** file to include this setting:

```
server {
    # .
    large_client_header_buffers 4 32k;
    # .
}
```
Which didn't do anything, same error.

**Comment by magnus919** [comment]
Still a problem. Running in a Docker container with plenty of free CPU & memory. Spans multiple web browsers.

**Comment by UtopiaOpera** [comment]
> Still a problem. Running in a Docker container with plenty of free CPU & memory. Spans multiple web browsers.

I think I tracked this down to not using DNS. This could just be down to Firefox which I use, or not, but when all your services use the same IP address, all the cookies for all your different services are stuffed into one single cookie file. I don't see why it's a problem because it's still a tiny file size, and I can't remember now if I looked into increasing the allowed size of a cookie.

Anyway, I ended up using the local DNS service in Pi Hole in combination with Nginx proxy manager, and I haven't had the cookie too large error since.

**Comment by snachodog** [comment]
> all the cookies for all your different services are stuffed into one single cookie file

I encountered this error for the first time, - I just access Heimdall directly with the internal network IP address and your tip about the cookies saved the day. I cleared the cookie and it was all good again. Going to put it back into Nginx Proxy Manager so I don't have to deal with this issue.

**Comment by yewkay** [comment]
Just encountered this issue today as well. Using a different browser allowed me to access the page as normal. Cleared cookie for the heimdall page and everything loads. However, the issue comes back after a few hours. Clearing cookie again works. Doesn't seem to be a permanent solution if i have to keep clearing cookies every few hours.
