### ISSUE TITLE
After installation: include(.../app/SupportedApps/Concourse/Concourse.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by mertl2** [linuxserver/Heimdall#660]
Hi there,

I'm trying to install Heimdall (without Docker) on an Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-30-generic x86_64). Here are my steps:
- Install dependencies
- $ sudo git clone https://github.com/linuxserver/Heimdall.git ./heimdall
- Editing the ./vendor/symfony/console/Input/ArrayInput.php (see https://github.com/symfony/symfony/commit/3f431860c6992540d984f461b8dfa6ad19289ca2)
- $ sudo chown -R www-data:www-data ./heimdall
- $ sudo chmod -R 755 ./heimdall
- Customize the Apache config file

After running it in the browser (or $ sudo php artisan serve) I get the error: [In ClassLoader.php line 444:] include(/var/www/vhosts/heimdall/vendor/composer/../../app/SupportedApps /Concourse/Concourse.php): failed to open stream: No such file or directory

If I navigate to the ./app/SupportedApps directory, there is a Concourse.zip, but it contains plain ASCII text:
$ file Concourse.zip
Concourse.zip: HTML document, ASCII text
the HTML document contains "Sorry, the page you are looking for could not be found."

any ideas?

**Comment by KodeStar** [comment]
Should be fixed
