### ISSUE TITLE
Link to installation instructions on blog goes to "plex login"

### ISSUE THREAD

**Issue by robvdl** [linuxserver/Heimdall#663]
Unable to see the blog, all I see is a plex login.

https://blog.heimdall.site/index.php/2018/02/28/installing-docker-and-heimdall-application-dashboard-on-ubuntu/

Docker installation can be found here anyway https://hub.docker.com/r/linuxserver/heimdall/ but there are two links to the blog at the bottom of the homepage which go to this plex login form now.

**Comment by KodeStar** [comment]
The blog has been removed as it was just attracting tons of spam without actually getting updated, I'll look at removing the links

**Comment by robvdl** [comment]
I see, fair enough.
