### ISSUE TITLE
OpenMediaVault - excessive amount of logins

### ISSUE THREAD

**Issue by robvdl** [linuxserver/Heimdall#664]
I had OpenMediaVault configured to send notifications, turned out that was a bad idea.

When I added OpenMediaVault to Heimdall, within a short amount of time it sent over 800 emails every time Heimdall was loging into OMV to read the statistics.

Surely this can be done in a more efficient way, does it really have to log in hundreds of times per minute? can't it just stay logged in?

Meanwhile I just turned off notifications in OpenMediaVault or I'll burn through my max free emails sent via Mailgun ... I almost did :)

**Comment by KodeStar** [comment]
Turn off the enhanced part for now, I'm looking at transferring the way enhanced apps works on heimdalljs so you can choose to check on demand.

As for staying logged in, the OMV enhanced app was submitted b a 3rd party so it depends how they built it.
