### ISSUE TITLE
Portainer loging worked once or twice then stopped working

### ISSUE THREAD

**Issue by robvdl** [linuxserver/Heimdall#665]
I can't figure out why but it just stopped logging in at some point (it worked briefly then just stopped working), always saying "invalid credentials" now, I tried authenticating other users and same thing.

It did work at first, I did see some status information showing on the Portainer button like number of containers running.

Then at some point it just stopped, I checked the config and it's no longer wanting to authenticate at all.

But also I see that portainer has access token support, I am wondering shouldn't it be using access tokens instead of username/password combination??

http://portainer_instance/#!/account/tokens/new

**Comment by robvdl** [comment]
I think this is my own doing. I am running both apps in Docker and I just see there are some notes about that.

Why it worked once or twice I don't know though, but it's something I can go on.

I presume it's the backend that is making the connection, not done via JavaScript on the frontend.

**Comment by robvdl** [comment]
Re-opening because it is not a Docker networking issue. The portainer container is actually using host network port 9000.

I tried pinging that from the heimdall container and it can contact it just fine.

Something is definitely off with the "invalid credentials".

**Comment by robvdl** [comment]
I think I can see the problem: https://github.com/portainer/portainer/issues/3092

If you keep reading on for a while, it says that it has a rate limiter and will ban IPs.

Could be related to the other issue I raised here: #664 which showed that it was slamming openmediavault with 800 login requests, my guess is something similar has happened to portainer and that has caused it to ban Heimdall.

I see that Heimdall is doing lots of little requests (so it's not using websockets), therefore every single request is possibly logging in and not utilising sessions. If that is the case that would be bad as it will just slam the login endpoint.

**Comment by KodeStar** [comment]
Turn off the enhanced part for now, I'm looking at transferring the way enhanced apps works on heimdalljs so you can choose to check on demand.

**Comment by pops199** [comment]
The problem you are facing is the fact that portainer's got an rate limiter on the authentication,  which is 1 login a second per ip that tightens further if ongoing incorrect attempts, they never ban it totally though.

One way to get past this, is to restart your portainer container:
`sudo docker restart portainer`
or you can go to settings and change the authentication from the default 8 hours to 1 year and see if that makes a difference.

**Comment by robvdl** [comment]
NO NO NO the issue isn't that portainer is doing rate limiting. The issue is that the way Heimdall is written is not right. It should hold the session open rather than login over and over and over and over and over again.

For example I have the exact same issue when Heimdall logs into OpenMediaVault it sends an email. The issue within 10 minutes it sent out almost a THOUSAND emails. And you can't stop OpenMediaVault from emailing every time you log in.

The issue is that Heimdall should log in ONCE and then retain that session.

**Comment by aptalca** [comment]
The api integrations are community supported. Feel free to submit a PR.

PS. Iirc the `enhanced` functionality was designed to make api calls, not log in or maintain a session.

**Comment by robvdl** [comment]
> The api integrations are community supported. Feel free to submit a PR.
> 
> PS. Iirc the `enhanced` functionality was designed to make api calls, not log in or maintain a session.

I would but last time I bought this up, I got the message Heimdall was going through some internal redesign to allow for this, so I held off and turned off any enhanced apps since.
