### ISSUE TITLE
OpenMediaVault - once you have ticked autoupdate you can't untick it anymore

### ISSUE THREAD

**Issue by robvdl** [linuxserver/Heimdall#666]
First of all you need to tick "enable" under Config (optional) and put in a username and password.

There are two issues here:

1. If you untick "enable" and try to save, it will end up saving a blank username and password as well. This will cause AJAX requests to keep raising a 500 in the background
2. If you until "enable" and fill in a password and username, then save. You won't get errors, but it will not "disable" the auto updating either. Going in there again shows it hasn't saved anything.

It seems removing the OpenMediaVault widget entirely and re-adding it fixes it.

However this should not be necessary, my experience with the OpenMediaVault plugin was that it seemed quite buggy.

**Comment by KodeStar** [comment]
Have a look for the author of the plugin on https://github.com/linuxserver/Heimdall-Apps/

**Comment by robvdl** [comment]
Ah sorry I didn't realise the apps had their own Github. Thanks.
