### ISSUE TITLE
SupportedApp -  Graylog

### ISSUE THREAD

**Issue by bassrock** [linuxserver/Heimdall#70]
Just a request to add Graylog as a foundation or enhanced app.

**Comment by skluthe** [comment]
@KodeStar Found some logos that could fit the bill. Let me know which one is better.
![graylog logo2](https://user-images.githubusercontent.com/23664304/36228612-813005a6-1189-11e8-8f2f-e8ed9df19b23.png)
![graylog logo](https://user-images.githubusercontent.com/23664304/36228614-829fd312-1189-11e8-87ea-4b3c495a611a.png)

**Comment by KodeStar** [comment]
the circle one would fit in the space better
