### ISSUE TITLE
SupportedApp - TT-RSS

### ISSUE THREAD

**Issue by Attoy** [linuxserver/Heimdall#72]
I hope this is the right way to ask to add a foundation app. I'd like to have ttrss added ( more information on https://tt-rss.org/ ).

tt-rss is an open source web-based news feed (RSS/Atom) reader and aggregator, designed to allow you to read news from any location, while feeling as close to a real desktop application as possible.

**Comment by KodeStar** [comment]
Perfect place to ask Attoy :) thanks

**Comment by Attoy** [comment]
Awesome! Thanks @KodeStar 

On a completely unrelated note I see you accepted my PR for the italian translation and well, thanks! This was my very first PR and I was really scared to make a mistake!
