### ISSUE TITLE
Dashboard Links not working

### ISSUE THREAD

**Issue by hrabosky** [linuxserver/Heimdall#75]
I learned you have to specify the http:// before your internal urls.

if I have plex at 192.168.1.4:32400

my url for the dashboard should read

http://192.168.1.4:32400 otherwise it will open a blank page.

**Comment by skluthe** [comment]
Could have http:// or https:// pre-filled? Just a quick fix.

**Comment by KodeStar** [comment]
yeah, I'll probably do something to validate the url
