### ISSUE TITLE
Tags list Issue

### ISSUE THREAD

**Issue by deejayexe** [linuxserver/Heimdall#763]
Hi

With last update (v. 2.3.1) for tag list page it redirect to localhost -> http://localhost/tag/special-k

I test my heimdall site and all tag page redirect to localhost from my domain, must be https://domain.com/tag/1234 but now is http://localhost/tag/1234

Thanks

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Are you using the Docker container from LSIO or running it natively, @deejayexe [deejayexe](https://github.com/deejayexe)?  I had flagged the same [issue](https://github.com/linuxserver/docker-heimdall/issues/95) on the Docker Container GitHub, but am not sure where the issue lies.

**Comment by deejayexe** [comment]
> Are you using the Docker container from LSIO or running it natively, [deejayexe](https://github.com/deejayexe)? I had flagged the same [issue](https://github.com/linuxserver/docker-heimdall/issues/95) on the Docker Container GitHub, but am not sure where the issue lies.

From lsio

**Comment by deejayexe** [comment]
From docker lsio in last update

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Temporary workaround found in the above-link to the docker container issue.
