### ISSUE TITLE
Illuminate \ View \ ViewException (E_ERROR)

### ISSUE THREAD

**Issue by thom-arne** [linuxserver/Heimdall#766]
This error occurs when I try to edit Portainer application in list.

Illuminate\View\ViewException thrown with message "htmlspecialchars() expects parameter 1 to be string, array given (View: /config/www/SupportedApps/Portainer/config.blade.php) (View: /config/www/SupportedApps/Portainer/config.blade.php) (View: /config/www/SupportedApps/Portainer/config.blade.php)"

**Comment by mzlumin** [comment]
Same here:


/var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Support/helpers.php
 

Arguments
"htmlspecialchars() expects parameter 1 to be string, array given (View: /config/www/SupportedApps/Portainer/config.blade.php) (View: /config/www/SupportedApps/Portainer/config.blade.php) (View: /config/www/SupportedApps/Portainer/config.blade.php) ◀

**Comment by KodeStar** [comment]
Unfortunately I don't use portainer nor did I create the portainer app so it's hard to say. Your best bet for now is to delete the portainer app and add it again. If you want to pop on discord I can try and troubleshoot it with you, as the information provided isn't really enough to do anything about it.

**Comment by KodeStar** [comment]
Try clicking the `Update Apps List` button, I think i found the issue and resolved it.
