### ISSUE TITLE
2.3.2 lost edit for portainer applications

### ISSUE THREAD

**Issue by NIghtHawkATL** [linuxserver/Heimdall#767]
I have been updating and downgrading all weekend and finally decided to grab the latest as the update notifications stopped. Now when I try to edit a portainer application I get a screen full of code.

Latest image is: sha256:4d25478a77dd6ae34d97fce05dfa511104e5a98da413217f278f920eee23b4b5
Version 2.3.2 as of this morning.

**Comment by mzlumin** [comment]
Same here:

Arguments
"htmlspecialchars() expects parameter 1 to be string, array given (View: /config/www/SupportedApps/Portainer/config.blade.php) (View: /config/www/SupportedApps/Portainer/config.blade.php) (View: /config/www/SupportedApps/Portainer/config.blade.php) ◀"

**Comment by KodeStar** [comment]
Try clicking the `Update Apps List` button, I think i found the issue and resolved it.

**Comment by NIghtHawkATL** [comment]
> Try clicking the `Update Apps List` button, I think i found the issue and resolved it.

That didn't work fpr me and I have provided what I see when I try to edit in the image above.

**Comment by KodeStar** [comment]
You might need to delete it and re-add it if update apps list didn't work, I can't see anything that would explain it and I believe Updating the apps list has worked for some people
