### ISSUE TITLE
Newly added apps with Application Type = "None" do not show

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [linuxserver/Heimdall#771]
Hi!

Thanks for your great app!

Heimdall recently updated and it seems a bug has been introduced when adding an app without a pre-made type.  If I create one, leave application type as "none", and fill in the details including its tag, the application will not appear on the appropriate page.  Using browser "find" gets a hit for the text, but no bubble or visible text.

I looked at the page source, and it seems that the issue is the "class" tag (in the 'pinlist' section)  is left blank, which hides the new app.  For example:

**Working app:**
`<li>Code Server<a class="active" data-tag="24" data-id="48" href="REMOVED"><i class="fas fa-thumbtack"></i></a></li>`

**Not working:**
`<li>aatest3<a class="" data-tag="24" data-id="53" href="REMOVED"><i class="fas fa-thumbtack"></i></a></li>`

However, if I create an app with a dummy application type (eg Ad miner), it will be properly added.  I can then change the application type back to 'none' and it works as expected.

**Comment by KodeStar** [comment]
Check the top right of the app edit page, if you don't select an application it doesn't automatically get pinned. It's always worked this way though. If I'm misunderstanding your issue please reopen and try to take me through it step by step, or hop on the discord.
