### ISSUE TITLE
On item/ edit screen, elements (Preview, Home dashboard) are not translated

### ISSUE THREAD

**Issue by xavier-GitHub76** [linuxserver/Heimdall#772]
Hello,
firstly, thanks for you job.

Version installed with Docker :  2.3.2
![image](https://user-images.githubusercontent.com/82046143/158659455-ddca524b-7dae-4a21-9414-0e74bea38c88.png)

On screen « Item / Edit », following items are not translated
    • Preview
    • Home dashboard
although the elements are present in the file \resources\lang\fr\app.php :
    • 'apps.preview' => 'Aperçu',
    • 'dashboard' => 'Tableau de bord',
![image](https://user-images.githubusercontent.com/82046143/158659489-3233af3c-00af-4543-b7f7-e227c94a85c5.png)

Best regards

**Comment by KodeStar** [comment]
Preview should be fixed in 2.4.0, not sure about Home Dashboard though, I can't see any issues there.

**Comment by KodeStar** [comment]
This should be fixed in 2.4.0

**Comment by xavier-GitHub76** [comment]
Thanks for your response
