### ISSUE TITLE
APP.APPS.AUTOLOGIN_URL : not possible to translate it

### ISSUE THREAD

**Issue by xavier-GitHub76** [linuxserver/Heimdall#773]
Hello,
On the "users" screen the column APP.APPS.AUTOLOGIN_URL has no entry in the app.php file (in English or French). It is therefore not possible to translate it.
![image](https://user-images.githubusercontent.com/82046143/158660168-6e437c9c-59c8-4e34-aa00-1e993b8c6ec2.png)
Best regards

**Comment by KodeStar** [comment]
Added to the english file in 2.4.0, feel free to PR a french version
