### ISSUE TITLE
items trash : Element "Showing deleted applications" can't be translated

### ISSUE THREAD

**Issue by xavier-GitHub76** [linuxserver/Heimdall#774]
Hello,

On the "/items?trash=1" screen the title "Showing deleted applications" has no entry in the app.php file (in English or French). It is therefore not possible to translate it.
![image](https://user-images.githubusercontent.com/82046143/158672863-76044cb2-9c47-40cb-8199-7c222d0627ae.png)

Best regards

**Comment by KodeStar** [comment]
English version fixed in 2.4.0, feel free to PR a french version, thanks.
