### ISSUE TITLE
On screen « Items », the alert "Updating apps list" is not translated

### ISSUE THREAD

**Issue by xavier-GitHub76** [linuxserver/Heimdall#776]
Hello,
firstly, thanks for you job.

Version installed with Docker : 2.3.2
![image](https://user-images.githubusercontent.com/82046143/158674413-ccd31323-89e2-446d-8074-f0aa42c2d59c.png)

On screen « Items », the alert "Updating apps list" is not translated
although the element is present in the file \resources\lang\fr\app.php :
'alert.success.updating' => 'Liste des applications mise à jour avec succès'

![image](https://user-images.githubusercontent.com/82046143/158674683-dee18309-74fe-4267-9b29-637efc1d6b5f.png)

Best regards

**Comment by KodeStar** [comment]
Fixed in 2.4.0
