### ISSUE TITLE
SupportedApp - OPNSense

### ISSUE THREAD

**Issue by skluthe** [linuxserver/Heimdall#78]
Since you already have PFSense I think OPNSense would be a good addition.

**Comment by KodeStar** [comment]
Struggling to find a 250 x 250px transparent png for this but will add it to the list

**Comment by skluthe** [comment]
![opnsenselogo](https://user-images.githubusercontent.com/23664304/36225509-be167464-117f-11e8-9bfc-cba7acd889c5.png)

**Comment by skluthe** [comment]
It's not as detailed as the main logo but it's what I was able to make. I've got the .ai file so I can modify it if there's an issue.

**Comment by KodeStar** [comment]
:D perfect, thanks
