### ISSUE TITLE
Error Class 'Illuminate\Notifications\NexmoChannelServiceProvider' not found

### ISSUE THREAD

**Issue by zell-mbc** [linuxserver/Heimdall#781]
First of all, let me say thank you for this tool! It's simple to use and does it's job.

I have just upgraded to the latest version and now am stuck with this error?

/**
     * Resolve a service provider instance from the class name.
     *
     * @param  string  $provider
     * @return \Illuminate\Support\ServiceProvider
     */
    public function resolveProvider($provider)
    {
        return new $provider($this);
    }

**Comment by KodeStar** [comment]
Are you using Nexmo?

**Comment by zell-mbc** [comment]
No, Nexmo and no Artison. Unless they get installed by something else?
I tried to revert with pulling v2.2.3 (I think), but that one came up with the same error, looks like the upgrade changed the config/db

I ended up restoring a backup and things are up and running again. 
Anything wrong with this report given that you closed it a day after posting?

**Comment by KodeStar** [comment]
I closed it because not much information was given and there were no replies to my questions. In order to figure it out I would probably need a copy of your database and maybe your .env, to try and work out why it was generating that error.

I don’t think I’m currently doing anything with notifications so I’m not sure if you changed something manually at some point in the past which is causing it but as far as I know you are the only person that has encountered it so far.

If you want to supply more details I’m happy to reopen it, but as you said, you resolved it by restoring a backup.

**Comment by zell-mbc** [comment]
Well, it's resolved by downgrading to v2.2.3 via restoring a backup, I guess I can break it again by upgrading to the current release.
I would say my setup is pretty basic, a bunch of apps and notifications via email, that's it.
I can try to upgrade/break it again if there is interest in troubleshooting…

**Comment by KodeStar** [comment]
Sure, I've been unable to replicate it so if you can come up with any further insights I'd be happy to try and work it out.

**Comment by zell-mbc** [comment]
Allright, here's the steps I took:
Made sure the v2.2.2. image is gone:
`docker-compose down --rmi all`

Changed version in docker-compose.yml to latest and restarted:
```docker-compose up
root@support:/opt/docker/heimdall# docker-compose up
WARNING: The password variable is not set. Defaulting to a blank string.
Creating network "heimdall_default" with the default driver
Pulling heimdall (ghcr.io/linuxserver/heimdall:latest)...
latest: Pulling from linuxserver/heimdall
bc63304feaf3: Pull complete
dcc0a30d9368: Pull complete
95b666618ca3: Pull complete
3cf2aab38cc4: Pull complete
f70c27464424: Pull complete
6e0c137e4d32: Pull complete
26cf139db356: Pull complete
607fc1049472: Pull complete
58d31d9469eb: Pull complete
5edd946b3793: Pull complete
Digest: sha256:dd054106ab49c5015989a222fc4202afb450ea72bd2886538aede2cad55e0541
Status: Downloaded newer image for ghcr.io/linuxserver/heimdall:latest
Creating heimdall ... done
Attaching to heimdall
heimdall    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
heimdall    | [s6-init] ensuring user provided files have correct perms...exited 0.
heimdall    | [fix-attrs.d] applying ownership & permissions fixes...
heimdall    | [fix-attrs.d] done.
heimdall    | [cont-init.d] executing container initialization scripts...
heimdall    | [cont-init.d] 01-envfile: executing... 
heimdall    | [cont-init.d] 01-envfile: exited 0.
heimdall    | [cont-init.d] 02-tamper-check: executing... 
heimdall    | [cont-init.d] 02-tamper-check: exited 0.
heimdall    | [cont-init.d] 10-adduser: executing... 
heimdall    | 
heimdall    | -------------------------------------
heimdall    |           _         ()
heimdall    |          | |  ___   _    __
heimdall    |          | | / __| | |  /  \
heimdall    |          | | \__ \ | | | () |
heimdall    |          |_| |___/ |_|  \__/
heimdall    | 
heimdall    | 
heimdall    | Brought to you by linuxserver.io
heimdall    | -------------------------------------
heimdall    | 
heimdall    | To support LSIO projects visit:
heimdall    | https://www.linuxserver.io/donate/
heimdall    | -------------------------------------
heimdall    | GID/UID
heimdall    | -------------------------------------
heimdall    | 
heimdall    | User uid:    1000
heimdall    | User gid:    1000
heimdall    | -------------------------------------
heimdall    | 
heimdall    | [cont-init.d] 10-adduser: exited 0.
heimdall    | [cont-init.d] 20-config: executing... 
heimdall    | [cont-init.d] 20-config: exited 0.
heimdall    | [cont-init.d] 30-keygen: executing... 
heimdall    | using keys found in /config/keys
heimdall    | [cont-init.d] 30-keygen: exited 0.
heimdall    | [cont-init.d] 50-config: executing... 
heimdall    | New container detected, installing Heimdall
heimdall    | Setting permissions
heimdall    | [cont-init.d] 50-config: exited 0.
heimdall    | [cont-init.d] 90-custom-folders: executing... 
heimdall    | [cont-init.d] 90-custom-folders: exited 0.
heimdall    | [cont-init.d] 99-custom-files: executing... 
heimdall    | [custom-init] no custom files found exiting...
heimdall    | [cont-init.d] 99-custom-files: exited 0.
heimdall    | [cont-init.d] done.
heimdall    | [services.d] starting services
heimdall    | [services.d] done.
heimdall    | 
heimdall    | In Application.php line 690:
heimdall    |                                                                           
heimdall    |   Class 'Illuminate\Notifications\NexmoChannelServiceProvider' not found  
heimdall    |                                                                           
heimdall    | 
heimdall    | 
heimdall    | In Application.php line 690:
heimdall    |                                                                           
heimdall    |   Class 'Illuminate\Notifications\NexmoChannelServiceProvider' not found  
heimdall    |                                                                           
heimdall    | 
heimdall    | 
heimdall    | In Application.php line 690:
heimdall    |                                                                           
heimdall    |   Class 'Illuminate\Notifications\NexmoChannelServiceProvider' not found  
…
```

The php error shows up multiple times. 

I didn't notice this error in the docker log last time because I focused on the UI (below) and then quickly reverted to the backup to get the service up and running again. But most likely it was there last time too.

![image](https://user-images.githubusercontent.com/29018767/159220195-055cf3d0-6e2b-49e7-92ab-0fa68a7ffbd4.png)

**Comment by martadinata666** [comment]
> Well, it's resolved by downgrading to v2.2.3 via restoring a backup, I guess I can break it again by upgrading to the current release. I would say my setup is pretty basic, a bunch of apps and notifications via email, that's it. I can try to upgrade/break it again if there is interest in troubleshooting…

more detail on this? As it requested vonex/nexmo, i assume the notification looking that libs? 

So one thing i can guess it, on 2.2.3 the lib exist, and on 2.4.0 upgrade as the laravel upgraded, some lib become obsolete and not available.

**Comment by zell-mbc** [comment]
> more detail on this? As it requested vonex/nexmo, i assume the notification looking that libs?

I honestly have no idea where this nexmo thing is coming from, I am not running this app. Is there a config file I can provide which would help with narrowing down whats going on?

**Comment by martadinata666** [comment]
> Allright, here's the steps I took: Made sure the v2.2.2. image is gone: `docker-compose down --rmi all`
> 
> Changed version in docker-compose.yml to latest and restarted:
> 
> ```
> root@support:/opt/docker/heimdall# docker-compose up
> WARNING: The password variable is not set. Defaulting to a blank string.
> Creating network "heimdall_default" with the default driver
> Pulling heimdall (ghcr.io/linuxserver/heimdall:latest)...
> latest: Pulling from linuxserver/heimdall
> bc63304feaf3: Pull complete
> dcc0a30d9368: Pull complete
> 95b666618ca3: Pull complete
> 3cf2aab38cc4: Pull complete
> f70c27464424: Pull complete
> 6e0c137e4d32: Pull complete
> 26cf139db356: Pull complete
> 607fc1049472: Pull complete
> 58d31d9469eb: Pull complete
> 5edd946b3793: Pull complete
> Digest: sha256:dd054106ab49c5015989a222fc4202afb450ea72bd2886538aede2cad55e0541
> Status: Downloaded newer image for ghcr.io/linuxserver/heimdall:latest
> Creating heimdall ... done
> Attaching to heimdall
> heimdall    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> heimdall    | [s6-init] ensuring user provided files have correct perms...exited 0.
> heimdall    | [fix-attrs.d] applying ownership & permissions fixes...
> heimdall    | [fix-attrs.d] done.
> heimdall    | [cont-init.d] executing container initialization scripts...
> heimdall    | [cont-init.d] 01-envfile: executing... 
> heimdall    | [cont-init.d] 01-envfile: exited 0.
> heimdall    | [cont-init.d] 02-tamper-check: executing... 
> heimdall    | [cont-init.d] 02-tamper-check: exited 0.
> heimdall    | [cont-init.d] 10-adduser: executing... 
> heimdall    | 
> heimdall    | -------------------------------------
> heimdall    |           _         ()
> heimdall    |          | |  ___   _    __
> heimdall    |          | | / __| | |  /  \
> heimdall    |          | | \__ \ | | | () |
> heimdall    |          |_| |___/ |_|  \__/
> heimdall    | 
> heimdall    | 
> heimdall    | Brought to you by linuxserver.io
> heimdall    | -------------------------------------
> heimdall    | 
> heimdall    | To support LSIO projects visit:
> heimdall    | https://www.linuxserver.io/donate/
> heimdall    | -------------------------------------
> heimdall    | GID/UID
> heimdall    | -------------------------------------
> heimdall    | 
> heimdall    | User uid:    1000
> heimdall    | User gid:    1000
> heimdall    | -------------------------------------
> heimdall    | 
> heimdall    | [cont-init.d] 10-adduser: exited 0.
> heimdall    | [cont-init.d] 20-config: executing... 
> heimdall    | [cont-init.d] 20-config: exited 0.
> heimdall    | [cont-init.d] 30-keygen: executing... 
> heimdall    | using keys found in /config/keys
> heimdall    | [cont-init.d] 30-keygen: exited 0.
> heimdall    | [cont-init.d] 50-config: executing... 
> heimdall    | New container detected, installing Heimdall
> heimdall    | Setting permissions
> heimdall    | [cont-init.d] 50-config: exited 0.
> heimdall    | [cont-init.d] 90-custom-folders: executing... 
> heimdall    | [cont-init.d] 90-custom-folders: exited 0.
> heimdall    | [cont-init.d] 99-custom-files: executing... 
> heimdall    | [custom-init] no custom files found exiting...
> heimdall    | [cont-init.d] 99-custom-files: exited 0.
> heimdall    | [cont-init.d] done.
> heimdall    | [services.d] starting services
> heimdall    | [services.d] done.
> heimdall    | 
> heimdall    | In Application.php line 690:
> heimdall    |                                                                           
> heimdall    |   Class 'Illuminate\Notifications\NexmoChannelServiceProvider' not found  
> heimdall    |                                                                           
> heimdall    | 
> heimdall    | 
> heimdall    | In Application.php line 690:
> heimdall    |                                                                           
> heimdall    |   Class 'Illuminate\Notifications\NexmoChannelServiceProvider' not found  
> heimdall    |                                                                           
> heimdall    | 
> heimdall    | 
> heimdall    | In Application.php line 690:
> heimdall    |                                                                           
> heimdall    |   Class 'Illuminate\Notifications\NexmoChannelServiceProvider' not found  
> …
> ```
> 
> The php error shows up multiple times.
> 
> I didn't notice this error in the docker log last time because I focused on the UI (below) and then quickly reverted to the backup to get the service up and running again. But most likely it was there last time too.
> 
> ![image](https://user-images.githubusercontent.com/29018767/159220195-055cf3d0-6e2b-49e7-92ab-0fa68a7ffbd4.png)

When you run this, is it using your modified env ? or a clean setup? This is my env, let it compare to yours. 
```
APP_NAME=Heimdall
APP_ENV=local
APP_KEY=base64:YChmnQqrptpoztAU0Fik2Y3bt8zhC3rC+tFlR7+8SZs=
APP_DEBUG=true
APP_LOG_LEVEL=error
APP_URL=http://localhost

#DB_CONNECTION=mysql
#DB_HOST=db
#DB_PORT=3306
#DB_DATABASE=heimdall
#DB_USERNAME=heimdall
#DB_PASSWORD=heimdallpass

#DB_CONNECTION=sqlite
#DB_DATABASE=app.sqlite

DB_CONNECTION=pgsql
DB_HOST=db
DB_PORT=5432
DB_DATABASE=heimdall
DB_USERNAME=heimdall
DB_PASSWORD=heimdallpass

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120
QUEUE_DRIVER=sync
QUEUE_CONNECTION=sync

REDIS_HOST=rd
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

```

**Comment by zell-mbc** [comment]
Where can I find this env file? It's not in my config folder, so I guess it's inside the docker image?
I guess what I am saying is that I didn't make any changes to it because I didn't know it exists.
I set some environment vars in the docker-compose file though:

```
version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall:2.2.2
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/LOndon
      - PASSWORD=${password}
    volumes:
      - ./config:/config
      - ./www:/var/www/localhost/heimdall
    ports:
      - 90:80
    restart: unless-stopped
```

I just noticed the typo in the timezone, will change that once we figured out what's going on.

**Comment by martadinata666** [comment]
> 

why you override to web root? , the env at `./config/www/.env` like yours override the dir maybe `./www/.env`

**Comment by zell-mbc** [comment]
> why you override to web root?

I didn't do that on purpose, I went with the sample docker-compose.yml I picked up when installing Heimdall for the first time. I don't remember any longer but would guess from your documentation?

Found the .env, the one in ./www points to ./config/www:

```
cat config/www/.env
APP_NAME=Heimdall
APP_ENV=local
APP_KEY=base64:UCEpZhneowzbS1lwyci7EAxkTLgawa9DPhiOwk1B338=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=sqlite
DB_DATABASE=app.sqlite

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=database

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1```

**Comment by martadinata666** [comment]
then you could do like this, copy out `app.sqlite` and `.env` , wipe the ./config path redeploy again from clean path config, and paste back the `.env` and `app.sqlite`. 
Database path should be `./config/www/database/app.sqlite`

**Comment by zell-mbc** [comment]
That did the trick!
I seem to have lost the icons for the services, but that's ok, that's easy to recreate.

Thanks for your help.

**Comment by KodeStar** [comment]
if you hit the `update apps list` button it should pull back in the icons unless they were custom icons

**Comment by zell-mbc** [comment]
I had to also switch to another service type and back to make the icons reappear, but everything is working now.
