### ISSUE TITLE
500 error /items/create

### ISSUE THREAD

**Issue by emfoursolutions** [linuxserver/Heimdall#784]
I just installed 2.4.3 and whenever I try to add an app I get a 500 error. 

OS: Rocky Linux 8
PHP: 8.0.16
Apache

This is the debug output

Illuminate \ View \ ViewException (E_ERROR)
Attempt to read property "apps" on array (View: /var/www/html/resources/views/items/form.blade.php) (View: /var/www/html/resources/views/items/form.blade.php)
Previous exceptions
Attempt to read property "apps" on array (View: /var/www/html/resources/views/items/form.blade.php) (0)
Attempt to read property "apps" on array (0)

I've checked file permissions etc.. everything seems good. 

This is an install without docker with my Vhost pointing to the public folder in the heimdall directory. 

Any ideas?

By the way, I love the app. I upgraded my webserver to PHP 8 a little while ago without realising 2.2 wasn't compatible. I've tried all the alternatives and none could beat heimdall for simplicity, looks, and functionality. So I was stoked when you released these newer versions I just hope I can get it to work.

**Comment by mmagidson** [comment]
Same issue with Synology DSM 6.2.4-25556 Update 5...I've been yelling at my computer for over an hour.

**Comment by KodeStar** [comment]
Sorry guys, this was an issue with the appslist on github, an apps icon had been updated without updating the apps.json which resulted in it failing to build the list entirely. The code should now build the list anyway if it happens in the future.
