### ISSUE TITLE
Trying to get property 'apps' of non-object (View: /var/www/localhost/heimdall/resources/views/items/form.blade.php) (View: /var/www/localhost/heimdall/resources/views/items/form.blade.php)

### ISSUE THREAD

**Issue by ottoking8912** [linuxserver/Heimdall#785]
Using latest Versin 2.4.3 and I'm getting these kind of errors if I try to update an existing entry or even if I click on 'Add' in the application list. No matter what, it always errors out. Any idea? Happy to provide any information regarding this issue....

**Comment by KodeStar** [comment]
Try it again, there was an issue with the apps list

**Comment by ottoking8912** [comment]
Recreated the container now it's working! Thx!

**Comment by KodeStar** [comment]
Awesome :)
