### ISSUE TITLE
Apps not showing on dash

### ISSUE THREAD

**Issue by emfoursolutions** [linuxserver/Heimdall#786]
Now that the adding of apps works with 2.4.3, the apps I add don't seem to show on the dash. 

They're definitely in the DB as I can bring up the list of apps. But when I try and pin them it doesn't seem to work. When I click Pin an item to the dash, there's no apps listed. But when I bring up the app list from the button in the bottom right they're there. 

I'm not getting any errors thrown with debug on either so I'm not sure I can provide any further info. 

PHP 8
Apache
And an install without Docker and my Vhose pointing to /public

**Comment by KodeStar** [comment]
This should have been fixed in 2.4.4 I noticed that the home dashboard tag wasn't being set by default. To fix your current ones, go into it and select the Home dashboard tag.
