### ISSUE TITLE
application type request: uptime kuma

### ISSUE THREAD

**Issue by magnus919** [linuxserver/Heimdall#791]
The [Uptime Kuma](https://github.com/louislam/uptime-kuma) application would make a fine addition to the Heimdall application types supported.

**Comment by magnus919** [comment]
Nevermind. I did an app pull and it showed up.

**Comment by Vansmak** [comment]
> Nevermind. I did an app pull and it showed up.

really?  i dont see it

**Comment by PrzemekSkw** [comment]
It will be great to have Uptime-Kuma status in Heimdall.
