### ISSUE TITLE
Add chinese language option in system

### ISSUE THREAD

**Issue by louielong** [linuxserver/Heimdall#801]
I see that Chinese translations have been merged into the repository, but there is no Chinese option in the system settings language options column, please add Chinese language options.

Thank you!

[language_options](https://github.com/linuxserver/Heimdall/blob/f2bfc26c5e537c322008fdc019e03a32a6153f62/database/seeds/SettingsSeeder.php#L123-L135)

[Chinese translation PR](https://github.com/linuxserver/Heimdall/pull/558)

**Comment by KodeStar** [comment]
It should be in the next release as it was merged in this PR https://github.com/linuxserver/Heimdall/pull/794

**Comment by louielong** [comment]
Nice.
I'm looking forward to the next release.
