### ISSUE TITLE
Issue with adding some Foundations / Enhanced apps

### ISSUE THREAD

**Issue by meme1337** [linuxserver/Heimdall#807]
It seems that some apps are not working for me: I see a zip downloaded, but it's corrupt if I try to unzip it.
If I manually copy it to the `SupportedApps` folder then it works 90% of time, but some apps still give issues, like `Firefly 3`

```shell
/var/www/localhost/heimdall# php artisan register:app Firefly

In SupportedApps.php line 165:
                                                          
  Class '\App\SupportedApps\Firefly3\Firefly3' not found  
```

If I rename the folder to Firefly3 I get another different error.

I've installed Heimdall on docker.

**Comment by KodeStar** [comment]
Ugh, this is a bit of an annoying problem, newer versions allowed numbers in the class names, whereas older versions stripped them out. The class is determined from the name, so it's now returning Firefly3 where before it would have returned Firefly, but the app was submitted before that was allowed, or the code on the request system still strips out numbers (or both). I'll have to think how best to fix this.

**Comment by KodeStar** [comment]
I've updated the Firefly 3 app and it seems to work, but it will need to be done on a case by case basis.

**Comment by meme1337** [comment]
Thank you so much for your quick fix! Just tried and it worked out of the box, without me downloading the zip. 

I’ll close the issue then, thank you so much!

just FYI the apps I had to handle manually were uptime-kuma and prowlarr. 

Thank you!
