### ISSUE TITLE
Add icon for ArgoCD

### ISSUE THREAD

**Issue by lknite** [linuxserver/Heimdall#808]
When I added Harbor, Plex and others the application was found and a nice icon was displayed.

If you take requests I'd like to make a request to have ArgoCD added.  If it'd be better for me to alter the source code could you give me some initial direction and I'll look into it.

https://argo-cd.readthedocs.io/en/stable/

**Comment by lknite** [comment]
<img width="84" alt="argocd" src="https://user-images.githubusercontent.com/92187614/160266603-ac865979-8490-44ad-90b0-2e07c427e130.png">

**Comment by KodeStar** [comment]
https://apps.heimdall.site/request/create
