### ISSUE TITLE
Pihole enhanced not working on docker container

### ISSUE THREAD

**Issue by mrquatsch** [linuxserver/Heimdall#81]
Running in docker on my Synology. I can't seem to get the enhanced logging function for Pihole working. The API test comes back fine and I see the appropriate values returned when I hit my pihole /admin/api.php endpoint.

`{"domains_being_blocked":118253,"dns_queries_today":1649,"ads_blocked_today":124,"ads_percentage_today":7.519709,"unique_domains":489,"queries_forwarded":537,"queries_cached":988,"clients_ever_seen":11,"unique_clients":11,"status":"enabled"}`

I've entered the Hostname correctly - I receive the suggested "Pihole". I also see the "Config (Optional)" at the bottom of the application config. I have that enabled and the test returns successful.

Any ideas why this doesn't populate when I load the Heimdall UI? 

I also seem to have the same problem with Sabnzbd. I just haven't dived into what and where it pulls those values. 

I'm also running the docker tag 20 - linuxserver/heimdall:latest.

`docker inspect -f '{{ index .Config.Labels "build_version" }}' linuxserver/heimdall
Linuxserver.io version:- 20 Build-date:- February-12-2018-15:59:22-UTC`

I've tried in Firefox, Safari and Chrome. Nothing. 

Any ideas what's wrong on my end? Is this a known problem? Is there something else I should check/validate?

**Comment by KodeStar** [comment]
What url are you using? If http://IPADDRES:PORT/admin/ try http://IPADDRES:PORT/ instead.

**Comment by mrquatsch** [comment]
Using http://[ip address]:[port] works to display the enhanced stats, but now my link is broken - I want it to load http://[ip address]:[port]/admin; which is what I had configured previously.

**Comment by mrquatsch** [comment]
Would it be possible to update the Pihole.php to exclude 'admin/' from the api_url?

From:
`$api_url = $url.'admin/api.php';`
To:
`$api_url = $url.'api.php';`

I manually modified the file on my end. Now the stats and the URL load fine.

**Comment by KodeStar** [comment]
Sure, I don't personally use Pihole, so if that is the right way to do it I'll follow your recommendation.  I'll add it to master and it will be in the next release.

**Comment by seffyroff** [comment]
FYI in order for me to get the enhanced stats to display at all I had to set the additional config url to http://<hostaddress>/admin/api.php.

It's probably my own fault, some sort of misconfiguration with my pi-hole container.  :/

**Comment by d-rez** [comment]
> It's probably my own fault, some sort of misconfiguration with my pi-hole container. :/

Nope, I run pihole on a separate raspberry pi and I had the same problems as described in this thread. 

Setting `http://pi.hole/admin/api.php` in the additional config URL was the only thing that worked. Thanks

**Comment by dmdusn** [comment]
> > It's probably my own fault, some sort of misconfiguration with my pi-hole container. :/
> 
> Nope, I run pihole on a separate raspberry pi and I had the same problems as described in this thread.
> 
> Setting `http://pi.hole/admin/api.php` in the additional config URL was the only thing that worked. Thanks

I for the life of me can not get this to work. I've tried every variation that I can think of, and no matter what, when I click test on Pihole config section I get nothing. If I go to http://pi.hole/admin/api.php it pulls up my stats. No problems with Tautulli or Netdata.

**Comment by j0nnymoe** [comment]
Running pihole in a docker container?

**Comment by dmdusn** [comment]
> Running pihole in a docker container?

Yeah, should have added that for clarity. Actually on Unraid. I had read somewhere that you should use the internal Docker IP, but my pihole doesn't use the Docker IP. Setup for Unraid port mappings was to map Pihole to itself. I might try running it in a VM to see if I can get it to work.

**Comment by j0nnymoe** [comment]
If you're giving the pihole container a dedicated IP, Heimdall can't communicate with it due to a security feature in macvlan.

**Comment by dmdusn** [comment]
> If you're giving the pihole container a dedicated IP, Heimdall can't communicate with it due to a security feature in macvlan.

I'm not really sure if there is a way to not give Pihole a dedicated IP in Unraid. I'll move Pihole over to a VM and test it out.

**Comment by ericfrederich** [comment]
@dmdusn I run pihole inside an Unraid docker container.  I set the networking type to `br0` and give it a fixed ip.

I can't get the stats to show up either on Heimdall.

Another problem of running pihole as a docker container on Unraid is that Unraid will then not be able to use it itself.  This means if you configure your network's DHCP to use that dockerizd pihole as the DNS you'll have to manually change the DNS settings on Unraid.

Now I have 3 reasons to not run the Pihole as a container on Unraid

- requires manualy configuration of host (Unraid) DNS settings
- Heimdall stats don't work
- When my power goes out and comes back on, a raspberry pi would boot itself; my Unraid server does not

**Comment by dmdusn** [comment]
> @dmdusn I run pihole inside an Unraid docker container. I set the networking type to `br0` and give it a fixed ip.
> 
> I can't get the stats to show up either on Heimdall.
> 
> Another problem of running pihole as a docker container on Unraid is that Unraid will then not be able to use it itself. This means if you configure your network's DHCP to use that dockerizd pihole as the DNS you'll have to manually change the DNS settings on Unraid.
> 
> Now I have 3 reasons to not run the Pihole as a container on Unraid
> 
> * requires manualy configuration of host (Unraid) DNS settings
> * Heimdall stats don't work
> * When my power goes out and comes back on, a raspberry pi would boot itself; my Unraid server does not

I ended up just putting it on a spare Qnap I had that I installed Ubuntu on because like J0nnymoe said it's a security feature with macvlan. I had it on a VM for a while, but swapped it to a dedicated device that auto reboots in case if a power outage. I have stats now.

**Comment by blueqwertz** [comment]
> > It's probably my own fault, some sort of misconfiguration with my pi-hole container. :/
> 
> Nope, I run pihole on a separate raspberry pi and I had the same problems as described in this thread.
> 
> Setting `http://pi.hole/admin/api.php` in the additional config URL was the only thing that worked. Thanks

Worked for me too!
