### ISSUE TITLE
Multiuser: Browser does only sometimes remember last selected user

### ISSUE THREAD

**Issue by KOBALTenterprises** [linuxserver/Heimdall#811]
I really enjoy the Multiuser update. However, when I start my browser (chrome) with Heimdall as start page, he sometimes remembers my last selected user. Unfortunately in most cases he switches back to my friends account (not the admin account). 
I tried to figure out, if it has something to do with the cookies, but I did not found a pattern - sometimes he could remember my user after rebooting my device, sometimes not. Or sometimes chrome was closed for a longer period and when I opened it, it was back to the other user (without rebooting the device).
When I manually delete the cookies he switches to the other account.

Any way to fix this?

Thank's a lot!

**Comment by keriati** [comment]
I assume that the session is expiring in the above case and heimdall falls back to the default user that has the setting "Allow public access to front".
In the above case Heimdall works as expected.
I would suggest to extend the default session time as it uses the default value from Laravel.
This can be done in the .env file with the SESSION_LIFETIME variable.
See https://dev.to/techsolutionstuff/how-to-increase-session-lifetime-in-laravel-4fe6
