### ISSUE TITLE
Add Application type -> [any] icons no longer loading, name mot auto-populating 

### ISSUE THREAD

**Issue by Beersteddy** [linuxserver/Heimdall#812]
UNRAID 6.9.2
 Linuxserver container 31/03/2022
 Heimdall version 2.49
 

Added a few new apps -  without any issues.
When tried to add another app without a URL filled up, an error message appeared "The title field is required. The URL field is required."

From now on when selecting `Application type` and choosing for example `TrueNAS`, the icon no longer is loading, also the `Application name` field is not getting auto-populated. 

On the other hand... once a while after clicking different app names, it will randomly populate an icon & name from other apps.

All of this was auto-populated
![image](https://user-images.githubusercontent.com/91010735/160943466-1365dfda-0764-4e9d-94d6-bb00d8a624b3.png)

**Comment by Beersteddy** [comment]
The latest update 31/03/2022 partially fixed the problem.

All of the icons are loading. 
`application name` is getting only once - when choosing `application type` for the first time.
Later on, when changing `application type`, the icon will change according to the new app selected while the `application name` stays the same.

![image](https://user-images.githubusercontent.com/91010735/161297557-550041a5-4fb1-4ee7-ab63-d8448619598f.png)

**Comment by KodeStar** [comment]
That's actually expected, as it only updates the Application name if it's empty.
