### ISSUE TITLE
Getting error when pressing "Update apps list"

### ISSUE THREAD

**Issue by Lipown** [linuxserver/Heimdall#815]
Getting error when pressing "Update apps list". Below is the error. Any Idea how to fix that? I was thinking about docker permisions but i do not think so.

`ErrorException thrown with message "Trying to get property 'appid' of non-object"

Stacktrace:
#65 ErrorException in /var/www/localhost/heimdall/app/Jobs/ProcessApps.php:50
#64 Illuminate\Foundation\Bootstrap\HandleExceptions:handleError in /var/www/localhost/heimdall/app/Jobs/ProcessApps.php:50
#63 App\Jobs\ProcessApps:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
#62 Illuminate\Container\BoundMethod:Illuminate\Container\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/Util.php:37
#61 Illuminate\Container\Util:unwrapIfClosure in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
#60 Illuminate\Container\BoundMethod:callBoundMethod in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
#59 Illuminate\Container\BoundMethod:call in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php:596
#58 Illuminate\Container\Container:call in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:94
#57 Illuminate\Bus\Dispatcher:Illuminate\Bus\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
#56 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#55 Illuminate\Pipeline\Pipeline:then in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:98
#54 Illuminate\Bus\Dispatcher:dispatchNow in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:83
#53 Illuminate\Queue\CallQueuedHandler:Illuminate\Queue\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
#52 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#51 Illuminate\Pipeline\Pipeline:then in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:85
#50 Illuminate\Queue\CallQueuedHandler:dispatchThroughMiddleware in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:59
#49 Illuminate\Queue\CallQueuedHandler:call in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:98
#48 Illuminate\Queue\Jobs\Job:fire in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php:43
#47 Illuminate\Queue\SyncQueue:push in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:182
#46 Illuminate\Bus\Dispatcher:pushCommandToQueue in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:158
#45 Illuminate\Bus\Dispatcher:dispatchToQueue in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:73
#44 Illuminate\Bus\Dispatcher:dispatch in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php:134
#43 Illuminate\Foundation\Bus\PendingDispatch:__destruct in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php:17
#42 App\Jobs\ProcessApps:dispatch in /var/www/localhost/heimdall/app/Http/Controllers/ItemController.php:440
#41 App\Http\Controllers\ItemController:checkAppList in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#40 Illuminate\Routing\Controller:callAction in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
#39 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/Route.php:239
#38 Illuminate\Routing\Route:runController in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/Route.php:196
#37 Illuminate\Routing\Route:run in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/Router.php:685
#36 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/app/Http/Middleware/CheckAllowed.php:47
#34 App\Http\Middleware\CheckAllowed:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#33 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#32 Illuminate\Routing\Middleware\SubstituteBindings:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#31 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78
#30 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#28 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#27 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:116
#26 Illuminate\Session\Middleware\StartSession:handleStatefulRequest in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:62
#25 Illuminate\Session\Middleware\StartSession:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#24 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#23 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#22 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67
#21 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#20 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#19 Illuminate\Pipeline\Pipeline:then in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/Router.php:687
#18 Illuminate\Routing\Router:runRouteWithinStack in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/Router.php:662
#17 Illuminate\Routing\Router:runRoute in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/Router.php:628
#16 Illuminate\Routing\Router:dispatchToRoute in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/Router.php:617
#15 Illuminate\Routing\Router:dispatch in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:165
#14 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/fideloper/proxy/src/TrustProxies.php:57
#12 Fideloper\Proxy\TrustProxies:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#10 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#9 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#8 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#6 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#5 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:63
#4 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
#3 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#2 Illuminate\Pipeline\Pipeline:then in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:140
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:109
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/localhost/heimdall/public/index.php:55
`

**Comment by KodeStar** [comment]
Should be fixed in 2.4.10, reopen if not

**Comment by Lipown** [comment]
Unfortunatelly came to Dashy...
