### ISSUE TITLE
in tags list, link href are wrong

### ISSUE THREAD

**Issue by Tsuna77** [linuxserver/Heimdall#816]
I don't know why but href for my tag is just a concat of current page and real page

![image](https://user-images.githubusercontent.com/3943654/161272195-6ea48eff-6325-4085-916c-58f6391ab6ac.png)

Version used : Docker  v2.4.9-ls166

**Comment by NightDragon1** [comment]
Can Confirm the issue. Same for me. Fresh Install

**Comment by PhilippMundhenk** [comment]
same as #901, maybe fixed in #912
