### ISSUE TITLE
Heimdall starts only with access error

### ISSUE THREAD

**Issue by drdiablo1337** [linuxserver/Heimdall#817]
I always get the following errors on first launch via Docker Container, note the logs with the network bridge log off and on and the different access error message

Logs with deactivated #network_mode: bridge

> cURL error 6: Could not resolve host: appslist.heimdall.site (see https://c  
>   url.haxx.se/libcurl/c/libcurl-errors.html) for https://appslist.heimdall.site/list.json

>   In StreamHandler.php line 146:
>   The stream or file "/var/www/localhost/heimdall/storage/logs/laravel-2022-0  
>   4-02.log" could not be opened in append mode: failed to open stream: Permission denied

Logs with activated network_mode: bridge    

> In CurlFactory.php line 210:
>                                                                                
>   cURL error 6: Could not resolve host: appslist.heimdall.site (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://appslist.heimdall.site/list.json      

  
The whole thing runs on an RPI4-8GB with DietPi-arm64 and there with Docker, Docker-compose and Portainer.

It's my only container that isn't working (15 others are running fine)

I also tested network bridge and host, host does not work due to the port assignment.
Local volume have access for Dietpi user (1000:1000) or for everyone write permissions. Files are also stored.

Does anyone have any ideas what I could check or why?

Stack-Config:

> ---
> version: "2.1"
> services:
>   heimdall:
>     image: ghcr.io/linuxserver/heimdall
>     container_name: heimdall
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - TZ=Europe/Berlin
>     volumes:
>       - /mnt/dietpi_userdata/Docker/heimdall/config:/config
>     ports:
>       - 2000:80
>       - 4000:443
>     restart: unless-stopped
>     #network_mode: bridge
> 

Logs with deactivated #network_mode: bridge

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01-envfile: executing... 
> [cont-init.d] 01-envfile: exited 0.
> [cont-init.d] 02-tamper-check: executing... 
> [cont-init.d] 02-tamper-check: exited 0.
> [cont-init.d] 10-adduser: executing... 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> Brought to you by linuxserver.io
> -------------------------------------
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    1000
> User gid:    1000
> -------------------------------------
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 20-config: executing... 
> [cont-init.d] 20-config: exited 0.
> [cont-init.d] 30-keygen: executing... 
> generating self-signed keys in /config/keys, you can replace these with your own keys if required
> Generating a RSA private key
> ..................+++++
> ......+++++
> writing new private key to '/config/keys/cert.key'
> -----
> [cont-init.d] 30-keygen: exited 0.
> [cont-init.d] 50-config: executing... 
> New container detected, installing Heimdall
> Creating app key. This may take a while on slower systems
> In CurlFactory.php line 210:
>                                                                                
>   cURL error 6: Could not resolve host: appslist.heimdall.site (see https://c  
>   url.haxx.se/libcurl/c/libcurl-errors.html) for https://appslist.heimdall.si  
>   te/list.json                                                                 
>                                                                                
> Setting permissions
> [cont-init.d] 50-config: exited 0.
> [cont-init.d] 90-custom-folders: executing... 
> [cont-init.d] 90-custom-folders: exited 0.
> [cont-init.d] 99-custom-files: executing... 
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-files: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> In StreamHandler.php line 146:
>                                                                                
>   The stream or file "/var/www/localhost/heimdall/storage/logs/laravel-2022-0  
>   4-02.log" could not be opened in append mode: failed to open stream: Permis  
>   sion denied                  

Logs with activated network_mode: bridge                                                

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01-envfile: executing... 
> [cont-init.d] 01-envfile: exited 0.
> [cont-init.d] 02-tamper-check: executing... 
> [cont-init.d] 02-tamper-check: exited 0.
> [cont-init.d] 10-adduser: executing... 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> Brought to you by linuxserver.io
> -------------------------------------
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    1000
> User gid:    1000
> -------------------------------------
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 20-config: executing... 
> [cont-init.d] 20-config: exited 0.
> [cont-init.d] 30-keygen: executing... 
> using keys found in /config/keys
> [cont-init.d] 30-keygen: exited 0.
> [cont-init.d] 50-config: executing... 
> New container detected, installing Heimdall
> Setting permissions
> [cont-init.d] 50-config: exited 0.
> [cont-init.d] 90-custom-folders: executing... 
> [cont-init.d] 90-custom-folders: exited 0.
> [cont-init.d] 99-custom-files: executing... 
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-files: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> 
> In CurlFactory.php line 210:
>                                                                                
>   cURL error 6: Could not resolve host: appslist.heimdall.site (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://appslist.heimdall.site/list.json

**Comment by KodeStar** [comment]
What version are you using?

**Comment by drdiablo1337** [comment]
The current version or "latest".

> ghcr.io/linuxserver/heimdall

I've also tried to force the arm64 version with the same problem.

Which I haven't tested at all, forcing an older version! I can test that again.

**Comment by drdiablo1337** [comment]
I just tested it, up to version `v2.3.1-ls161` it seems to work, all versions after that bring the error messages and the website is not accessible `"Error 500"`

The only errors I have with the "older" versions are the following:

> [2022-04-02 16:48:10][12] Processing: App\Jobs\ProcessApps
> [2022-04-02 16:48:15][12] Failed:     App\Jobs\ProcessApps

The current new version from today ` 2.4.10` brings the same error messages as mentioned at the beginning.

**Comment by KodeStar** [comment]
Your container doesn't seem to have connectivity to the outside world, exec into the container and see if you can ping anything outside it.

**Comment by drdiablo1337** [comment]
thanks, that was it...

I had been testing the network types host, bridge etc. for the last few days and there was always a deploy error with "Host" that the ports were already in use...

After restarting the RPI and changing to network "Host" it works now.
