### ISSUE TITLE
Enhanced Sabnzbd - API timeout and always display stats

### ISSUE THREAD

**Issue by mrquatsch** [linuxserver/Heimdall#82]
When configuring the API, I wouldn't receive a status result on test.

This was my fault, for not adding a trailing slash. That said, would it be possible to add 'read_timeout' to the request? I think the test just hung on my end, so it appeared to not be working.

Also, could we remove the if statement that prevents stats from displaying all the time? I would love to always see the stats.

From:
`        if($size > 0 || $rate > 0) {
            $output = '
            <ul class="livestats">
                <li><span class="title">Queue</span><strong>'.$queue_size.'</strong></li>
                <li><span class="title">Speed</span><strong>'.$current_speed.'/s</span></strong></li>
            </ul>
            ';
        }`

To:
`        $output = '
        <ul class="livestats">
            <li><span class="title">Queue</span><strong>'.$queue_size.'</strong></li>
            <li><span class="title">Speed</span><strong>'.$current_speed.'/s</span></strong></li>
        </ul>
        ';`

**Comment by mrquatsch** [comment]
The code block removed spaces, so it's a bit tough to read. Hopefully, it still makes sense to everyone.

**Comment by KodeStar** [comment]
The master version has a fix in place for the trailing slash thing.  I'll look into adding a timeout.

I'll look at adding an option as to whether to display stats all the time or only when something is happening.

Thanks for the feedback.
