### ISSUE TITLE
cant access the web interface

### ISSUE THREAD

**Issue by Razerl64** [linuxserver/Heimdall#820]
Hi All,
I'm new to docker 
I had setup Heimdall all was working fine and now getting 500 Server Error

when looking at the logs 

In CurlFactory.php line 210:
                                                                               
  cURL error 28: Failed to connect to appslist.heimdall.site port 443 after 1  
  4088 ms: Operation timed out (see https://curl.haxx.se/libcurl/c/libcurl-er  
  rors.html) for https://appslist.heimdall.site/list.json 

any help would be much appreciated

**Comment by KodeStar** [comment]
Your container seems unable to hit the site, you should try exec-ing into the container and seeing if it's limited to the site itself, or all sites

**Comment by Razerl64** [comment]
thank you I will do some testing

**Comment by jasonmeehan11** [comment]
too bad this is built in... was it to save on doing updates or the size of the image... i manage a lot of dashboards that are internal access only...

**Comment by Mangeloco** [comment]
I am having the same issue, while i can actually open the .json and curl it from the console of that same docker
help please

**Comment by Razerl64** [comment]
> I am having the same issue, while i can actually open the .json and curl it from the console of that same docker help please

I found that the issue was a proxy issue after using the information from https://docs.docker.com/network/proxy/
the container started and was working
