### ISSUE TITLE
Add MySQL compatibility

### ISSUE THREAD

**Issue by hkpanchani** [linuxserver/Heimdall#821]
If we can add mysql compatibility, it can supercharge the dashboard.

**Comment by zhujunsan** [comment]
laravel support mysql out of the box, you can add following settings to `.env` file (add correct settings to each line except the first line)

```
DB_CONNECTION=mysql
DB_HOST=
DB_PORT=
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=
```

and run `php artisan migrate` in the command line and you should be good to go.

**Comment by crkinard** [comment]
It throws nothing but errors after doing this.

It connects and makes all the tables but just 500 errors.
```
heimdall.1.uovzd1mt0w93@rbpi-02    | In Setting.php line 184:
heimdall.1.uovzd1mt0w93@rbpi-02    |
heimdall.1.uovzd1mt0w93@rbpi-02    |   Call to a member function settings() on null
```

**Comment by zhujunsan** [comment]
OK my bad, because there's some db init, you need to run `php artisan migrate --seed` instead.

but even you got this through, I found out the code is actually not follow the best practice of laravel and hard coded sqlite file name in the app bootstrap code... more work needed to support mysql and other db driver :(

**Comment by crkinard** [comment]
So postgres works fine? Been meaning to spin up a docker of that for wikiJS because it will require it soon.

**Comment by crkinard** [comment]
> im using heimdall with postgress, i can say it work fine.

Got postgress working in docker and heimdall linked to it. All seems well so far. Thanks for the info.

**Comment by keriati** [comment]
Should be done with #944
