### ISSUE TITLE
message-container were success messages appear should be position: absolute

### ISSUE THREAD

**Issue by monxas** [linuxserver/Heimdall#825]
Minor annoyance when adding items to the board, the confirmation message pushes the bookmarks down when it appears, and then up when it goes away. The div should be positioned absolute so it doesn't break the flow of the web.

Steps to reproduce it:

1. Add a bookmark, success message appears and edit window closes.
2. when the message goes away, the bookmarks jump up.

**Comment by keriati** [comment]
There is no plan to adjust this for now.
