### ISSUE TITLE
Docker部署无法获取应用图标

### ISSUE THREAD

**Issue by MatrixShoo** [linuxserver/Heimdall#829]
版本：2.4.10
部署方式：docker

目前添加链接的时候，可以选择应用，但是应用的图标无法获取，只显示默认的图标。

容器日志：
````
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
New container detected, installing Heimdall
Setting permissions
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
````

**Comment by CiaoBye** [comment]
我的也是。。。。升级到最新了 也不可以

**Comment by zhujunsan** [comment]
Please make sure your server can access `https://appslist.heimdall.site/list.json`, which provided by GitHub according to it's IP. You can change `.env` file and add `APP_SOURCE` to another website if possible.


请确认你的服务器可以访问 `https://appslist.heimdall.site/list.json`。根据 IP 查询，提供服务的是 GitHub，所以是不是受某些不可抗力影响嗯... 你可以修改配置文件 `.env`，在中间添加 `APP_SOURCE` ，然后改成另一个网站（虽然我也不知道有哪里有镜像或是代理）

**Comment by MatrixShoo** [comment]
> Please make sure your server can access `https://appslist.heimdall.site/list.json`, which provided by GitHub according to it's IP. You can change `.env` file and add `APP_SOURCE` to another website if possible.
> 
> 
> 
> 
> 
> 请确认你的服务器可以访问 `https://appslist.heimdall.site/list.json`。根据 IP 查询，提供服务的是 GitHub，所以是不是受某些不可抗力影响嗯... 你可以修改配置文件 `.env`，在中间添加 `APP_SOURCE` ，然后改成另一个网站（虽然我也不知道有哪里有镜像或是代理）

感谢你的建议，不过这两天这个问题又没有了，暂时不知道什么原因！

**Comment by zzzz0317** [comment]
> Please make sure your server can access `https://appslist.heimdall.site/list.json`, which provided by GitHub according to it's IP. You can change `.env` file and add `APP_SOURCE` to another website if possible.
> 
> 请确认你的服务器可以访问 `https://appslist.heimdall.site/list.json`。根据 IP 查询，提供服务的是 GitHub，所以是不是受某些不可抗力影响嗯... 你可以修改配置文件 `.env`，在中间添加 `APP_SOURCE` ，然后改成另一个网站（虽然我也不知道有哪里有镜像或是代理）

```git clone https://github.com/linuxserver/Heimdall-Apps.git -b gh-pages```
在拉过来的文件夹里面起个 http server，然后改 APP_SOURCE
