### ISSUE TITLE
Could you add RSS Reader?

### ISSUE THREAD

**Issue by nuhll** [linuxserver/Heimdall#83]
Hi, i really like your app (?) how ever its called... :)

Would it be possible, or will u ever add a RSS reader to it?

If you could add that, it would be my new starting page :)

Anyway, great thing. Very much thanks for it.

**Comment by KodeStar** [comment]
Hi nuhll, I'm not sure what you mean?  A link to an rss feed?  If so, there is nothing stopping you doing that now.  Or do you mean have an RSS reader built in?  Not sure how that would work.

**Comment by KodeStar** [comment]
Could add SimplePie integration with https://packagist.org/packages/willvincent/feeds making it look good might be difficult though

**Comment by nuhll** [comment]
Dont know how to explain... so i used my incredible skillz to make a picture...

they say pictures say more then 1000 words... lets see ... :)

![test](https://user-images.githubusercontent.com/34555093/36276557-a959802e-128e-11e8-9223-9d4824ef0c41.jpg)

**Comment by KodeStar** [comment]
Ok, I'll do a bit of research into it

**Comment by anoma** [comment]
Devils advocate, what is the advantage of this over the native/addon RSS support within modern browsers (that you are already using to view Heimdall) or linking to a full RSS webgui with potential enhanced app support.

**Comment by nuhll** [comment]
???

So you could also ask, why this make heimdall? 

It would be the one in all solution.

**Comment by zag2me** [comment]
I think the advantage would be to show it in a transparent way on the Heimdall screen. Not just embedding a web page. Would be a great feature for sure!

**Comment by anoma** [comment]
I am on the fence. I can see where heimdall can be the best at something but i cant see it ever being other than a `good enough` RSS client.

IMO the focus should be on finding a RSS projectt with a good api that then can become an Enhanced App.

**Comment by nuhll** [comment]
No just embedd a web page, i dont think anyone was thinking about implementing it this way.

My screen was just a example, because i dont know how to ask for what i want... :D  

But i guess, now its clear, how its displayed i dont care, like i said, i dont have the technical background. But it would be very nice to have a new startpage. If then the proxy is implemented, this will be the perfect tool.

**Comment by KodeStar** [comment]
Will close this for now and re-look at it at a later date
