### ISSUE TITLE
Export / import of data

### ISSUE THREAD

**Issue by ser** [linuxserver/Heimdall#831]
How one can export configuration including all apps and tags from one Heimdall site to an other?

**Comment by KodeStar** [comment]
Just copy the database

**Comment by ser** [comment]
Should not there be a way to do it via web interface?

**Comment by KodeStar** [comment]
I'm not sure on that one, why overcomplicate something when it's so easy to just copy the sqlite file?

**Comment by ser** [comment]
OK, you convinced me. Thanks :)
