### ISSUE TITLE
Can't connect to webpage.

### ISSUE THREAD

**Issue by Nauseouswave** [linuxserver/Heimdall#832]
Installation: Raspi OS

It shows up as running but when I try to connect I get the error from my browser "(raspi-ip) refused to connect."

I know this isn't a network issue since I can access other apps on the pi.
I also see there are running Heimdall tasks.

edit: I followed [this](https://varhowto.com/install-heimdall-dashboard-ubuntu-20-04) guide

Couldn't access through http://(raspi-ip):7889 or http://(raspi-ip):8000

**Comment by LukasL28** [comment]
Which web server did you use Apache ore Nginx and did you make sure you configure it right? 

I would recommend installing Heimdall through Docker [here](https://hub.docker.com/r/linuxserver/heimdall/)
