### ISSUE TITLE
Error 404 when creating new item - Synology install without docker

### ISSUE THREAD

**Issue by viktor-sc** [linuxserver/Heimdall#833]
Hi,

I'm using a Synology NAS where I run the Synology Web Station (a webserver). Nginx.
There, I created a folder web\heimdall. In the config\database.php I changed the default to be mysql and entered the credentials.
After opening myserver/heimdall/public, it took a while and created a few tables in the database. Then it run into an error 500.
Opening it again created other tables (now I have 11 in total) and actually opened the dashboard.
So, it looked good. But when I try to create an item there's an error 404. It tries to open myserver/heimdall/public/items/create. And in the directory public there is actually no subfolder 'items'.

Any ideas?

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/21951987/163175196-cf1a4a8f-3582-4d2f-8572-448663fc808b.png">

![image](https://user-images.githubusercontent.com/21951987/163177030-5b1b2ff7-dc3a-44f0-bccc-b7e22d5ec10c.png)

Thanks

**Comment by KodeStar** [comment]
Do you have htaccess enabled? items/create isn't in a subfolder, apache should be re-writing the links

**Comment by viktor-sc** [comment]
Wow. Thanks for your quick response.
That seems to be the issue.
Nginx seems to have it disabled. Apache Server works perfectly.
Thanks!

**Comment by KodeStar** [comment]
I missed that you were using nginx, https://github.com/linuxserver/Heimdall#nginx you should just need to add the correct directive
