### ISSUE TITLE
SupportedApp - Ombi

### ISSUE THREAD

**Issue by christianneu** [linuxserver/Heimdall#86]

**Comment by tidusjar** [comment]
Here is some basic information to help with this:

**Logo**: https://github.com/tidusjar/Ombi/blob/master/src/Ombi/wwwroot/images/logo.png
**Homepage**: https://ombi.io/
**Github**: https://github.com/tidusjar/ombi
**Default Port**: 5000

If you need anything else please let me know.

There is also an API available if you would like to integrate further, I could see it quite useful e.g. `Outstanding Requests: 5`
