### ISSUE TITLE
Heimdall Internet Reliance

### ISSUE THREAD

**Issue by escamudo** [linuxserver/Heimdall#860]
I'm trying to run the Heimdall's v2 docker container in an organisation, whoever it is not allowed to have internet access. Is there anyway to disable the reliance on internet access?
 
When I start the docker image, I received an error from the curl trying to resolve the link " cURL error 6: Could not resolve host: appslist.heidmall.site".

**Comment by escamudo** [comment]
Until Heimdall's version 2.4.5 docker it was possible to run the docker without internet, after that version, i'm getting an internal error code 500. Whoever if I connect to the internet all disappeared.

In addition of the error in the last post I also getting this one:

[2022-06-02 12:33:35][19] Processing: App\Jobs\ProcessApps
In StreamHandler.php line 146:                                                                     
  The stream or file "/var/www/localhost/heimdall/storage/logs/laravel-2022-0  
  6-02.log" could not be opened in append mode: failed to open stream: Permission denied

**Comment by KodeStar** [comment]
You could copy the appslist and add a hosts file entry to point it to your local version, not tried to do that

**Comment by jasonmeehan11** [comment]
I just download the list.json file from appslist.heidmall.site
I then hosted it on my own nginx docker container.
Then I modified this file in the heimdall container listing the location of the json file back to my own server:
/var/www/localhost/heimdall/config/app.php

**Comment by ochompsky** [comment]
wtf kind of newbie coding is this that requires external access to make this work offline?

**Comment by aptalca** [comment]
@ochompsky this is the second time today that you're using abusive language in unnecessary comments to issue reports. Please refrain from doing so. Thanks.

This is a final warning.

**Comment by LeehamElectronics** [comment]
This kind of defeats the purpose of being self-hosted. I disable internet access for any service that does not need internet access, Heimdall and any other static hosts fall into that category. This also means that if someone's internet connection fails, their 'self-hosted' services no longer work. Is there a guide on self-hosting the files required for Heimdall to work? Something to do with `appslist.heidmall.site`?

**Comment by jasonmeehan11** [comment]
> This kind of defeats the purpose of being self-hosted. I disable internet access for any service that does not need internet access, Heimdall and any other static hosts fall into that category. This also means that if someone's internet connection fails, their 'self-hosted' services no longer work. Is there a guide on self-hosting the files required for Heimdall to work? Something to do with `appslist.heidmall.site`?

read my comment above, its actually very easy to host the file yourself.

**Comment by eekdood** [comment]
Maybe the solution is to cache the appslist data locally and check for updates on a schedule, with a notification when there is an update available.

**Comment by DrDoug88** [comment]
> > Until Heimdall's version 2.4.5 docker it was possible to run the docker without internet, after that version, i'm getting an internal error code 500. Whoever if I connect to the internet all disappeared.
> > In addition of the error in the last post I also getting this one:
> > [2022-06-02 12:33:35][19] Processing: App\Jobs\ProcessApps In StreamHandler.php line 146: The stream or file "/var/www/localhost/heimdall/storage/logs/laravel-2022-0 6-02.log" could not be opened in append mode: failed to open stream: Permission denied
> 
> It was simple to solve the problem if you used the Heimdall Docker image. So the steps are as follows:
> 
> * To begin, get the "list.json" file from the Heimdall site " https://appslist.heimdall.site/list.json "
> * Then copy the file into the " /var/www/localhost/heimdall/public/ "
> * And modify the following lines in the " /var/www/localhost/heimdall/config/app.php " file:
>   #From:
>   'appsource': env('APP SOURCE,'https://appslist.heimdall.site/'),
>   #TO:
>   'appsource': env('APP SOURCE,'https://localhost/'),
> * Finally, check if the server displays the file 'https://localhost/list.json'

This is a very kludgy method to achieve something that should standard and default.  I'm nearly with ochompsky on the level of frustration. I think Heimdall is extremely well done in every other aspect aside from this. Nice clean look, easy-to-use interface, couldn't ask for more, it's awesome. Many thanks that went into its development. For the purpose that it serves, i.e. a beautiful site to bookmark one's links, having to rely on an external source in order to function is egregious.

**Comment by KodeStar** [comment]
You don't have to change any source files, just change/add `APP_SOURCE=https://localhost/` in the `.env`.
The appslist is frequently updated hence it pulling from there. I'll look into making it more localhost friendly though. Maybe we could fallback to a local version if a remote one isn't accessible.

**Comment by keriati** [comment]
We added a wiki page describing how to self host the apps, see: https://github.com/linuxserver/Heimdall-Apps/wiki/Offline-or-Selfhosted-Apps

Please provide feedback if you encounter issues there.
