### ISSUE TITLE
Hitting enter on a tiles search should open the first item instead of an error page

### ISSUE THREAD

**Issue by jlsjonas** [linuxserver/Heimdall#864]
Currently, when hitting enter after making a "tiles" search, even if there's only 1 item left in the filter, Heimdall will open a new tab with a server error (presumably as it doesn't make sense for it to do something outside of the home page's live filtering.
![image](https://user-images.githubusercontent.com/932193/173192696-289f8a82-dc77-4d4c-89c7-277d042e5c91.png)

It would be great (esp. for keyboard-centric users) if heimdall instead just opened the first item, as if you had clicked it.

This way, you can simply go to Heimdall, have auto-focus on the search (already in place), type in part of what you want and hit enter to go to your desired application all without removing your hands of the keyboard :)

**Comment by keriati** [comment]
see https://github.com/linuxserver/Heimdall/pull/1022
