### ISSUE TITLE
2.4.11 in 2.4.12 image

### ISSUE THREAD

**Issue by OperKH** [linuxserver/Heimdall#866]
label "build_version": Linuxserver.io version:- v2.4.12-ls174 Build-date:- 2022-06-12T09:58:52+02:00

So it must be 2.4.12

But if I open heimdall settings - I see that there is 2.4.11 (Made a clean cache and "clear site data" in dev tools still 2.4.11)

**Comment by OperKH** [comment]
Linuxserver.io version:- v2.4.12-ls175 Build-date:- 2022-06-19T09:58:29+02:00

The same - 2.4.11 inside

**Comment by martadinata666** [comment]
As long as `config/app.php` still 2.4.11 it will stay, maybe it just forgotten versioning update
