### ISSUE TITLE
[BUG] Login dialog redirect incorrect path/url

### ISSUE THREAD

**Issue by sirlordt** [linuxserver/Heimdall#868]
I installed heimdall in custom path like https://mydomain.com/bookmarks

I using multiple users. The login dialog is showed, the user put the password and click en the button login. But the user is send to wrong url.

https://mydomain.com but must be to https://mydomain.com/bookmarks

I already changed the HTTP_URL=https://mydomain.com/bookmarks in the www/.env file.

I using haproxy for reverse proxy and work very well with another features from heimdall. And docker image from linuxserver.io

Your can please fix that?.

Thanks!!!

**Comment by transcendence-x** [comment]
Can you fix this bug? Or come up with a temporary solution. I found it hasn't been fixed yet
