### ISSUE TITLE
Any method to use domain and inner ip address at the both time?

### ISSUE THREAD

**Issue by rickyjoy** [linuxserver/Heimdall#869]
Hi all,
I have a question when I use the Heimdall.
Now I set up a Heimdall for my synology nas and I usually use domain like abc.com to open it from outside.
But now I wanna use Heimdall even if  I am at home. Because the inner ip address is like 192.168.2.xx for my nas, while the address stored in Heimdall is a domain address. I cannot open websites of nas services.
Creating and setting up a second copy of Heimdall can achieve what I want. But I just wanna know if there is any other method to let Heimdall use different address according to the visitor ip?

**Comment by j0nnymoe** [comment]
You would do this by configuring your network/reverse proxy in the correct way to allow you to use your domain inside and outside your network but this of course depends on what nas you have/reverse proxy solution you're running and what router you're using.
