### ISSUE TITLE
Enhancement: Add Dropdown selection next to search engine (For Service-Provider selection)

### ISSUE THREAD

**Issue by inject00r** [linuxserver/Heimdall#87]
Hi,

can you add a dropdown selection on the left next to the search input field which displays all search engine providers?

The default search provider should be select but then you can quickly change it to Nzbhydra for example and shows you a live result list while you enter the search value (auto-completion).

I guess for most of the services user+password and api token should be required.

**Comment by nuhll** [comment]
No dropdown, but a option somewhere. (no dropdown bc u wont change between seartch eninge every time, correct?)

**Comment by KodeStar** [comment]
In current master version
