### ISSUE TITLE
enforced title

### ISSUE THREAD

**Issue by TheAdminFromHell** [linuxserver/Heimdall#884]
Thanks for sharing your great dashboard? with the world. It's a helpful tool for managing the things running in my home lab. I have a feature request or at least help to find out what I need to edit to remove the enforced title/name requirement!

I like to use my logos and images as names, not this boring and ugly white text. 
I have tried using invisible characters, but this did not work :( 

Here is what it looks like now with the ugly white text
<img width="209" alt="b62a1d3a760349b9c53d02e3274995ae" src="https://user-images.githubusercontent.com/33555304/182017795-db4b424a-3df5-4b5a-9035-e0ad6cf915a1.png">

Here is what I want-ish, no white text ^^ 
![b62a1d3a760349b9c53d02e3274922295ae](https://user-images.githubusercontent.com/33555304/182017806-731db011-3501-4321-8982-deef16f52456.png)

**Comment by KodeStar** [comment]
Go to Settings / Custom CSS and add:
```
.item-container[data-name="Whoogle"] .details { display: none; }
```
