### ISSUE TITLE
Excessive DNS Requests

### ISSUE THREAD

**Issue by chrisg991** [linuxserver/Heimdall#888]
I use Pi-hole for my local DNS and have seen a huge spike in resolution requests for my local services since setting up my Heimdall dashboard. All the requests are coming from my Docker host (which has many containers). I have been through each container individually and spun them down and I _think_ it's my Heimdall container which is generating 30ish requests every few seconds. Is there a way in Heimdall or in Docker that I can verify where the DNS requests are coming from and identify why they have suddenly appeared with such frequency?

Thank you

**Comment by j0nnymoe** [comment]
This is happening when you have the enchanced data while a client has your heimdall dashboard open. Unfortunately you can't do much about it if you want the stats showing.

**Comment by chrisg991** [comment]
> This is happening when you have the enchanced data while a client has your heimdall dashboard open. Unfortunately you can't do much about it if you want the stats showing.

Thank you for your reply. Is there a way of limiting how often the enhanced data is refreshed? It seems to be making far more requests than necessary?

**Comment by aptalca** [comment]
I don't believe it's adjustable, iirc it checks once per second for each enhanced app.

If you're worried about dns requests, you can try setting IPs instead of hostnames for the api sections. Or you can turn off enhanced functionality. Or, you can close the heimdall interface when not needed (it only does api calls when it's open in a browser window

But to be honest, I don't consider increased dns requests to be a problem (perhaps a cosmetic one) as it's providing a function and that's what dns requests are for.

**Comment by chrisg991** [comment]
> I don't believe it's adjustable, iirc it checks once per second for each enhanced app.
> 
> If you're worried about dns requests, you can try setting IPs instead of hostnames for the api sections. Or you can turn off enhanced functionality. Or, you can close the heimdall interface when not needed (it only does api calls when it's open in a browser window
> 
> But to be honest, I don't consider increased dns requests to be a problem (perhaps a cosmetic one) as it's providing a function and that's what dns requests are for.

Thank you for replying. I guess I'll just make sure it's closed when not in use, then. I'm reluctant to set the IPs instead of hostnames incase I need to change things around in the future.

**Comment by bengalaviz** [comment]
I have the same issue. Noticed that when the web page was opened, a lot of DNS request were made. Enough to reach the PiHole default limit of 1000 requests within 60 seconds before it would block further DNS requests. I had to turn off the "enhanced" feature to make this go away.

**Comment by keriati** [comment]
Should be resolved with https://github.com/linuxserver/Heimdall/pull/1059
