### ISSUE TITLE
Enhancement: Open in new tabs & have more rows without filling up the current row

### ISSUE THREAD

**Issue by mgworek** [linuxserver/Heimdall#89]
Would like the apps to be able to open in new tab.

Rows. right now a new row of apps only gets created if the current one fills out. It would be nice to be able to move an app or two down to its own row on the bottom of the page and be able to have an empty row separating them from the other apps. Or however else someone wants to customize the screen.

Awesome job on this!

**Comment by KodeStar** [comment]
I've changed it to open in a new tab on master, it will be in the next release.

The rows thing is more difficult, that's not the way flexbox works, I'll have a think about it, it would probably be doable, but would mean completely changing the way it works. Plus the amount of items you can fit on a line changes with the width of your screen. So what would fit on your desktop screen would be completely different on your portrait ipad screen.

**Comment by mgworek** [comment]
Thanks!

Understand about the rows, if you are able to get the groups working that was mentioned earlier, maybe that would work. Not sure flexbox can have tabs which could do the trick. I don't know anything about flexbox but going to look into it more for my own use. I did find this about flex box tabs https://codepen.io/josh_vogt/pen/EaaZbP
