### ISSUE TITLE
Opening the settings menu causes error.

### ISSUE THREAD

**Issue by BobHassok** [linuxserver/Heimdall#904]
When I try to open the settings menu, (http://localhost/settings) I get this error. https://i.imgur.com/gogKZhP.png

Alternatively, when I make a fresh container and open the settings pane, it loads, but if I make any changes and save, it gives me an error 419.

I assume my PHP is botched and I'm probably going to have to make a brand new Heimdall instance?

**Comment by esbeeb** [comment]
This happens to me as well - the error 419 - 2/3 of the time, when I try to save any created Heimdall button.  This problem happens to me ONLY when in a docker container.  The problem does not happen when Heimdall is a native install - not in a container.  Note that these 419 errors occur whether the docker container is in docker-ce 20.10.18 (in Debian 11), or podman 4.2.1.

I highly suggest a native install of Heimdall.  I put some rough install instructions for a native/non-docker install of Heimdall [here](https://old.reddit.com/r/selfhosted/comments/o0x3tr/install_heimdall_dashboard_on_debianubuntu/ioi54bc/).  BTW: your Heimdall will also be about 20x more performant (opening and closing any menu), when not run in docker!

**Comment by tophee** [comment]
@esbeeb thanks for sharing your workaround. 

> your Heimdall will also be about 20x more performant (opening and closing any menu), when not run in docker!

What do you have to back up that statement?

**Comment by BobHassok** [comment]
> 

Sadly, I much prefer having it run in Docker. This issue seems to have begun in the last 2-3 months with the newest image from here and from LinuxServer.io.

**Comment by esbeeb** [comment]
> @esbeeb thanks for sharing your workaround.
> 
> > your Heimdall will also be about 20x more performant (opening and closing any menu), when not run in docker!
> 
> What do you have to back up that statement?

I set up a VM (guest OS: debian 11, host os: Linux Mint Debian edition 5 - LMDE5), and installed Heimdall both in docker-ce, and just a manual install [as above](https://old.reddit.com/r/selfhosted/comments/o0x3tr/install_heimdall_dashboard_on_debianubuntu/ioi54bc/).  I was able to start both Heimdalls at the same time, both in the VM, just listening on slightly different ports (the docker container, listening with the the default of :8080, then with my manual "artisan" command, I specified :8082 instead.  

From the host OS' web browser, I visited the Heimdalls at both links (same URL both times, different ports), each in its own browser tab.  As to application buttons already created: those instantaneously launch the links in new browser tabs.  That's lightening fast: the experience end users would have - using application buttons already set up.

The 20x slowdown is when an admin user of Heimdal opens any menus for adding/editing application buttons, etc.  Everything goes from instantaneously (like 100ms) to about 8 seconds, if it was done in Docker.  That's just to open the menus!!  Then when saving an filled-out application button, 2 times in 3 **if it was in docker only**, I got the highly annoying "error 419", and the application button wouldn't create!

**Comment by BobHassok** [comment]
I've completely discarded my previous Heimdall setup and made a fully new container. When I save a setting it will save, however I have to close the browser tab and reconnect to edit another setting. If I don't close the tab and start again, I'm once again given error 419. For example if I add a url in Heimdall, then save it, I cannot add another URL unless I close the tab and open settings again, or else I get error 419. The same is true is I try to edit user settings, which tab to open in, default search bar, etc.

**Comment by esbeeb** [comment]
I've added a sample nginx conf file [here](https://old.reddit.com/r/selfhosted/comments/o0x3tr/install_heimdall_dashboard_on_debianubuntu/iqupr2k/), so as to get systemd goodness to start heimdall at boot time.

**Comment by KodeStar** [comment]
Looking at that error message you deleted google as an option from the searchproviders.yml but it is what was set as the default provider. You could add google back to the list (look in search providers under Discussions), then go into settings, change the default to something else, then delete it again.
