### ISSUE TITLE
Hash inside list.json dont match the file.zip and SupportedApps stop working

### ISSUE THREAD

**Issue by webysther** [linuxserver/Heimdall#909]
After not receiving any information from Heimdall I started debugging the app and found the zip files downloaded on SupportedApps have the 404 HTML content:

[ArchiveBox.zip](https://github.com/linuxserver/Heimdall/files/9595013/ArchiveBox.zip)

I tried:

- Remove from Authelia
- Remove from proxy
- Rollback to the old snapshot

After looking inside the code I found this:

He gets the list from [list.json](https://appslist.heimdall.site/list.json) and the zip file from the hash inside the app name, but he doesn't check if the zip file is valid or if the URI from the list is returning an HTTP 200.

![image](https://user-images.githubusercontent.com/750007/190923652-a88a9aab-c42a-4ba3-b541-c76f9c4faac3.png)

![image](https://user-images.githubusercontent.com/750007/190923719-6a49244f-4a42-4b1d-8620-a035d0005ba1.png)

**Comment by keriati** [comment]
When the `storage/app/supportedapps.json` file is outdated and has old hashes
and the user selects an app with an outdated hash,
the laravel app will download the 404 page and save it as a zip file.

After that the unzip fails and the app selection also fails on the client side.

I might try to add some better error handling here.

Workaround: Press the `Update App List` button on the `Application list` page.

**Comment by keriati** [comment]
Should be fixed with: 

https://github.com/linuxserver/Heimdall/pull/1018
