### ISSUE TITLE
[Request] Emby as Foundation App

### ISSUE THREAD

**Issue by Attoy** [linuxserver/Heimdall#91]
I see there's already PLEX, what do you think to add Emby too? Is it doable?

Emby Server is a personal media server with apps on just about every device.
More information on [Emby Homepage](https://emby.media/) and the [project page](https://github.com/MediaBrowser) on GitHub.

**Comment by KodeStar** [comment]
Emby is already a foundation app

**Comment by Attoy** [comment]
@KodeStar I apologize, I didn't see the Emby box in the project page.

**Comment by KodeStar** [comment]
No problem :)
