### ISSUE TITLE
Failed to connect to applist.heimdall.site 

### ISSUE THREAD

**Issue by Mangeloco** [linuxserver/Heimdall#913]
Getting this in logs, using Portainer
I can actually access it and curl it from the console of that docker, but I still get this error.
When I try to open Heimdall in the browser, i get a 500 Server error probably because of it.
Help please

**Comment by Mangeloco** [comment]
In CurlFactory.php line 210:

                                                                               

  cURL error 28: Failed to connect to appslist.heimdall.site port 443 after 1  

  4090 ms: Operation timed out (see https://curl.haxx.se/libcurl/c/libcurl-er  

  rors.html) for https://appslist.heimdall.site/list.json

**Comment by webysther** [comment]
Same #909

**Comment by goosebumpage** [comment]
> In CurlFactory.php line 210:
> 
> cURL error 28: Failed to connect to appslist.heimdall.site port 443 after 1
> 
> 4090 ms: Operation timed out (see https://curl.haxx.se/libcurl/c/libcurl-er
> 
> rors.html) for https://appslist.heimdall.site/list.json


Getting the exact same issue after installing it in docker.

**Comment by ghost** [comment]
Same error message:
  cURL Error 6: Unable to resolve host: appslist.heimdall.site (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) https://appslist.heimdall.site/list.json

CURLE_COULDNT_RESOLVE_HOST (6)
Could not resolve host. The given remote host was not resolved.

I can access https://appslist.heimdall.site/list.json

Error：
SERVER ERROR

![image](https://user-images.githubusercontent.com/42706238/207404077-8b41fdb8-8087-4a94-ae28-2cf4e69469b8.png)
![image](https://user-images.githubusercontent.com/42706238/207404148-407ce0ca-7f54-4c25-980f-4cef2aab9924.png)
![image](https://user-images.githubusercontent.com/42706238/207404222-a6e4f077-f395-482c-b77a-fd187a8a7af3.png)
![image](https://user-images.githubusercontent.com/42706238/207404324-539d3dd4-71cc-476a-b1d5-87c66c9f23ff.png)

**Comment by keriati** [comment]
@maxage what version of heimdall did you use?

**Comment by svanhoutte** [comment]
I have the same issue. It seems the image cannot negotiate TLS correctly with applist.heimdall.site. From the docker standpoint internet works, and other websites in https are working such as google and facebook. Any idea on what issue this could be ? 
I m running 2.5.5 version in docker.

**Comment by iomarcovalente** [comment]
I have the same issue. It fails with error 500 when trying to connect to `https://appslist.heimdall.site/list.json`
```
   GuzzleHttp\Exception\ConnectException 

  cURL error 28: Operation timed out after 15001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://appslist.heimdall.site/list.json

  at /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
    206▕         }
    207▕ 
    208▕         // Create a connection exception if it was a specific error code.
    209▕         $error = isset($connectionErrors[$easy->errno])
  ➜ 210▕             ? new ConnectException($message, $easy->request, null, $ctx)
    211▕             : new RequestException($message, $easy->request, $easy->response, null, $ctx);
    212▕ 
    213▕         return P\Create::rejectionFor($error);
    214▕     }

      +13 vendor frames 
  14  /app/www/app/SupportedApps.php:157
      GuzzleHttp\Client::request()

  15  /app/www/app/Jobs/ProcessApps.php:42
      App\SupportedApps::getList()

```
In my case it might as well be that I am hitting corporate firewall and that site is not whitelisted, but after checking with "is it down", it seems that the website is down?

What's the purpose of that file and is it possible to mount it somewhere locally so to avoid that problem altogether?
<img width="691" alt="Screenshot 2023-01-20 at 21 45 35" src="https://user-images.githubusercontent.com/12092106/213811351-237b7296-3c0d-4aaa-912c-d3c1fca991fe.png">

**Comment by ghost** [comment]
I have the same problem. On Qnap with Docker-Compose. Any idea ?

**Comment by Gunb0at-Dipl0mat** [comment]
Hit this issue with Heimdall in Kubernetes. The URL https://appslist.heimdall.site/list.json is missing the last dot to become a full FQDN and it kept unsuccessfully  looping through the domains in my /etc/resolv.conf  with the default ndots value 5.

Manually curling in the pod showed the same error:
`kubectl exec -i -t heimdall-5b449d6554-g29xk -- curl -I https://appslist.heimdall.site/list.json | head -n 2
curl: (6) Could not resolve host: appslist.heimdall.site
command terminated with exit code 6`
Curling the FQDN including the dot works.
`kubectl exec -i -t heimdall-5b449d6554-g29xk -- curl -I https://appslist.heimdall.site./list.json | head -n 2
HTTP/2 200 
server: GitHub.com`

I tried setting the variable APP_SOURCE to the adjusted FQDN with the dot, but no success.
Worked around the issue by reducing the ndot value for the pod.
