### ISSUE TITLE
Heimdall Docker behind firewall

### ISSUE THREAD

**Issue by jesusvm1** [linuxserver/Heimdall#917]
Hello, I'm running heimdall in docker with ubuntu behind firewall, I start the docker but I have the error 500, the logs show the next message;

cURL error 28: Failed to connect to appslist.heimdall.site port 443 after 1
  4090 ms: Operation timed out (see https://curl.haxx.se/libcurl/c/libcurl-er
  rors.html) for https://appslist.heimdall.site/list.json

Can I modify the container to dont try connect to Internet t when I run the docker?

**Comment by KodeStar** [comment]
You can store the apps list locally, though enhanced apps won't work unless you host the site locally as well - https://github.com/linuxserver/heimdall/#running-offline
