### ISSUE TITLE
Rearrange does not line up with the cursor?

### ISSUE THREAD

**Issue by MrDKGE** [linuxserver/Heimdall#925]
I noticed when I wanted to try out Heimdall that the rearrange function is a little weird.
When you try to move the second row of items the issue is not that bad, but the first row of items do not line up at all.
I am not sure what the official name is for this behavior.
Here is a video showing what happens.
https://streamable.com/z7rkze

Tested on 2 browsers to make sure that was not the issue (Edge, Firefox)
I have also recreated the Docker Container to make sure everything was setup correctly.

**Comment by robotfishe** [comment]
I'm experiencing this as well, on two Windows PCs using Chrome and Edge. It's actually making it impossible to grab and move the top row of items on one computer. The workaround I've been using is to open the Inspect panel in Chrome and add "padding-bottom: 100px" to the style for .item-container - that gives each item enough vertical space that you can grab them despite the offset. When you close the inspect panel and reload the page the styling goes back to normal.

**Comment by berwhale** [comment]
I have the same issue.  Running Windows 11 22H2 (OS Build 22623.746) and Chrome version 106.0.5249.119 (Official Build) (64-bit)

**Comment by hoover900** [comment]
I'm having the same issue on MacOS 12.6 with Firefox 106.0.3 & Safari 16.0

**Comment by keriati** [comment]
Fixed by https://github.com/linuxserver/Heimdall/pull/941
