### ISSUE TITLE
I can't access your application on the public network through port forwarding

### ISSUE THREAD

**Issue by Sincejunly** [linuxserver/Heimdall#935]
Like the question, everything else is OK：
![image](https://user-images.githubusercontent.com/96775034/197476885-db1fc0b7-7983-4425-908e-63223e62b532.png)
![image](https://user-images.githubusercontent.com/96775034/197477057-9cf41385-df6a-45db-a62a-cb56a76d5b6c.png)
![image](https://user-images.githubusercontent.com/96775034/197477204-d6037ca3-d0dd-4863-bf92-bf055d9c8741.png)
![image](https://user-images.githubusercontent.com/96775034/197479609-903b2e78-9c9d-4624-8cbc-fb2620e86b2b.png)
It can only be accessed normally when I am on the LAN. I have not found the relevant settings on the UI interface, which is very unreasonable. If you can set it in the file, please let me know

**Comment by keriati** [comment]
I don't know about any setting anywhere in heimdall that would prevent / allow it to be accessed with port forwarding. I would suggest to look for issues on the local infrastructure.
