### ISSUE TITLE
Custom homepage search provider?

### ISSUE THREAD

**Issue by 825i** [linuxserver/Heimdall#936]
Hi,

I host my own SearXNG instance and I'd like to set it as the homepage search engine but it seems only Google, Duckduckgo etc. are supported.

Could you please allow us to use our own? Something that allows POST/GET method.

So I could use eg.

https://myprovider.tld/search?q=my_search_query

Thanks

**Comment by keriati** [comment]
At the moment custom search providers can be added like this: https://github.com/linuxserver/Heimdall-Apps/wiki/Creating-search-providers

**Comment by martadinata666** [comment]
just add your prefered customer search there web root dir `storage/app/searchproviders.yaml`

**Comment by KodeStar** [comment]
https://github.com/linuxserver/Heimdall/discussions/categories/search-providers the details for searx are already in the list from the looks of it
