### ISSUE TITLE
FoundationApp: Airsonic

### ISSUE THREAD

**Issue by anoma** [linuxserver/Heimdall#94]
**Name:** Airsonic
**URL:** https://github.com/airsonic/airsonic
**License:** GNU General Public License v3.0
**Summary:** Airsonic is a free, web-based media streamer, providing ubiquitious access to your music.
**Icon Source:** ![Airsonic](https://github.com/airsonic/airsonic/blob/master/contrib/assets/icons/airsonic_blue_512x512.svg)

**Comment by Futos** [comment]
@anoma I enjoy the style you posting Issues, cool to have directly a summary and icon source ;)

**Comment by halorrr** [comment]
This can be closed now.
