### ISSUE TITLE
Not all provided languages are selectable

### ISSUE THREAD

**Issue by keriati** [linuxserver/Heimdall#952]
@KodeStar: I noticed while looking at the PR requests that 

https://github.com/linuxserver/Heimdall/blob/2.x/database/seeders/SettingsSeeder.php#L127

has 12 languages, but the folder

https://github.com/linuxserver/Heimdall/tree/2.x/resources/lang has 20

**Comment by KodeStar** [comment]
https://www.php.net/manual/en/locale.getdisplayregion.php#115523 possible solution
