### ISSUE TITLE
Walkthrough on converting supported apps to enhanced apps? 

### ISSUE THREAD

**Issue by mrquatsch** [linuxserver/Heimdall#97]
This is probably not the right place for this, but I wasn't sure where else to ask this... 

That said, how can I go about converting a supported app into an enhanced app? I have an idea for PlexPy(stream count). I would also like to create one for RuneAudio(currently playing). 

I'd like to start playing around with these and submitting PRs, but I can't seem to get things to work on my end.

For PlexPy, I've tried modifying localhost/heimdall/app/SupportedApps/Plexpy.php and then creating a localhost/heimdall/resources/views/supportedapps/plexpy.blade.php file. I would have thought that I would see the "config" portion. I'm basically trying to mimic the sabnzbd files.

What am I missing/doing wrong here?

**Comment by mrquatsch** [comment]
Bleh, this can be closed. I was trying to mount the /var/www directory locally and modify the files there. I was able to get things working by going right into the running container and modifying files there.

**Comment by KodeStar** [comment]
If you want to have a chat about things feel free to join the discord channel.  Enhanced apps are still a work in progress which is why there isn't really any information on making them yet.

**Comment by mrquatsch** [comment]
Sounds good. I went ahead and submitted a PR for Plexpy. 

Thanks for the input on the discord channel. It would be nice to get some input from other on what they’d like to pull from the apps when converting to an enhanced app.
